### ISSUE TITLE
radio input lost checked in admin views setup - issues 

### ISSUE THREAD

**Issue by Naroso** [vdm-io/Joomla-Component-Builder#104]
I have a issues when I setup a admin views

![image](https://user-images.githubusercontent.com/15976506/28198773-c2ba0cb8-688a-11e7-903f-0413f8243136.png)

![image](https://user-images.githubusercontent.com/15976506/28198753-a9268876-688a-11e7-9a68-1a64789f4470.png)

I should always to fix them each time to setup admin views again 

Please check and fix this issue
Many thanks
Neo

**Comment by ro-ot** [comment]
This is not a JCB issue but a Joomla issue, the work around is to open the modal a second time. Since the values are actually saved in the database, if you set it up the first time. It seems like the JavaScript is just not loading the values correctly the first time you open the modal, but the second time it is successful. This means the first time you open it, and see the values are missing, just close the modal and open it again and you will see the values are still there. Then only should you make our changes to insure all values are kept.

JCB does not controlled the code that loads the modal, it is a standard Joomla field that gets build by Joomla it self. So if there is to be a fix it should come from them, so you are welcome to report the issue with them.
