### ISSUE TITLE
fields do not retain onchange attribute in xml

### ISSUE THREAD

**Issue by stutteringp0et** [vdm-io/Joomla-Component-Builder#129]
Many (most) Joomla input fields allow an onchange attribute in XML - however, fields created via JCB retain the configuration in the builder interface, but not in the compiled XML.

**Comment by Llewellynvdm** [comment]
The option to use the onchange feature can be added to any field type and then used. So if you find a field type that does not have this property, simply open that field type and add it.

You can open the **text** _field type_, as an example of how this property looks when it is added since the text field has this Property.

![image](https://user-images.githubusercontent.com/5607939/31151008-12078548-a896-11e7-8b25-19c45133f563.png)

![image](https://user-images.githubusercontent.com/5607939/31151058-380606d4-a896-11e7-9a78-60383c180a64.png)

IF for some reason your text field type does not show this option, you my need to uninstall JCB and reinstall the latest version to get access to all the JCB/Joomla fields, or you will need to add this property to the field type your self.

**You can extend the JCB field type yourself**... they are dynamic in nature so to be able to adapt as Joomla improves or adds and removes field types.

I just setup the field types that I use, and the properties I thought most common. I did not add every possible XML property... but you can do so on your own.

**Comment by stutteringp0et** [comment]
I see!  I haven't made it through all of the videos yet.  I kind of dived right in...
