### ISSUE TITLE
Create Folder in Images

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#130]
I have some media fields that I have set to a certain folder that I would like to have exist in the Joomla images folder. I have tried a few things, but they don't seem to be working, so I wanted to see if I might be missing something.

In my component settings, I selected the folder that I wanted, setting the target path as /images/, but JCB creates the folder in the media folder for the component.

In some reading of docs, I have come across the following documentation, but can't find a place too add code that would accomplish this. The function install($parent) is of course in the code, but see no option for adding code to it. I'm not sure if custom code would work there or not?  Am I missing something?

> Put in the header of install script:
> 
> jimport('joomla.filesystem.folder');
> 
> and inside of function install($parent) put the code:
> 
> $path = JPATH_SITE . DIRECTORY_SEPARATOR . "images" . DIRECTORY_SEPARATOR . "mycom";
> $mode = 0755;
> JFolder::create($path, $mode);
> DIRECTORY_SEPARATOR for Joomla 3.x

**Comment by Llewellynvdm** [comment]
In the Component view => PHP tab => any of the install script areas can be used.

The correct place for component images is really the media folder... but yes if you want to place stuff in the image folder best use the install script.

**Comment by mwweb** [comment]
The majority of images are in the media folder foe the component. The images folder would be for selecting, as an example, a preacher image. 

I'll have to experiment with custom codes I guess to see if I can get out to properly add where I want (function install).

I just wasn't sure if I was actually missing something.

**Comment by Llewellynvdm** [comment]
Let me see... the fields and folders option that is used to include folders and files can not directly place those folders and files outside of the component areas... which is the **front component folder**, **admin component folder**, **media folder** and of course the language folders.

So that means you must during install... take the folder out of **one of these places** (so you still add it to one of these the component areas) and move it from there to the desired place. Here is a little snippet that I have used n the past inside the Preflight (install) function.
```
$app = JFactory::getApplication();
$installer = $parent->getParent();
$src = $installer->getPath('source').'/media/demo';
$dest = JPATH_SITE.'/images';

if (!JFolder::move($src, $dest, '', true))
{
	$app->enqueueMessage('Could not copy demo images to the images folder, please make sure destination is writable!', 'error');
}
```
