### ISSUE TITLE
script.php install() and update()

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#131]
As I'm learning the interworkings of JCB, I noticed in the script.php file that gets generated I don't see a way to add code to the install() and update() methods. Am I correct in that this is missing? And if so are there plans to add it?

**Comment by Llewellynvdm** [comment]
No they are there... in the component under the PHP tab there is various PHP areas that you can target the install script.

**Comment by kevincam3** [comment]
Correct, but there is no "Install" or "Update"

You have the following only:
- PHP Dashboard Methods
- Add PHP Preflight (install) 
- Add PHP Preflight (update)
- Add PHP Postflight (install)
- Add PHP Postflight (update)
- Add PHP Method (uninstall)

What's missing is:
- Add PHP Method (install)
- Add PHP Method (update)

Looking at the JCB source code there is nothing being added from the JCB Component to these methods

![image](https://user-images.githubusercontent.com/870934/31186003-ce67b3f8-a903-11e7-853f-e930f06120b3.png)

**Comment by Llewellynvdm** [comment]
You can really do everything you need with just those that are there. Since if you want to update there is two areas to use and if you want do something on install there is two areas to use. I thought that would be more then enough. If you really feel that adding those extra two (not so often used) options let me know and I will add it in due time. I was not planning of doing so... five areas that also target the same concepts seemed enough.

**Comment by kevincam3** [comment]
No need to add them then. As I said. I'm still learning and just didn't know if they would be needed. Thanks for the explanation.
