### ISSUE TITLE
Is there any thing in JCB that helps with creating the help pages for a component

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#134]
Since I'm learning JCB and going through all the screens/tabs/etc. to understand it, I'm toying with the idea of doing help screens. This made me wonder if JCB has anything to help with this.

**Comment by Llewellynvdm** [comment]
Well the [Sermon Distributor](http://vdm.bz/get-sermon-distributor-key) has a help structure that can be reused in any other component.

It is the same help structure that is available in the JCB component.

So yes once you have the Sermon Distributor installed, you can simply add the help back-end view to any other component and it will dynamically add this feature to that component.

This help menu concept is a very dynamic help idea. That allows you to ship the component with some help menus... but allows the user to improve on it for their own website.

Please watch this quick tutorial if you have any more questions:
https://youtu.be/nw9YPu9emws

**Comment by kevincam3** [comment]
Actually,

I was looking for just the ability to add the context help the way that Joomla! does by adding something like  JToolbarHelper::help( 'MY_COMPONENT_HELP_VIEW_TYPE1', true ); to the view.html.php

See this:
https://docs.joomla.org/Special:MyLanguage/Help_system/Adding_a_help_button_to_the_toolbar

I dosen't look like there's a way to do this without doing a custom admin view for all my views. It would be nice to be able to inject code into the view.html.php file.

**Comment by ro-ot** [comment]
I don't want to be rude... but @kevincam3 are you being serious?

Did you watch the video, @Llewellynvdm has done an amazing job to explain how to add help toolbar feature to any JCB component. What he did not tell you is that the compiler is a actually do the work in adding the `JToolbarHelper::help` to your components __view.html.php__ files and so much more.

So all you really need to do is add the helper document view to your component and the JCB compiler does all the hard work for you. 

How can you then say : 
>I dosen't look like there's a way to do this without doing a custom admin view for all my views. It would be nice to be able to inject code into the view.html.php file.

- Do you have Sermon Distributor?
- Did you add the view?
- Did you look at the code in the view.html.php files?

It is clear to me that you did not, and that you are making statements that have not merit.

The only reality is that if you don't have access to Sermon Distributor you don't have access to the helper document (admin view) But if you are able to read PHP you can look in the compiler and see how the helper structure is triggered in the compiler.

Go to line [878](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/e_Interpretation.php#L878) in the e_Interpretation.php

You will see that it checks if you have a __help_document__ view ones it finds one it adds a bunch of files to the component.

So to me it seems like you did not follow the instructions @Llewellynvdm gave in the tutorial, because if you did then JCB would have added all you read on https://docs.joomla.org/Special:MyLanguage/Help_system/Adding_a_help_button_to_the_toolbar

**Comment by Llewellynvdm** [comment]
Hey @ro-ot thanks for your input! but it seems @kevincam3 is just pointing out that you will need an admin view to add the **JToolbarHelper::help** to the **view.html.php**

This is in fact true ....

Tell me @kevincam3 what do you think about the custom scripting options that allow you to add custom scripting via placeholders anyplace in the code? Have you tried using that?

Then who you say we need to add the option for you to add custom scripting in that area as well in the JCB admin edit view?

**Comment by Llewellynvdm** [comment]
Hey @ro-ot 

Thank you for the complement, but please give @kevincam3 little more credit, he is also just tying to help.

**Comment by kevincam3** [comment]
I did see something like that and was trying to understand where in the admin I would trigger that replacement. What I saw in the compiler code for the display was this: ###LINKEDVIEWITEMS### But I like the idea that you suggested which is to be able to add custom scripting via placeholders anyplace in the code.

**Comment by ro-ot** [comment]
@kevincam3 sorry man, I jumped to conclusions to quickly.

Watch this tutorial to help with the custom coding idea:
- [Automatic import of custom code during compilation in JCB](https://youtu.be/DFMfIl-VkSk?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE)
- [JCB manual custom code implementation](https://youtu.be/KiAtJawZ3oo?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE)

@Llewellynvdm thanks! I putt my foot on my mouth.

**Comment by kevincam3** [comment]
@ro-ot excellent. This is exactly what I needed to accomplish my goal. I'm also happy to see that in it's current state it doesn't include all the /***[INSERT<>$$$$]***/ type tags anymore and I can just edit the code directly in JCB after the first insert. 

Thanks.
