### ISSUE TITLE
Creating a Site View that doesn't display dynamic data by default loads the last Dynamic Get data.

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#143]
As I learn to use JCB, I'm creating tutorials . While creating a tutorial adding a basic site view. I just wanted to add some HTML to display in the view. I later noticed that by default it had values populated for Main Get and Dynamic Get (snippet) So now my simple HTML view is actually making calls to the database. I think these dynamic get values should be empty by default and not pre-selected with something which appears to be the last Dynamic Get created.

 
![image](https://user-images.githubusercontent.com/870934/31761239-047b85ee-b496-11e7-834f-55e936a2d2f5.png)

**Comment by mwweb** [comment]
It's just grabbing the first get, alphabetically. I'm guessing that you're suggesting that Llewellyn maybe add a -- Select Get -- placeholder as the default?

**Comment by kevincam3** [comment]
Yes, that way if I don't want to include any dynamic data, I'm not forced to do so. Just a thought

**Comment by Llewellynvdm** [comment]
No data... hmm okay... we can look at that.

**Comment by Llewellynvdm** [comment]
Just a closing note, here.

Best work around is to setup a dynamic get that just gets the user ID (or something insignificant) from the database, as basic or default(blank) get. Since if we remove the main get from that page it removes the model and the view... it does not get build at all. Believe me the mix  also called _polymorphism and encapsulation_ going on there is hard to fathom even with a cup of very strong coffee, lol...

To changes this will be a little much at this time, and the workaround is like nothing. But we could look at this again sometime in the future. As I can see the use case for these kind of things, specially if you just want to use the controller. Like I do on the API front-end of JCB.

So sorry, but this needs to take a seat for now! Hope you will understand.
