### ISSUE TITLE
created date show in wrong tab after update

### ISSUE THREAD

**Issue by sepehr09** [vdm-io/Joomla-Component-Builder#144]
hi & thanks for new update,
before this version we select tab 15 to showing created date field in default tab but after update tab 15 is not more existing & how we can show created date in default tab? ( i wan to show created date in admin listview)
![image](https://user-images.githubusercontent.com/11753906/31860014-0017487a-b721-11e7-82d9-cc5c035f8846.png)

best regards!

**Comment by Llewellynvdm** [comment]
You, sure you can still setup tabs. Please watch this tutorial https://youtu.be/NFp_CtE0LZI

**Comment by Llewellynvdm** [comment]
ahh, I now see what you really asking.... great stuff, with the next update I will add that option back in. Sorry :) I missed that, but hey now there is one more tutorial :+1:

**Comment by Llewellynvdm** [comment]
I was looking for a quick work around and it seems we are stuck.... I am on a difficult place I have already fixed this issue, but since I also started moving the **Joomla Component View** away from the repeatable fields like yesterday..... my local _JCB as a mapped component_ has diverged from the working package so drastically that I can not do a quick update. I have only two options, one is to wait until the next release that other is to give you some custom code to place in the compiler to do a temporal work around... how urgent are you for this? can you wait a week?

**Comment by sepehr09** [comment]
Thanks for your attention, i'm glad we have you!
if you can send me custom code It will be very good but if you are busy right now i can wait.
If any help I can do, I'll be happy to do it!
thanks.

**Comment by Llewellynvdm** [comment]
Okay I found a work around, that does not need any code.

Just add a tab, named `publishing` all lowercase. then add that field `created` to that tab and it should work. 

Let me know :+1:

**Comment by Llewellynvdm** [comment]
Just not that this workaround will only work when you replace the default fields so you can use them in the list view, or what to tweak the field in some way. With the coming release you will be able to add other fields to the publish tab as well as the default once. So it will work as before only better.

**Comment by sepehr09** [comment]
yes that's work! actually i'm test adding tab before but the key is all words must be lowercase!
