### ISSUE TITLE
Change the language strings from within JCB

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#149]
I noticed that I want to change the submenu name displayed. I can manually change the string in the language file but I just wanted to know if there's a way to do this from within JCB since I'm thinking if I recompile it then my changes will be overridden

**Comment by Llewellynvdm** [comment]
All language strings in JCB are build from your own input values. This will naturaly mean that you should open the view and change its name to change the language string. But convention all views and their names are linked to the table name and the controller name and so on... so if you change the view name it will also change the table name and so all the file names. This is part of good practice and what makes JCB possible. 

So in summery give you fields and views the right names from the start :+1: since you language files are build from your own input values in relationship with good old conventions that makes development scalable and integratable.

**Comment by kevincam3** [comment]
It would be nice not to have them match for example in Joomla! core they have "Field Groups" but the view is "groups" I wanted to leave my view=waves but I wanted to name the menu item "Sound Waves" currently to do this I'll have to edit the language file outside of JCB.

**Comment by Llewellynvdm** [comment]
@kevincam3 I can add this as a feature request.

**Comment by Llewellynvdm** [comment]
@kevincam3 I think [this tutorial will resolve](https://www.youtube.com/watch?v=q5NwKGnOHoQ&index=51&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE) this issue.

**Comment by kevincam3** [comment]
Hi @Llewellynvdm,

Nice feature for doing translations. Great job. It doesn't really address what I was trying to do since I'm only working with one language. English.

**Comment by Llewellynvdm** [comment]
Yes it does, since it explains why you can not make changes to the English strings. IT also points you in the right direction to make those changes in field, view or other instead if trying to do so in the translation manger.

**Comment by kevincam3** [comment]
Okay when I get a minute I'll take a look at this again. I just remember it was using the same value I set for the view name as the value for "view=[view name]" and also using this for the name in the submenu for the component and I wanted them to be different. So I'll check again and see if this is now doable.
