### ISSUE TITLE
New Component ID appearing in Compiler List

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#17]
Hello again,
Actually a couple of bugs here:

1. In creating a new component, two bugs - In the compiler, the ID of the component, rather than the name of the component, is appearing. Compiles file tho. HOWEVER, the name of the component does not appear in the component list so unable to access to edit. Works fine tho if you create a new component by saving a copy of an old one.

2. In the component - new or older components, including sermon builder - in the list where the admin views are added - the first admin view's attributes are not saved or defaulted to being blank. Specifically, Main Menu,Dashboard list, Submenu, Has Metadata, Add Access

I have checked out two above for adding custom views or site admins.

Thanks Llewellyn!
Paola

**Comment by paolavness** [comment]
Oh actually, I've just realized when using the 'save a copy' of an existing component to create a new one, it saves the name of the component used to create it, rather than the new name...

**Comment by paolavness** [comment]
Ah this is embarrassing, I had not given the new component 'System Names'! But bug 2 above stands.

**Comment by Llewellynvdm** [comment]
Can you record a video of this? I am not sure I understand what is going wrong here... I have done that action many times without any issues. So I need to see the exact steps you take.

**Comment by paolavness** [comment]
for bug 1 above? I simply created one without a 'System Name'

for two above, opening any component and going to add new admin views - the first line of goodies for the first admin does not save. 

sorry, don't have view recording capacity or time right now!

**Comment by paolavness** [comment]
Here is an image for the second bug

[bug2.pdf](https://github.com/vdm-io/Joomla-Component-Builder/files/376302/bug2.pdf)

**Comment by Llewellynvdm** [comment]
Ahaa, yes this is a Joomla bug, not actually due to Component builder. It does save the data, but when you reopen the component, and open those selected admin views, it does not show them selected. 

So if you close the repeatable and reopen that same repeatable field it will now show the stored selection.

If you open it and it does not show, I mean the first time around, and then make changes and click save it will actually save those first row as not being selected at all.

So I will usually open the repeatable, close it and open it again and then only make my changes..... Sorry about that, I am sure Joomla will fix this some time soon... hey you could actually try and fix it for them and make a pull request :)

But until then this is the work-around. Let me know if you still don't get it to work for you.

**Comment by paolavness** [comment]
Aha! 

I've actually found an work around - I've added a new admin view at the top row but not selected an admin view... CB seems to save it, with nothing in, but does not compile it in. This is great! so i don't have to worry about re-setting the goodies for this field each time I save. 👍

**Comment by Llewellynvdm** [comment]
ya... it is little tedious... it seems to only happen if you have many repeatable fields on the same page with huge field selection options.

But sure that data does not change unless you open the field and click save to close it. So if you normally open the view and make other changes, and save that data should remain unchanged.

**Comment by paolavness** [comment]
That's good to know and be aware of, thanks Llewelyn!
