### ISSUE TITLE
I have created on file type field but it doesn't seems to be working

### ISSUE THREAD

**Issue by programmerhk** [vdm-io/Joomla-Component-Builder#177]
I have created on file type field but it doesn't seems to be working - I checked databas its blank column and i checked server as well which hasn't uploaded any file 

![image](https://user-images.githubusercontent.com/30821271/32591214-3b287ec6-c544-11e7-9456-80f08b54779b.png)

Is that anything is still  in progress?

**Comment by Llewellynvdm** [comment]
Okay the media field type is the best option to upload files since it does not require any custom scripting to work.

Please give us more information on what you are doing, since that is also not clear. 

Field-Types and not the same as Fields... you build field and use field types to do that. So even your explaination does not sound right.

Make sure you [watch all tutorials](https://www.youtube.com/playlist?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE) before continuing :+1: 
Here is a [breakdown of the tutorials](https://github.com/vdm-io/Joomla-Component-Builder/wiki)... but best just watch all!

**Comment by programmerhk** [comment]
hey @Llewellynvdm 

I have figured it out with custom field type. As i was not able to upload file through file type field

So i have created custom field type on model/fields then with some extra html of facility to remove uploaded file as well 

![image](https://user-images.githubusercontent.com/30821271/32599953-0afb1c7a-c564-11e7-9d8c-d6493f4fc10d.png)

But really you should give it try create couple of text field and couple of file type field and create component. after publishing component when we try to add new item its not storing file to server nor its storing value to database field

May be I am working on latest joomla - which may be not supported

Have figured it with otherway but just checking if you can update builder if you found same issue :)

Regards

**Comment by Llewellynvdm** [comment]
Hmm seems like I mis read... sorry. Yes the file type field will require custom scripting, and JCB does not do that basically because the implementation is just crazy...

Would you be willing to help with this? Should I add this as a feature request?

**Comment by programmerhk** [comment]
I have already sorted it but other way ;)

**Comment by programmerhk** [comment]
And yes one more thing i needed to update

![image](https://user-images.githubusercontent.com/30821271/32600165-b8fb191a-c564-11e7-8637-14864e38ac9d.png)

adding code to upload file some where

BTW i am same developer of https://github.com/vdm-io/Joomla-Component-Builder/issues/171   
Just working on 1st project of joomla

Seems your plugin has helped a lot to me :) Thanks a lot
