### ISSUE TITLE
Duplicated field type does not retain the type

### ISSUE THREAD

**Issue by stutteringp0et** [vdm-io/Joomla-Component-Builder#189]
### Steps to reproduce the issue
I found this after duplicating the Subform field type, naming it Subform XML and altering the "fields" property to "formsource".  A relatively simple change, saved and published.

The result was a 500 error after publishing, and a bit of digging I found that the field "type" was now "subform_xml" instead of "subform" as defined in the field.

Manually editing the xml resolved the issue and everything worked as expected.  Something in the code isn't honoring the type attribute in the field XML when creating the form XML.

### Expected result

xml field retains correct type

### Actual result

xml field gets a type which is based on the field name.

### System information (as much as possible)

J3.8.2

### Additional comments

I may dig into this next week

**Comment by ro-ot** [comment]
It seems strange, this is not the correct behavior. Check that you did not only change the xml, but also selected the subfrom field type:

![image](https://user-images.githubusercontent.com/2594383/33514343-09ad86e2-d75b-11e7-816d-ff38a7386019.png)

**Comment by ro-ot** [comment]
You will see the path of building a field some what when looking at this function called [setDynamicField](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L708) the type is always set with the [typeName](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L714) the type name is build in the [get.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/a_Get.php#L1260) of the compiler on line [1782](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/a_Get.php#L1782), and as you can see it is the type name in JCB. So make sure you also did not change that.

Then you will see in this [block of code](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L1316) the type is set and nothing here will change the subform field type. Only as a last option will it [fall back the your xml values](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L1335) unless it is custom.

So the function to study and follow is [setFieldAttributes](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L1297) as here the field things are happening.

I still think it is just a setting that is wrong, and not a bug.

**Comment by stutteringp0et** [comment]
I thought it was strange too... Nowhere did I save "subform_xml" or "Subform_xml"

![screenshot from 2017-12-02 09-32-49](https://user-images.githubusercontent.com/310899/33517118-cc8ea226-d743-11e7-8191-0a1b9e4e90c9.png)
![screenshot from 2017-12-02 09-30-14](https://user-images.githubusercontent.com/310899/33517113-ae54689a-d743-11e7-956a-b2b8c936a7ee.png)
![screenshot from 2017-12-02 09-31-38](https://user-images.githubusercontent.com/310899/33517114-aeecc46e-d743-11e7-9c94-dca0385824ff.png)

**Comment by stutteringp0et** [comment]
I created the fieldtype the easy way, I used batch to copy the Subform type and just modified the name value and the fields property (changing it to formsource).  The only place I typed "XML" was in the name.

**Comment by ro-ot** [comment]
@stutteringp0et what you are trying to do with subfrom will not work with JCB at this time. Why? because there can be only one _subform_ **fieldtype**. You can not copy a **fieldtype** and change some properties and thing it will work. It must be a new **fieldtype**. That means a new **fieldtype name**.

Yes you change the name and when JCB builds the field it uses like I said
>is always set with the typeName

That means the actual name of the fieldtype, hope you get it now :+1: 

I think we can give @Llewellynvdm a heads-up for a feature request here :100: 

The subform at this time works the same way the repeatable fields worked, you add field ids that you already created in JCB to the `options="1,2,3"` and the JCB builds your subform or you, no need to write up some custom xml.

But to grab some custom xml may be useful, yet it is not how it works at this time. Subfrom is hard coded in to not work that way, but I know @Llewellynvdm will be willing to improve this when he gets time.

**Comment by ro-ot** [comment]
So just to make it clear, building a subfrom is very easy. You first create the fields you want in the subform.

Like:
- Name Field (with all its settings and stuff)
- Description Field (with all its settings and stuff)
- Age Field  (with all its settings and stuff)
- Email Field  (with all its settings and stuff)

After having saved them each get an ID
- Name Field (4)
- Description Field (5)
- Age Field  (6)
- Email Field  (7)

Then you create your subform field:
```
<field 
	type="subform" 
	name="editor" 
	label="Form Editor" 
	layout="joomla.form.field.subform.repeatable-table" 
	multiple="true" 
	fields="4,5,6,7" 
	icon="list" 
	maximum="999"
/>
```
Your good to go!

**Comment by stutteringp0et** [comment]
I'm aware of how jcb created subforms work.  The form I'm creating will have a few hundred fields with nested subforms.  It's way more efficient to write xml.

My problem isn't creating forms, it's that the field type doesn't honor the type defined in the xml

**Comment by Llewellynvdm** [comment]
Okay thanks @ro-ot for your great support here!

@stutteringp0et sorry that is not they way I choice to make it work. You can say that I asked the question who has the most authority, and the fieldtype **name** won the vote in the case of subforms, for various reasons.

The point @ro-ot was making and is correct, is that you tried to create a new fieldtype called subfrom when there is already a fieldtype called subform. This you should not do period. 

Second point is that then name of the fieldtype is what we use and not the name in the xml as unintentional mistypes in the xml is avoided this way. I mean if you select text field type you will not want any thing else but text field type right.

Now in your case you selected subfrom-xml (one you cloned) as the fieldtype and that is exactly what you got, yet Joomla does not have that kind of fieldtype so it will obliviously broke. Nothing dishonoring about that, it is how JCB works to protect you.

I realize subfrom is not yet able to utilize its full potential here, you are welcome to look at the core code @ro-ot pointed to earlier in the issue and make a pull request, it is around those areas we will need to make a few changes, and then your new attribute **formsource** could work no problem

I have not used that before so can you explain a little more how that should behave? Since it makes sense to just extend the subform fieldtype instead of trying to have to fieldtypes with the same name.

**Comment by Llewellynvdm** [comment]
Okay I have a quick fix for you until the next release, you will need to change a few lines in the compiler and then in the original subform fieldtype:

**Comment by Llewellynvdm** [comment]
On line [1422](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L1422) in the Fields file of the compiler change to:
```
elseif ($property['name'] === 'extension' || $property['name'] === 'directory' || $property['name'] === 'formsource')
```

**Comment by Llewellynvdm** [comment]
Under Line [1055](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L1055) in the same file add:
```
// if we detect formsource we do not add the form
if (isset($fieldAttributes['formsource']))
{
	$fieldSet .= PHP_EOL."\t\t />";
}
else
{
```
and under line [1127](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L1127)
```
}
```

**Comment by Llewellynvdm** [comment]
Now open the original fieldtype called **subform** and add the following attribute:
![image](https://user-images.githubusercontent.com/5607939/33519888-e692c5d8-d7b8-11e7-8894-c604226f37f0.png)
Enlarge the pick to see :)

Also make one more change and you are good to go, change the fields attribute to look like this:
![image](https://user-images.githubusercontent.com/5607939/33519961-259132aa-d7ba-11e7-9b93-adf0af30a0be.png)
Mainly un-check the Mandatory field

Now the subform field should work as expected, let me know....

**Comment by ro-ot** [comment]
That was easy :+1:

**Comment by Llewellynvdm** [comment]
I have update the core with these changes so all should continue to work after the upgrade.

**Comment by stutteringp0et** [comment]
That's a good solution.  I have to point out that there's as much of a possibility for a typo in the name as there is possibility for a typo in the xml...  and it makes more sense to take xml -> xml .....

I have to wonder, why the xml isn't generated using simpleXML and converted to text rather than being concatenated together?  That's a change I might make  PR for.

**Comment by stutteringp0et** [comment]
I need to look at something other than the extension I'm working on - so I'm rewriting c_Fields.php to use simpleXML instead of concatenation.  When it's ready I'll issue a PR.

Would there be any objection if the rewrite makes subforms into separate xml files?  I'm sort of partial to that approach.

**Comment by stutteringp0et** [comment]
Done - #191
