### ISSUE TITLE
CustomUser - Unique Groups & ACL

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#20]
Hello again Llewellyn,

I have a couple of questions here regarding ACL & CustomUser

**1. ACL on Installation**
I'd like to install unique ACL groups for my component when the component installs, so that when users assigned to these groups, they only see my component. Something like 

> |-MyComponent Admins
> |-|- MyComponent Super Admin
> |-|-|- MyComponent Junior Admin 

 I'm assuming i'd do this with a mysql script to first create the ACL groups, then assign the 'Target Groups' (from the global options) for mycompent to these groups.

Is this the correct way to go about it? I wondering if there is a simpler option? I'm also wondering if you have an idea on SQL to create the ACL groups?

**2. CustomUser & Unique ACL Group** 
Different parts of my component should only be accessible to certain user groups. With the above ACL, can you tell me what SQL i could use to create a CustomUser field that lists users only in certain ACL groups?

Thank-you!
Paola

**Comment by Llewellynvdm** [comment]
This is huge, and to explain will take some time... I will have to create another tutorial just for this. Please add it to the suggestions here:  https://github.com/vdm-io/Joomla-Component-Builder/issues/8

I have already build very advanced components that does extreme smart ACL concepts... I will do my very best to explain more detailed in a new tutorial. Yet do note that I did mention some of it already in the existing tutorials, have you watched all of them?

Since it will take some time before I add the new tutorials... here is some quick pointers.

Instead of creating new groups at the component install, add fields in the component settings where the user can link existing groups to the various "departmental groups" of your component.

In this component I did just that >>> [see xml](https://github.com/namibia/CBP-Joomla-3-Component/blob/master/admin/config.xml#L337) >>> [see Helper Method](https://github.com/namibia/CBP-Joomla-3-Component/blob/master/admin/helpers/costbenefitprojection.php#L29) >>> [see use in model](https://github.com/namibia/CBP-Joomla-3-Component/blob/master/admin/models/companies.php#L212) >>> [see use in controller](https://github.com/namibia/CBP-Joomla-3-Component/blob/master/admin/controllers/company.php#L86)

No to add all these custom scripts can be done in the various views (add PHP) text areas. also to setup the helper functions can be added to the component helper (PHP) text area.

**Comment by paolavness** [comment]
Thanks Llewellyn, these pointers do help somewhat.

The videos are great but without an index to search and hone in on specific topics, its a drag and time consuming to go thru allot of what I don't need to find what I do... And then recall where in what video i came across what i was looking for... You know, the coding process does not follow a linear process, especially when new to a frame work. 

Personally, I'd prefer quick howto's - 10min video snippets - or even better, help file which I can search and hone in on.

All the same, so much gratitude for what is :)
Paola

**Comment by paolavness** [comment]
Hello again,
Another thought on this...  I am assuming that to login, mycomponent_contact will need to be linked to a joomla_user.

I was just thinking, if I link mycomponent_contact to a joomla_user and put the joomla_user in a group, couldn't I achieve ACL with this? 

What would the benefit be of linking my component_contact to a group AND a Joomla-user?


Thanks again, 
Paola
