### ISSUE TITLE
Insert a php code in a Form admin

### ISSUE THREAD

**Issue by marini91** [vdm-io/Joomla-Component-Builder#221]
Good evening, I'm just using this very useful component but I do not understand how to enter a **php code** in the validation of an admin form. I try to explain, I would like when I click on "Save" or "Save and Close" start a php code, for example to send an email. I added my code in the "**Add PHP (AJAX)**" block of the **View Admin**, the program compiles but when I click on the "Save" button it does not work. Do you confirm that I have to enter the code in that block? Where am I doing wrong ?

Thank you

**Comment by Llewellynvdm** [comment]
Have you watched [all the tutorials](https://github.com/vdm-io/Joomla-Component-Builder/wiki)?

Your question has a very wide answer that requires us to know many things. This makes if very hard to help you, due to our own time constraints.

We want to use the issue area for issues related to the development of JCB and not so much the use, for that please use the [forum](https://groups.google.com/a/vdm.io/d/forum/jcb) and [tutorials](https://www.youtube.com/playlist?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE).
