### ISSUE TITLE
Do I custom my own router rule or modify JCB router file? 

### ISSUE THREAD

**Issue by kwaninmacau** [vdm-io/Joomla-Component-Builder#223]
Do I custom my own router rule or modify JCB router file? Any advice to custom router rule?
Thank you very much!

**Comment by Llewellynvdm** [comment]
Have you watched [this tutorial](https://www.youtube.com/watch?v=IQfsLYIeblk&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=45)?

JCB writes the router script for you, you can edit it after with the custom script options. IF you need to know more, please first review all tutorials and if you have further questions post it on the forum, since we want to use github for the development of JCB.

[Please review the support guidelines](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/.github/SUPPORT.md).

**Comment by ro-ot** [comment]
We need some help with this [look at issue](https://github.com/vdm-io/Joomla-Component-Builder/issues/74) the new router has not been implemented as yet. @kwaninmacau can you help with this?

**Comment by Llewellynvdm** [comment]
Hi @kwaninmacau please watch [this tutorial](https://youtu.be/hYycPLbaMos), we were already working on this issue in another issue gh-74 and since it seems we have found a way forward, I made an tutorial to explain.

Hope this helps!
