### ISSUE TITLE
Snippet Not Saving in View

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#226]
### Steps to reproduce the issue
Edit, or create a view. Select a snippet, then save.

The same can be done with templates and layouts.

### Expected result
The snipped should be saved to the snippet field in the table.

### Actual result
Snippet doesn't save to the snippet field in the table. It reverts back to the default when opening or creating a view, and the field is empty.

### System information (as much as possible)
- OS Name & Version: CentOS 6.9
- MySql Version: MySQL 5.6
- Apache Version: 2.4.25
- PHP Version: 5.6.33
- Joomla Version: 3.8.2
- JCB Version: 2.6.13
- Browser: Chrome

**Comment by Llewellynvdm** [comment]
This is the expected behaviour since we are using many snippets that field is just like a preview and should not store the value. This also since we do not want the snippets to be exported with JCB packages but would instead want to insure that the snippets get installed via the getsnippets area.

So we do not want the snippets to be saved, it should be copied and placed in the `Default View` field and is anyway not used by the compiler.

What is the reason you want to have the snippets saved?
