### ISSUE TITLE
Not Echo JFactory in getOptions

### ISSUE THREAD

**Issue by ebrahimiali9005** [vdm-io/Joomla-Component-Builder#227]
hello.
when create custom field
not write Jfactory in "public function getOptions()"
```
	/**
	 * Method to get a list of options for a list input.
	 *
	 * @return	array		An array of JHtml options.
	 */
	public function getOptions()
	{
		$db =  ::getDBO();
		$query = $db->getQuery(true);
```

**Comment by ebrahimiali9005** [comment]
/**
	 * Method to get a list of options for a list input.
	 *
	 * @return	array		An array of JHtml options.
	 */
	public function getOptions()
	{
		$db =  ::getDBO();
		$query = $db->getQuery(true);

**Comment by ebrahimiali9005** [comment]
Hello
Good time
When you create a custom field
And connect it to another table
In the getOptions function in the file
components \ com_library \ models \ fields \ libraries.php
Is written
$ db = :: getDBO ();

Which should write
$ db = JFactory :: getDBO ();

**Comment by Llewellynvdm** [comment]
This is an error you made, not JCB.... let me show you:
[![Human Error](https://img.youtube.com/vi/OMnRlwNI7xc/0.jpg)](https://www.youtube.com/watch?v=OMnRlwNI7xc)
So that means you must have removed it, just putt the string back.

# Yet you did not give use all the info we need
> When you open an issue on Github, there are fields you need to submit

### Steps to reproduce the issue


### Expected result


### Actual result


### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser: 

### Additional comments

> Please provide us the details we need, since it makes it so much easer to debug.

**Comment by ebrahimiali9005** [comment]
Thanks.
