### ISSUE TITLE
Adding SSH

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#230]
I have been working on a feature to add ssh to JCB so we can not only FTP files from the developing environment to other locations, but also via SSH move our zipped files around.

So FTP is now being changed to SERVER, and we are adding a protocol type to the view with ssh as a new option.

IF any of you have knowledge on the subject, then please join me on the implementation of this new feature.

**Comment by Llewellynvdm** [comment]
I am planning to make use of the [phpseclib](https://github.com/phpseclib/phpseclib) to achieve the most secure, easy way to do this.

If any of you have a better idea please speak up. Reality is making composer part of JCB would add new and great possibilities.

**Comment by ro-ot** [comment]
I think that phpseclib is the best choice, since it is a pure PHP library.

I would think that you should not include the Composer json and lock file, as this is a limitation for those of use who may want to add other libraries. During update/upgrade of JCB you will mess with our install, by over writing our json and lock file.

**Comment by Llewellynvdm** [comment]
I was wonder over this, I will take it out. But you will have to have the phpseclib as part of your initializer file.

I am working on the implementation of the ssh into JCB as we speak.
