### ISSUE TITLE
Getcustom Dynamic Get's Custom PHP Scripts not deployed

### ISSUE THREAD

**Issue by MiAlmeida** [vdm-io/Joomla-Component-Builder#239]
### Steps to reproduce the issue
New Dynamic Get on a Back-end View with "Add PHP (before getting the Item)" , like so:
![image](https://user-images.githubusercontent.com/37026740/36938659-ae1b2b54-1f1c-11e8-9ce7-ad7106d87f7b.png)

### Expected result
The public function getMyTeamName should have the PHP code before getting the Item.

### Actual result
No code is inserted. Tried with the "after getting the Items" with the same result.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7.19
- Apache Version: 2.4.27
- PHP Version: 7.1.19
- Joomla Version: 3.8.5
- JCB Version: 2.6.17
- Browser: Firefox 58

### Additional comments
I have another Dynamic Get of getType = getListQuery with PHP coded added and running succesfully before getting the items so I suspect it's related to this being a Getcustom dynamic get.

**Comment by Llewellynvdm** [comment]
Yes we should hide those fields since you are right the custom script does get dropped at this time when it is a custom get. 

I can point you to where in the compiler this is happening, but you will see that it gets little crazy to juggle all those values. So it is a todo to look at it again and try to achieve a greater scalability.

So in the compiler we have to look at a few places.
- Where all dynamicGet objects begin and are set ([line 2107 - a_Get.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L2107))
- Then in the intermediation file ([e_Interpretation.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php)) do a search for `function setCustomView` you will find atleast 25 methods working in polymorphic cohesive madness.
- Then the area where the php "custom scripting is added" can be found in the ([f_Infusion.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/f_Infusion.php)) file by doing a search for `main_get->gettype`

I don't have time to really look at this now, but if you want to spend some time, go right head and send me your suggestions. But hey at some point this must be done, and I can tell you hours have already been spend to prepare the way... :+1:

**Comment by Llewellynvdm** [comment]
To me it seems like we need to give customGets their own fields, which we move into another class value and so be able to accurately detect placement.

A quick review shows that all custom scripting will endup in the main get areas. 

So @MiAlmeida do a search across your complete model for the custom script as I suspect it does get added but not in the place you expect.

**Comment by Llewellynvdm** [comment]
@MiAlmeida are you willing to run tests if I try and fix this? I mean I have not heard anything back from you on the above posts.

**Comment by MiAlmeida** [comment]
Sorry for the late reply. Health issue.

I searched across my complete model and the custom script isn't added anywhere. I've been adding it manually after compiling and deploying. I've been placing it where I think "After getting the items" would mean. I started this issue wanting it before getting the items but ended up with "after getting the items". 

I had a look at the compiler files you mentioned but lack of php experience and the flu did me in... :(

Of course I'm willing to run tests.

**Comment by Llewellynvdm** [comment]
No problem, I will give this a look, add the fields I suggested and make the changes to the compiler. Then I will link this issue to the push I make to the staging branch. At that point I will let know to run some test.

**Comment by Llewellynvdm** [comment]
Okay please run some tests, I have made the needed changes to insure that the script gets added in the correct place as expected. Please use the latest version pushed to the staging branch, and let me know if it now behaves as you would expect.

**Comment by MiAlmeida** [comment]
Did some testing and the custom scripts I set for before, as well as after, getting the item do indeed get added in the custom method.

I only have one suggestion for the location of the "after getting the item" script:
![image](https://user-images.githubusercontent.com/37026740/37257163-3e57acc4-255d-11e8-962a-75451fcc2fca.png)
as you can see it comes after checking for an empty dataset.
So the script is prevented from checking for an empty dataset and acting accordingly. Possibly returning some default/dummy dataset.
Could I suggest the placement to be immediately after the $data = $db->loadObject(); ?

Anyway. Great job. Let's get a coffee. :)

**Comment by Llewellynvdm** [comment]
Yes I think we can move that, and it does make sense.
