### ISSUE TITLE
Custom Admin Views - Menus Not Appearing

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#24]
Hi Llewellyn, hope this finds you well!

Any simple reasons why a custom admin menu & dashboard items are not appearing? The views have been created. Where can I find the dynamicGet code to check there are no errors in it? Wondering perhaps if this is the reason they are not appearing.

Thank you!
Paola

**Comment by Llewellynvdm** [comment]
Well first please insure that you have fully watched the tutorial ([custom admin view](https://www.youtube.com/watch?v=gtdQ1lwB9ds&index=17&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE)) on this topic :+1: 

There are many reasons why this can happen, since there are many aspects that needs to be setup correctly, therefore I will need to see the code in various folders and files to actually be able to debug. But it could be a setting in the ComponentBuilder UI... this I can help with only via Skype.

The dynamicGet code will be added to the model class of the custom admin view, this is all found in the relevant folders as per Joomla conventions.
