### ISSUE TITLE
Versioning not working ?

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#241]
### Steps to reproduce the issue
When I compile a component I expect the version to be stepped to the next version

### Expected result
I expected the version to be stepped to the next version

### Actual result
Sometimes it steps and sometimes it doesn't.  Haven't seen a repeatable way of getting the problem.
I think it's when I have updated a field.  So for example I had a field for a persons name and the db column value was mytextfield.  I only noticed this after the compile and load of the component.   So I changed it: fields->field and changed the code to adjust the name:
<field 
	type="text" 
	name="mytextfield" 

changed to

<field 
	type="text" 
	name="person_name" 

What I noticed was that the database column name didn't change after the recompile.  So I wonder if it's not picking up some field changes and so doesn't see a change in the code so it doesn't update the version number.

I've now taken to uninstalling the component, updating the version manually, compiling and then reinstalling and that seems to work every time.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7
- Apache Version: 
- PHP Version: 7.0.28
- Joomla Version: 3.8.5
- JCB Version: 2.6.17
- Browser: CHrome

### Additional comments
Software seems great - haven't tried it extensively but this little bug is worth living for because of the time saved.

**Comment by Llewellynvdm** [comment]
The versioning only steps up if you made changes to the database (add a new field, and a new view), and it need to tell Joomla that there is a DB update file being generated. So it does not step-up every compilation, since those of use who have already created huge components with JCB know that you tend to compile so much that it will become crazy if every time it versions up.

This is not a bug, but a feature... :+1:

**Comment by alan123489** [comment]
Thanks - why did it not pick up on the column change?

**Comment by Llewellynvdm** [comment]
Well, it is because that part of the feature is not fully developed yet. Here is the notes in the compiler on [line 5713](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L5713) it says... // hmmm tough one

I knew that we need to catch that change and make the update, but it is not done yet. How good is your PHP, want to give it a go?

**Comment by Llewellynvdm** [comment]
The reason why it is tough is we have to check every field if it changed and that is a very huge number if we are compiling a huge component, not sure if our memory will hold-up. You see the tables are already being done, here on [line 982](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L982) the build begin. So we will need to add that to each field as well, and this is a huge amount of new calls. I am not sure if that is a good idea.

Do you know enough to give some advice? I can try to add it in... but we already have huge amount of movement in the compiler.

The next challenge is that the actual field name or as you called it column name is build dynamically, meaning that if we see there is two of the same field names in a table/view we increment them so to insure no conflict and that they both still get added. So the original name in the history of the field is not always the same as the name used to actually add the field. Yes this is not common practice to add one field twice, but it does happen. Then the field name also changes if it is a tag field, you can see some of this happening in the compiler on line 444.

So we end-up having to build the fields twice, once from the history of the fields and then the actual build. This make is even more crazy... then only can we be sure of the field name change.

So it is a **tough one** and I have not yet come-up with an easier approche, unless I add a new table that just tracks field names per component per view and not depend on the Joomla default history implementation as we now do.

**Comment by Llewellynvdm** [comment]
oops wrong button..

**Comment by alan123489** [comment]
Hi
I don't know enough about the compiler so please forgive any mad comments!

In terms of scoping:

If a table had on average 20 columns (i.e 20 fields) and there were up to 100 tables then that's only 2000 columns/fields to check.  Most of these are standard Joomla fields like id or created_by  etc.

So I think in terms of processing power analysing them for changes doesn't seem likely to be a big overhead.

My guess therefore is the issue comes in two possible places:
1. Gathering in all the fields and checking them against history  if this is done dynamically I can see there being a major processing overhead.
2. Amending the database which is full of data.  Assuming it's big then the overhead might be substantial.

I would have thought that on compile running code that looked for changes to fields (might not just be limited to fields) first might help.  It could build the database schema and determine what (if any) changes were needed.  

So rather than looking dynamically for changes as the compile progresses it would split the process into look for changes and then do the processing.  I don't have enough knowledge to know how it all fits but I would have thought that something like
create database schema from fields
amend any data in the database to fit with the new schema
create the controllers, models and views
finally create the main cotroller, the xml etc

The first two bits look like the biggest time sumps (or rather the second one - database - on any sizable component.

Sorry if this isn't any help.

**Comment by Llewellynvdm** [comment]
Hey I appreciate the feedback, keep it coming.

I should at some point get some tutorials out of exactly how JCB's compiler works. But I can tell you it is doing it in a way that is truly scalable and stable. So we are not going to change the overall process at this point. Believe me that is many months of work and tones of issues.

I have started to refactor some of the code surrounding this issue, and I am looking at a possible way to get this to work. I mean hey this feature must get added some way or another, since it seems logic and what will be expected.

Just a heads-up JCB itself has 1651 fields, which I would also consider as many. The amount goes up when you use repeatable/subform fields. So you do not need that many views just many subforms.

Okay so you are saying sort of what I am saying... I mean the compiler is broken up in pieces that execute one after the other.

- First we get all the data from the DB ([a_Get.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php))
- Then we build all the files and folders ([b_Structure.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/b_Structure.php))
- Then we build all the fields ([c_Fields.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php))
- Then we build all the dynamic scripts for the files ([e_Interpretation.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php))
- Then we line-up the dynamic data with its locations ([f_Infusion.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/f_Infusion.php))
- Then we update the files with the actual data ([compiler.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler.php))
- Then we do some final stuff (very complex) ([compiler.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler.php))
- Then we package and move the component into place. ([compiler.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler.php))

So at this point the history check happens in the [a_Get.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php) of the compiler. But the field names are only detected in the [c_Fields.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php) of the compiler. Which is little late in the process, so I first started to create a function to get the fieldName in a constant way. Then I am planning to move that function out of the [c_Fields.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php) file into the [a_Get.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php) to sooner get the name and run a validation against the field history.

**Comment by Llewellynvdm** [comment]
@alan123489 I have great news... I have managed to resolve this, and it really works well, no huge extra load and yet able to detect the name change, even the datatype and length. Well please test and let me know!

**Comment by Llewellynvdm** [comment]
Make sure to use the latest push to the staging branch, and do not test on your production system :+1:

**Comment by alan123489** [comment]
Great I'll have a look  I've been having a more thorough test today and there was definitely an issue. But hopefully it'll be gone now:)  I'll get the staging build and have a look.

**Comment by alan123489** [comment]
Hi  so I installed the staging (only the admin side.  I'm getting a problem which I don't know if it's related to updating.  when I add a new field to an admin view:
<field 
	type="text" 
	name="Initial_website_cost" 
	label="Initial website cost" 
	size="10" 
	maxlength="50" 
	default="" 
	description="Initial website cost" 
	class="text_area" 
	readonly="false" 
	disabled="false" 
	required="false" 
	filter="FLOAT" 
	validate="" 
	field="" 
	message="Error! Initial website cost" 
	hint="Initial website cost" 
	autocomplete="" 
	showon="" 
	onchange="" 
/>

it throws an error in that views detail page - a.name not in column list

I have another field  which is exactly the same:

<field 
	type="text" 
	name="monthly_value" 
	label="Monthly amount £" 
	size="10" 
	maxlength="50" 
	default="Some text" 
	description="Please enter the monthly amount" 
	class="text_area" 
	readonly="false" 
	disabled="false" 
	required="false" 
	filter="FLOAT" 
	validate="" 
	field="" 
	message="Error! Please enter the monthly amount" 
	hint="Please enter the monthly amount" 
	autocomplete="on" 
	showon="" 
	onchange="" 
/>

same view but it doesn't throw any error.  

For completeness sake it actually did cause an problem but I fixed that directly in the database.  It set the field as decimal(10,0) and it needed to be decimal(10,2) -perhaps there was an option to set this that I missed? So whilst this might be an issue I don't think it's causing the a.name error.

I don't have name field in this admin view but I don't understand why one field would work but the other - which looks the same will throw an error.
(might be worth noting that without an name field the alias field just uses the date - I guess you know that :) -  but I can't imagine that that will give a database column issue)

When I check the database for the organisations table there is no name column but instead a name_one and a name_two - perhaps some convention you are using?

Anyway it's late here so any thoughts about where I might look?

**Comment by Llewellynvdm** [comment]
Well here is the deal, when you use the same field twice in the same view it will convert them to name_one and name_two. Since there can not in the database be two fields with the same name.

This is also the one issue that versioning can not effectively manage since the actual name used is never stored in the JCB database at all, but calculated on compilation when a duplicate field is detected.

So there is these four events that the version will increment, and the new update DB sql generated:
- When a new view is added
- When a view name is changed
- When a new field is added (not with multiple used field in one view, will only get a little notice in blue)
- When a field name is changed  (not with multiple used field in one view, will only get a little notice in blue)
- When a field datatype is changed (not with multiple used field in one view, will only get a little notice in blue)
- When a field datatype length is changed (not with multiple used field in one view, will only get a little notice in blue)

So please only test these cases, as that is all this feature can address. When you ad the same field a second time to the same view it will not create a database update and it will not increment the version, it will only give you a little notice in blue. Since we have no way to really validate that you really changed something. So if we did add the db update script and it was not a change, your clients will get an error on install since the fields already exist. So the little blue notice is our only way to give you a heads-up in those cases, you can then manually add sql script to the component if needed.

**Comment by Llewellynvdm** [comment]
## Just for little more perspective.

When you use the same field multiple times in one admin-view then JCB builds the install sql for that component to add those fields to the DB and all will work with no issues. So for fresh installs there is not issue, only if you do this latter (which will hardly ever happen, unless by accident)

So I thought well, lets drop that one edge case since the effort it will take to catch that and fix it is even more crazy then all that it already is being done.

Do you think that was a mistake, should we also resolve that issue?

I mean in reality one should not use the same field twice in the same view, anyway not with the same name, that is sql 101. So if someone really want to use the same field more then once they can open the field, change just the name (so they know what the target name will be on the front-end) and save as copy, then do it again and again... then go and link those fields to the view, and with that approach the database script gets build since it detects that the fields are new, and the version gets incremented. Then most importantly the developer knows what the field names are, since just like you, most when looking at the database seeing name_one and name_two will wonder where does that come from, unless they know that JCB did it to protect against naming conflicts in the DB.

The incremental option was mainly added for spacers so you can add the same spacer over and over and it never becomes and issue.

There was a suggestion to not increment the first instance of the name, so it will be:
- name
- name_one
- name_two
If you added the field three times, but the reason we did not go that direction is basically due to the iteration limitation. See when you have three fields like that, you may want to run a loop on them, like this:
```
for ($k = 1 ; $k <= 3; $k++){ echo $item->{'name_'.[[[Component]]]Helper::safeString($k)}; }
```
The helper class has this `[[[Component]]]Helper::safeString()` method that converts all numbers to words. So it is very easy to loop the incremented fields, but if the first was just `name` it will not work.

Well hope that helps to the why the incremental fields behave the way they do.

## Why can't we detect multiple fields like other fields

Well since it is essentially the same field, and since we are using the history component of Joomla to track the changes. When you add the field a second time, JCB looks at the field and sees it is already noted as being part of this component, and so does not flag it as new, but then it detects that the field is part of the what we call **multi field group** since it is added multiple times, therfore it ignores the name change since it has no idea how many time it was added on previous compilations, so how can it know that it has become more, or that any change was made at all. Therefore ignores it, since fields that are part of the **multi field group** can not at this time be tracked in the same way as the rest of the fields.

## Can multi fields be tracked

Yes we can actually tract them, but that will have to happen outside of the current method of convention. Which means four to eight hours, time I do not have at the moment...

**Comment by alan123489** [comment]
Thank you for the response I understand it better now.  

Actually I didn't have multiple fields with the same name.  What I had done was

1.create the field and then compile and install
2.remove the field (from the admin view) compile and install
3.create the field and then compile and install

What I discovered was that sometimes column names are left in the database and so I'm guessing that when the time comes to add the new field (step 3) the compile thinks that there is already a field with that name and so creates the one and two thing.  Perhaps I was just getting confused I haven't spent significant time reproducing this issue

I wonder if it would actually be better to throw a compile error and state that you can't have two fields with the same name in the same view - as you said that's sql 101?  So in short I think you are correct about the edge case, I would go further and simply throw an error because it is bad practise.

Two other things I've discovered as I've tested:

unless you have a name field the alias creates from the date/time.  I think it would be good to be able to specify which field the alias creates from.  I say this because I think it's helpful to try to name fields in a descriptive manner - organisation_name, product_name, person_name etc.  For me this makes code simpler to read especially when switching between views

it would help if it was possible to specify the number of decimal points.  Currently the only way I've found to get them is to manually edit the database.  Which is fine but not ideal since it needs to be remembered for every new update.

Hopefully my comments are helpful - your software is excellent and I appreciate how tough it is to write such code.

**Comment by Llewellynvdm** [comment]
When you remove a field and again add the same field the system will not detect a change was made, it must really be a new field.

About the duplicate fields, well I use that option of adding multiple of the same fields, since it safes me time, and I can see why others will do the same, and it works. It just does not work with auto-sql-update and version incrementing. So in other regards it works, and that was not easy to achieve. So I will just like to leave it as it is, we could change the little blue notice to a warning that is more noticeable. But I want the feature to still work, and not to jump out with a huge error.

About the alias, I have no idea what you are talking about. The system does not dynamic set an alias as far as I know. You have to check the field as an alias when you add it to the admin view.

Ahaa now I understand... hmmm I never thought one would have an alias without setting the name/title field. Yet the date-time behaviour is a default Joomla behaviour when it can't find a name/title field. So naturally the fix is to add a name/title field, or not to have an alias field.

**Comment by Llewellynvdm** [comment]
You add a name/title field, not by making the name value name, but when you link the field to the Admin-view you check it as the name/title field like so:
![image](https://user-images.githubusercontent.com/5607939/37372590-e5640f7a-271b-11e8-83b1-b671ee9f7a70.png)

**Comment by ro-ot** [comment]
@Llewellynvdm we should deal with this edge case, it will be the cause of many confusion. I read all your explanation, and I agree it will be hard to manage. You said

>Yes we can actually tract them, but that will have to happen outside of the current method of convention. 

I can help with that, I may have some opening soon.

My only request for now would be to insure that the notice becomes a warning, so that developers will know what is happening, and not overlook it since the blue notice is there all the time.

**Comment by alan123489** [comment]
That would be great.

I came across something else this morning too.  If you name the component Name in Code the same as one of the admin views then the admin view won't display.  It took me a while to track this down but when I think about it it's obvious.

Don't know if you need to do anything but I suspect it's one of these things that would be easy to flag up.
