### ISSUE TITLE
Feature Request - Setting Admin Views (and Site Views and Fields etc) header to stay visible

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#276]
This is just a very low-level UI request.

For all the areas where there are subforms being displayed (Selecting Site Views, Admin Views, Fields, etc.) that have the column headers at the top of the subform, to make those column headers somehow remain visible even after you add lots of subform entries.

It is a bit cumbersome when you can't remember what the checkbox in column 3 is used for and have to scroll all the way up to the top - esp. when you have a couple dozen entries.

![editing the component admin views- 2018-05-03-18-59-56](https://user-images.githubusercontent.com/1929923/39608049-67357b5a-4f04-11e8-8df9-1bbc77e805c4.png)

NOTE: It would be helpful if you could 'document' how you end up doing this because I know that I'm going to also need that functionality for components in the not-too-distant future.

**Comment by Llewellynvdm** [comment]
I sure we could add this with some custom scripting using UIKIT or Bootstrap. But really that is a Joomla issue. This feature should be asked at Joomla, since all we can do is hack the code, and this is not ideal. If you really want this feature to work well and be stable you should ask those at Joomla who build the subfrom to add it.

Okay the hack... so look at the code you will see it is a table and that area is the `thead`of the table.

So you need to first add some id via javascript to that `thead` area and then target it with [this UIKIT 2 sticky library](https://getuikit.com/v2/docs/sticky.html).

You will in the back-end need to load the library manually (admin view->php tab->Add PHP (custom document script)->yes) to the page like this:
```
// add the Uikit v2 style sheets
$this->document->addStyleSheet( JURI::root(true) .'/media/com_componentbuilder/uikit-v2/css/uikit.gradient.min.css' , (ComponentbuilderHelper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
$this->document->addStyleSheet( JURI::root(true) .'/media/com_componentbuilder/uikit-v2/css/components/sticky.gradient.min.css' , (ComponentbuilderHelper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');

// add Uikit v2 JavaScripts
$this->document->addScript( JURI::root(true) .'/media/com_componentbuilder/uikit-v2/js/uikit.min.js' , (ComponentbuilderHelper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
$this->document->addScript( JURI::root(true) .'/media/com_componentbuilder/uikit-v2/js/components/sticky.min.js', (ComponentbuilderHelper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript', (ComponentbuilderHelper::jVersion()->isCompatible('3.8.0')) ? array('type' => 'text/javascript', 'async' => 'async') : true);
```
Then with the library... you can do something like this:
```
var sticky = UIkit.sticky(element, { /* options */ });
```
Hope this helps you get going...
