### ISSUE TITLE
Suggestion for Translation 

### ISSUE THREAD

**Issue by lamatieregrise** [vdm-io/Joomla-Component-Builder#284]
Hello, I was wondering if filters for the translation list could be something to integrate into JCB, being able to see and export all translations of specific types such has: menus, fields, title, and by translating state such has: translated, not translated, revision would be a facilitator has for the User Xprience .  I've worked in the pass with professional translators and some like to adapt the verbiage to the place it's destined for and might even be an incentive to pick JCB over other ones. I'm a noobie when it comes to coding, but I'll put back on my senior strategic communication/marketing guy hat for a moment, just to say it would be a little plus that could be beneficial for JCB.

Francois

**Comment by Llewellynvdm** [comment]
Let look at this, I am working on building a automated bridge between https://crowdin.com API and JCB, so that https://crowdin.com will be the translation home of all your projects.

https://crowdin.com/project/joomla-component-builder is to official JCB project. But the idea is to be able to pull and push translation to and from crowdin, into any JCB component/project.

So we could use the Crowdin interface to manage all these relationships. Does that sound like an answer, or would you still think extending JCB is the better option?

**Comment by lamatieregrise** [comment]
Hello Llewellynvdm 

That's a good question, to my point of view crowd sourcing was the avenue to pick, We are all aware of the efficiency on that matter and it's been demonstrated over the years especially in regard of internationalization/translation and and documentative purposes such has guides, help desk and wikis. For those reasons JCB will benefit from such modus operandi. Could it be possible to have like a pair project switch that would give the option to go to crowdsource collaborative or private onsite collaborative, I'm talking to myself it is not uncommon to have mandates requiring a greater level of scrutiny when it comes to confidentiality of their assets (text image, etc.), in most case contract giver wont mind and crowd sourcing will suffice, but there are those few exceptions with their confidentiality requirement? When in general a company has a preexisting  structured confidentiality policy/agreement.Well,  seem to be a good of a bigger budget for the project that why  being able to offer some kind of close environment remains important... reassurance on confidentiality is an excellent sale incitative for the coder's customers. I I told you I'm still a newbie (well for js & sql, and not fluent in php, heh-heh) so there  might be some reason I dot see yet, but I'm being offering both would be problematic?(Has options per project) language is taken in charge by Jamal, all language files and folder structure remain the same in both cases?

Have a nice day
Francois

PS! (most of the reviews, i've found on the net about JCB are WOW! , they are easy to find but You should seriously link to them on your website this will be excellent free advertising for JCB)

**Comment by Llewellynvdm** [comment]
Have you tried the option to export the translation string to a spreadsheet? This is the option to achieve easy translation on a local level. 

I would suggest make a few translations (in to three or four languages) of at least one or two strings in JCB and then export it with the `[export data]` option in the list view of the Language Translations. I am sure you will find all you need to do translations much **more rapidly and privately**, with all the search and filter options a spreadsheet can offer. Then you can import your spreadsheet right back into JCB with the changes and your done!

All strings are bundled onto one at this time, since if you translate the English string once it will be translated every were it is used. This seemed like the better approach at the time, as it should in the long run mean less work.

What we are going to do is add a filter to be able to select only the strings of one project, and be able to export only those fields. But to zoom down into just labels and or titles will not be possible without a complete change to how the JCB translation manager works.

I would hope being able to export the strings you can sort them in the spreadsheet and just translate the strings with targeted words or length, and so be able to achieve your goal.

Well let me know if you still have more questions on this issue, I will be closing it, but you are more then welcome to continue the discussion.

**Comment by lamatieregrise** [comment]
Hi Llewellynvdm 
Sorry for the delay on the reply, the last few days over here have been quite crazy. Though on a good note, I had opportunity to spend lots time with 3 professional translators, they all agreed on a few things. 

First, they hate receiving for translation documents on a spreadsheet, but well they live with it since it's the format that kind of became the norms when it comes to translating web-related stuff, from their perspective there in most of the case information missing maximizing their efficiency 2 simple thing (well 3 but, the last one is normally not related to our end of the deal). 

What's missing in most of the case a column what is the usage of what need to be translated (is it a title, a button, a warning popup, etc.) the second column would be the importance of the text in comparison with it surrounding (which we can easily translate by: H1, H2, H3, blockquote, p, etc.) the third column would be for notes (for specific verbiage, words forbidden to use, pretty much the agency to provide them that info). 

Me, personally I would also suggest adding a column indicating the component it's because when working on many components at the same time it can get messy with this amount of info and column with associate string, to speed up the process on our side. The object of this is purely on a marketing stand point a more efficient tool for them, kind of transform them in and undercover sales team for JCB, if they prefer using your stuff for practicality they will let it know to whom it concern (event indicating somewhere translation grid generates by JCB could be a good thing).

Here is an example of what came up with that discussion.

Francois

[example.xls.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/2022722/example.xls.zip)

**Comment by Llewellynvdm** [comment]
Hi Francois

I have looked at your proposal, and it all sounds great. Well in fact it also makes sense that these kind of info be readily available. There is yet a few issues that makes it kind of hard to return this kind of result.

### No Go's..
- JCB does not keep track of the surrounding html.
- One string can be used as a header, button, link, and warning or even a paragraph at the same time.
- One string can be a label, description and a view name, even a component name at the same time.
- JCB does not keep track of any of these relationships inside the language builder.

### To Do's...
- We can add a field in the translation area for notes, but the note will have to be added manually.
- We can include the component names in the export.
- We can also add a field for forbidden words.

So in my mind the moment you separate the strings into kinds of placements you will have a huge mess in loading those strings back into the component. JCB can handle 10k of strings in one component with no really noticeable delay, because we use the Source strings as a pointers. That means one string for one string. You can only have _Afrikaans => *Name* => *Naam*_ in your array once.

So we will have to redesign the inner compilation structure surrounding the language builder, would you be willing to do that?

**Comment by lamatieregrise** [comment]
I can give it a try, I told you I'm still a noobie, so I'll need supervision. Note needs definelty to be added manually (usually by the agency and only IF they think about, Translator seems to be informed after their usually done) for instance, one of them told me he worked on a project like a point rewards program card (something similar to air miles) and they were forbidden to use the word "points" they need to refer has them has "Reward credit" (or something like that). So it basically the agency to provide them with those notes on those do's and don't's. 

I was thinking, even if it is not an imported spreadsheet, hikashop has that elegant way that comes quite handy when in need of quickly spotting the string association instead of going to check (see image) directly in the code every time, and if language content could be filtered by component (there might be a few existing components but they are not necessarily all translate by the same person or same team so a way to separate the document accordingly would be beneficial before the event being export that might be good premises to start with, and if hake are able to render language file their on screen i'm sure there is a way to transpose it onto a spreadsheet. Do you think it make sense?

Francois

![hikashop](https://user-images.githubusercontent.com/32321039/40316262-c329c534-5ceb-11e8-9e56-95a1e60882f0.jpeg)
