### ISSUE TITLE
Target other components from the front-end.

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#291]
We want to target other components from the front-end, so in JCB there is no admin view, just a site view and options to build forms that can update/create/delete other component data with all the refinement method and groups mapping for this frontend user management.

@tonypartridge will share with us some ideas, and code implementation to make this happen.

**Comment by ro-ot** [comment]
JCB and all its projects are leaving gitHub... this is going to take some time since JCB/VDM is so integrated with github,

The new address is [https://gitlab.com/jcb-repos/Joomla-Component-Builder](https://gitlab.com/jcb-repos/Joomla-Component-Builder).

**Comment by tonypartridge** [comment]
Has GitHub changed it’s policy? Is there really a need to leave GitHub just because it’s owner has changed?

**Comment by ro-ot** [comment]
I will never trust microsoft and I hope @Llewellynvdm will continue to take a stand for the open-source mandate and never let any propitiatory institution buy his loyalty.

How can we **who are apposing the ms development ideology of enslavement**, stand by and make friends with those who has oppressed us. No we will go stand on the other side of the bank and there we will wait and see if they have really changed.

Our trust is not _bought with money_ **but earned with code**!

So let the new owners open-source their operating system and we will speak again. Since it is not just a change of owners, it is a change back to the very people who refuse to share code, their source-code.

Yes they are giving money to Linux, yes they are now involved with open-source projects. That is like a wolf eating grass, it is still a wolf. They will only really be sheep if they make their code open-source, end of story! We are sick of being spied-on and manipulated.

The time has come to take a stand, so migrate, anywhere, that does not matter, just move away from github, so that there will be a clear voice that we are not happy with how ms has been doing things for the past century.

Look you are welcome to stay, please understand why we can't!

**Comment by tonypartridge** [comment]
I really do think this is way over the top. It’s like comparing Germany now to what it was when hilter was in charge.

There is a different CEO at MS so I wouldn’t jump on any ship unless you start seeing policy changes and staff leaving etc.

**Comment by ro-ot** [comment]
**That is not a good comparison my fiend!** shame on you! Germany no _longer kills Jews_, whereas ms still has not made their code open-source. You don't get it do you!

Maybe you should take time and go read the [gnu gpl](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/LICENSE.txt) again slowly.

The over reaction is doing noting! So the question is @tonypartridge how much code have you given away? Have you crossed the 1M line barrier? Do you know what it takes to do that? Once you do, you realize the only once who support you are those doing the same.

**Comment by tonypartridge** [comment]
Hello,

I’m not on about Jews. My point was simply extreme. There is no point in jumping to a judgement because of a company name. There is a different leader behind it, you shouldn’t assume the worst.

I’ve given lots of lines of code away thank you.

I won’t be contributing to JCB anymore, given your very narrow minded approach.

**Comment by Llewellynvdm** [comment]
Cool down guys, we are moving and would like to see you all continue supporting the many idea, and that is JCB not Microsoft or gitHub.

**Comment by ro-ot** [comment]
Hey I speak for myself, that much is clear. If you don't want to contribute to JCB because it is moving to gitLab then I suppose you will not be contributing to all the millions of projects who are moving. Which at this point is 27k per/hour more or less.

**Comment by marcodings** [comment]
Acting on emotion in the spur of the moment has seldom served anybody.

My 2ct would be wait a bit and reflect.  Start preparing / planning for a "plan B." 
However just because others act in a certain way does not seem a sensible reason to do the same. I don't think there is need for panic. 

Judge MS by its actions today and in the time to come regarding github and not by what it did in the past. Imho they showed a change in attitude and actions over recent history.
If MS shows to be moving in the wrong direction we can deploy a "plab B", until that time we can can better spend our time writing code for the community.

Some technical remarks:
Moving the repo is easy but the challenges only begin there ( i know as i moved jira projects to gitlab ). The the challenges is not with the repo itself, its with the issues, pr's etc. How to preserve history, assigned users context, etc.
FWIW atm you need a selfhosted solution to even begin attempting that as the hosted solution does not support "changing" assigned users etc. At least not at this moment.

Waiting might be even beneficial as gitlab is sure to come with "improved" migration tools. Time we do not need to spend.

**Comment by marcodings** [comment]
I personally could care less about the underlying system, i have used my own gitlab instance for years. I guess its fair to say people would contribute either way. I just think we should cool down and wait. See my other post

**Comment by marcodings** [comment]
@ro-ot https://gitlab.com/jcb-repos/Joomla-Component-Builder will not work if you want to preserve info on users etc, you require your own hosted setup ( i know i tried ! )

**Comment by tonypartridge** [comment]
Couldn’t agree more Marco

**Comment by ro-ot** [comment]
Well forgive me for having an option @mwweb, just again it is my opinion. My apology if it came across to strong. I just really have a difficult time to work with ms, that is simply all.

@Llewellynvdm please, do whatever you think is right. I will continue to support your work :+1:

**Comment by Tony301** [comment]
If I can give my 2 cents, we are here because we support JCB. At the end of the day emotions can not contribute to our JCB support. GitHub or GitLab, it does not matter as we support JCB and the path the creator of this amazing product is steering.

**Comment by gousety** [comment]
Just interesting note here.
```
nslookup gitlab.com
```
gives you
```
Non-authoritative answer:
Name:	gitlab.com
Address: 52.167.219.168
```
Then 
```
tracepath 52.167.219.168
```
and you get **ae121-0.icr03.bn6.ntwk.msn.net**

Welcome to Microsoft (Azure)

**Comment by Llewellynvdm** [comment]
We now find ourselves in a post open-source revolution era so I will start by making two statements.

1. I don't like Microsoft, even if they changed I am not convinced that they have changed to what Linux was.
2. Linux has also changed and is no longer what it was.

Having said that JCB is a Joomla component that runs on both Microsoft and Linux, where Linux still controls the majority of the market share. So it does not really matter how and where JCB is hosted and maintained.

We are all open-source enthusiast who love the open-source approach to software development. Microsoft has chosen to stepped into the spotlight, and will be closely observed in every step they take and how that effects open-source. If we at anytime see and agree that their actions in anyway will hurt or frustrate JCB's objectives we will and must take action even to our own hurt, for the sake of the cause of the open-source mandate.

I really like gitHub, JCB and many of my other products are fully integrate with gitHub. To move away is not a two hour or even two day exercise, but will take weeks, even months to fully implement not to mention all the data loss explained by @marcodings.

So if we could stay on gitHub, and still stay true to our community mindset of sharing code, with the true objective of empowering others to achieve what we can never achieve alone then I would be very happy indeed. It will save me tons of hours and money.

So as the founder and lead developer, I would ask that we stay on github until we have clear indication, due to changes in or around github, that the project is in danger or will suffer, and so also our common objective explained in the [license agreement](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/LICENSE.txt) of JCB.

I will however support the idea of having mirrors of this project on gitlab, or any other git platform that offers open-source hosting for free.

Thank you for your attention.
