### ISSUE TITLE
Heads-UP!!! JCB is moving to gitLab

### ISSUE THREAD

**Issue by ro-ot** [vdm-io/Joomla-Component-Builder#297]
JCB and all its projects are leaving gitHub... this is going to take some time since JCB/VDM is so integrated with github,

The new address is [https://gitlab.com/jcb-repos/Joomla-Component-Builder](https://gitlab.com/jcb-repos/Joomla-Component-Builder).

**Comment by Llewellynvdm** [comment]
Well lets give this some time...

**Comment by Llewellynvdm** [comment]
We now find ourselves in a post open-source revolution era so I will start by making two statements.

1. I don't like Microsoft, even if they changed I am not convinced that they have changed to what Linux was.
2. Linux has also changed and is no longer what it was.

Having said that JCB is a Joomla component that runs on both Microsoft and Linux, where Linux still controls the majority of the market share. So it does not really matter how and where JCB is hosted and maintained.

We are all open-source enthusiast who love the open-source approach to software development. Microsoft has chosen to stepped into the spotlight, and will be closely observed in every step they take and how that effects open-source. If we at anytime see and agree that their actions in anyway will hurt or frustrate JCB's objectives we will and must take action even to our own hurt, for the sake of the cause of the open-source mandate.

I really like gitHub, JCB and many of my other products are fully integrate with gitHub. To move away is not a two hour or even two day exercise, but will take weeks, even months to fully implement not to mention all the data loss explained by @marcodings.

So if we could stay on gitHub, and still stay true to our community mindset of sharing code, with the true objective of empowering others to achieve what we can never achieve alone then I would be very happy indeed. It will save me tons of hours and money.

So as the founder and lead developer, I would ask that we stay on github until we have clear indication, due to changes in or around github, that the project is in danger or will suffer, and so also our common objective explained in the [license agreement](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/LICENSE.txt) of JCB.

I will however support the idea of having mirrors of this project on gitlab, or any other git platform that offers open-source hosting for free.

Thank you for your attention.
