### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#302]
### Steps to reproduce the issue
Create the file upload as per the tutorial:
https://www.youtube.com/watch?v=o482sK4DxkM&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=56

Make the file upload field required (required - true).

### Expected result

To mark the area as red and prevent the submission of the form and it does.

### Actual result

When upload is complete all of the data (form fields are filled except the file field) is in the form but also it says there was no file and i need to input one. If i remove the required - true setting on the field, compile and test it  - it works fine. It is just i need to make sure that field is not empty.

### System information (as much as possible)
- OS Name & Version: Centos 7.4
- MySql Version: MariaDB 10
- Apache Version: Nginx 1.12
- PHP Version: 7.3
- Joomla Version: 3.8.8
- JCB Version: 2.8.0
- Browser: Chrome

**Comment by ro-ot** [comment]
You may need to add some JavaScript (custom) to the view, since Joomla does not by default have that. JCB is not the one doing the work after the component is compiled and in use, it is really Joomla. Since JCB is using Joomla to build the fields and validate and store. All Joomla, so if you need more then what Joomla does out of the box, then you need to write a little snipped of JavaScript to check that there is a file selected before it submits, very much like this [code used in the import of JCB packages](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/import_joomla_components/tmpl/default.php#L51).
