### ISSUE TITLE
re: Issue #303

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#304]
Since this issue was so quickly and rapidly closed, here is a NEW issue to address the issue that was closed. Note: My personal opinion is that if an issue isn't resolved, but closed, it kind of present the impression that is doesn't matter, which I feel is very poor for the reputation of JCB.

What's not getting added is lines 242-260 from that sample model in Sermon Distributor.
```				// set values to display correctly.
				if (SermondistributorHelper::checkArray($items))
				{
					// get user object.
					$user = JFactory::getUser();
					foreach ($items as $nr => &$item)
					{
						$access = ($user->authorise('preacher.access', 'com_sermondistributor.preacher.' . (int) $item->id) && $user->authorise('preacher.access', 'com_sermondistributor'));
						if (!$access)
						{
							unset($items[$nr]);
							continue;
						}
						// unset the values we don't want exported.
						unset($item->asset_id);
						unset($item->checked_out);
						unset($item->checked_out_time);
					}`
```

I'll further point out that I created a blank site, installed JCB 2.7.10, and the export works as intended. upgrade to JCB 2.8.0 and it failed. Reinstall JCB 2.7.10, overwriting 2.8.0, and it gets compiled correctly.

**Comment by mwweb** [comment]
Here, again, is the prior, original, issue:

Steps to reproduce the issue
It's an odd behavior, but if I go to a component admin list view for one of my components, select records, then click Export Data, the data exports, but without the header row. But, another admin list view works perfectly fine doing the exact same thing.

Expected result
Export data complete with header row.

Actual result
Data is exported without header.

System information (as much as possible)
OS Name & Version: 4.04.1-Ubuntu
MySql Version: 5.5.5-10.1.28-MariaDB-1~trusty
Apache Version: 2.4.29
PHP Version: 7.1.11-1+ubuntu 14.04.1+deb.sury.org+1
Joomla Version: 3.8.8
JCB Version: 2.8.0
Browser: Chrome/Firefox/MS Edge
Additional comments

**Comment by ro-ot** [comment]
Please report your continued finding on the original issue. I closed it since you sound like you were no longer pursuing the issue, your words:

> When i eventually have time to dedicate to debugging JCB inserted code, then i will. Until then, this is an unreliable/unstable feature.

**Comment by ro-ot** [comment]
I did no find the feature unreliable/unstable as you said, but that it still works well as expected. So if you are not going to debug it, then who is?

**Comment by ro-ot** [comment]
The what is this?

> My personal opinion is that if an issue isn't resolved, but closed, it kind of present the impression that is doesn't matter, which I feel is very poor for the reputation of JCB.

The issue was resolved, since the developers who maintain the JCB code did not get the same result as you did, this means the issue seems unique to you, and if you are not going to debug it, and give us feedback. Then nothing can be done, until some one else also discovers the issue and is willing to debug it.

That why the issue forum rules state:
> Then if you run into any issues, related to the JCB code, like bugs, **start by searching** the (***open & closed***) [issues][Issue] over on Github, and if the issue has not been mentioned before, **then only** open a new issue, following the [community guidelines][guidelines].

Because the owner of JCB made that call, that we will close issues if it is not actively being looked at. If you don't agree with the approach you are welcome to communicate that with @Llewellynvdm directly, or you can open a topic on the JCB forum.

[Issue]: https://github.com/vdm-io/Joomla-Component-Builder/issues
[guidelines]: https://github.com/vdm-io/Joomla-Component-Builder/blob/master/.github/CONTRIBUTING.md
