### ISSUE TITLE
JInstaller: :Install: Error SQL You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by canfine** [vdm-io/Joomla-Component-Builder#309]
### Steps to reproduce the issue
![1](https://user-images.githubusercontent.com/5087049/42090915-fe5d6d02-7bab-11e8-911a-d5ff697b6191.PNG)

Joomla version, 3.8.10. 
JCB Version: 2.8.0  
### Additional comments
I even deleted admin view " task" from the component but this error message still happens

**Comment by Llewellynvdm** [comment]
Hi, this may happen from time to time during development when the incremental steps of JCB conflicts with your own actions.

But not to worry you can fix this, you will see that in the component files on the website there is a sql folder in the admin area, and in it there is another folder for updates, just remove this folder and all should be well again.

![image](https://user-images.githubusercontent.com/5607939/42093402-1f12f970-7ba4-11e8-8a4c-9c54f7ca0a7c.png)

What happens is Joomla moves the files to the component location in Joomla, then it only does the database update, and since the old update file is still in that folder it gets to run again.

**Comment by canfine** [comment]
why is the query built incorrectly? How to make a field look like " created"?
![3](https://user-images.githubusercontent.com/5087049/42102250-05c87380-7bce-11e8-8362-c0dce53cccf6.PNG)
![4](https://user-images.githubusercontent.com/5087049/42102251-05fd8188-7bce-11e8-83d6-f667dd8b83e8.PNG)
![5](https://user-images.githubusercontent.com/5087049/42102252-062d3a40-7bce-11e8-8ef0-d6102fe04700.PNG)

**Comment by Llewellynvdm** [comment]
![image](https://user-images.githubusercontent.com/5607939/42115489-f7312318-7bea-11e8-8736-2f303bb8be1a.png)
![image](https://user-images.githubusercontent.com/5607939/42115519-1826b6dc-7beb-11e8-996b-08fc546706ca.png)

**Comment by canfine** [comment]
thanks, Another question: how to save data? clicking "save" button just clearing field's form. 
![6](https://user-images.githubusercontent.com/5087049/42123381-f316e62c-7c59-11e8-86a1-492de12dc2bc.PNG)
![7](https://user-images.githubusercontent.com/5087049/42123382-f3473458-7c59-11e8-8c5c-0557f85e4933.PNG)
![8](https://user-images.githubusercontent.com/5087049/42123383-f36c157a-7c59-11e8-916c-d1ffc7df9b8a.PNG)

**Comment by Llewellynvdm** [comment]
The values should save correctly if the field name is the same as the column name. What I found to help if things do not line up, uninstall the component and install again.
