### ISSUE TITLE
Feature Suggestion -- custom fieldtype php option

### ISSUE THREAD

**Issue by canfine** [vdm-io/Joomla-Component-Builder#310]
### This is a feature suggestion.

It could be very usefull feature to add php field in new fieldtype form 
to create  JFormFieldMyclass like in  [instruction](https://docs.joomla.org/Creating_a_custom_form_field_type)

### It might have several options

1. class extends ( JFormField, JFormFieldList ...) // list
2. php main override  //  editor "codemirror" 
3. php getLabel  override //  editor "codemirror"
4. linked or not with a form // switch button

### Additional idea
Second option could depends from the first. For example:
if **JFormField** then 
```
public function getInput() {
		return '<select id="'.$this->id.'" name="'.$this->name.'">'.
		       '<option value="1" >New York</option>'.
		       '<option value="2" >Chicago</option>'.
		       '<option value="3" >San Francisco</option>'.
		       '</select>';
	}
```
if **JFormFieldList** then

```
public function getOptions() {
                $app = JFactory::getApplication();
                $country = $app->input->get('country'); //country is the dynamic value which is being used in the view
                $db = JFactory::getDbo();
                $query = $db->getQuery(true);
                $query->select('a.cityname')->from('`#__tablename` AS a')->where('a.country = "'.$country.'" ');
		$rows = $db->setQuery($query)->loadObjectlist();
                foreach($rows as $row){
                    $cities[] = $row->cityname;
                }
                // Merge any additional options in the XML definition.
		$options = array_merge(parent::getOptions(), $cities);
                return $options;
	}
```

**Comment by Llewellynvdm** [comment]
Have you watched the tutorials? it seems like you have not. This feature is almost as old as JCB.

Please [watch this tutorial](https://youtu.be/VpzYbifqv0M?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE).

Now I know things have changed a little since I made those early videos. But I am sure you will easy get the hang of it. Specially since the [demo data can now so easy be accessed](https://vdm.bz/how-to-get-free-vdm-package-keys).

Please take the time to go over the tutorials.
