### ISSUE TITLE
Feature request of manual change layout for linked views

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#323]
**Feature request:**
Overwriting default field of joomla is nice, but that means that a total field is showed or not showed on the admin list view not on the linked view. 

It would be nice that only for the linked view you could determine with field are showed in table or not. 

**Let's try explain more:** 
Component name: com_example
Admin view 1: customer
           has two tabs called: Global and Location

Admin view 2: location

In admin view **customer** there is a linked view with location.

Looking into the generated code, is see that the linked view file is names: _administrator/components/com_example/layouts/customer/location_fullwidth.php_. 

Manually change this file can remove or hide field. You can build your own view of it. It would be nice if this can be managed from JCB.

**Comment by Llewellynvdm** [comment]
The idea I have is to add this feature to the **Editing the Admin Fields** area under the **Admin behaviour** column. It already has three values:
- Default
- Show in List View
- None DB

So why not just add two more and change one, so that it says:
- Default
- Both List Views
- Admin List View
- Linked List View (if linked)
- None DB

This way we need to make a whole major change... but it has a few drawbacks. The position number if _Both List Views_ is selected will remain the same, and on the relational implementation in the **Admin Fields Relations** we will have a real complex issue on our hands. Not even sure how that will work... but at least we can give it a try.

Not sure if you can follow what I am proposing, but please share with me any thought you may want to add.

**Comment by Schrijvers123** [comment]
Sounds a good solution. As you describe it could be workable adn of cource I'm happy to help testing/coding (although the last I don't know enough yep how JCB is build. Still learning that part).

**Comment by Llewellynvdm** [comment]
Okay we have not added this feature yet, but we have added the option to add custom tabs to admin views in which you can via ajax build your own linked views. Check-out [this video](https://youtu.be/J7vBu743h-U)...

We may still add this feature some where in the future, but the above mentioned option is a current work around that is very powerful. I will soon update the [Member Manager](https://github.com/vdm-io/Joomla-Members-Manager) to demonstrate this feature.

**Comment by Llewellynvdm** [comment]
Okay I have now added the feature as explained previously.

So @Schrijvers123 please give it a try, you will now under the **Editing the Admin Fields** area under the **Admin behaviour** column see that we have now added the new options to target only the list view of your choice.

Let me know if you find any bugs.
