### ISSUE TITLE
JCB not loading... Returns a "Parse Error"

### ISSUE THREAD

**Issue by raysr01** [vdm-io/Joomla-Component-Builder#334]
### Steps to reproduce the issue
Just installed latest version

### Expected result
Component to load

### Actual result
Parse error: syntax error, unexpected '.', expecting ')' in ...administrator\components\com_componentbuilder\helpers\componentbuilder.php on line 2339

and the same error on line 2408

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 5.5.15
- Joomla Version: 3.8.11
- JCB Version: 2.9
- Browser: 

### Additional comments
**The following solved the problem:**
Changed line 2339 from this:
```
	public static function getFilePath($type = 'path', $target = 'filepath', $fileType = null, $key = '', $default = JPATH_SITE . '/images/', $createIfNotSet = true)
	{
```
Into this:
```
	public static function getFilePath($type = 'path', $target = 'filepath', $fileType = null, $key = '', $default = '', $createIfNotSet = true)
	{
		if($default == '')
		{
			$default = JPATH_SITE . '/images/';
		}
```
And on line 2408 from this:
```
	public static function getFolderPath($type = 'path', $target = 'folderpath', $default = JPATH_SITE . '/images/', $createIfNotSet = true)
	{
```
Into this:
```
	public static function getFolderPath($type = 'path', $target = 'folderpath', $default = '', $createIfNotSet = true)
	{
		if($default == '')
		{
			$default = JPATH_SITE . '/images/';
		}
```

**Comment by Llewellynvdm** [comment]
Okay, I will update that, but just that you know. We have moved JCB to PHP 7 and are not testing it in version PHP 5 anymore. So thanks for the headsup, and if you run in to any more issues your are welcome to let us know.

**Comment by Llewellynvdm** [comment]
I also know that this issue is able to be fixed by making some changes to your PHP settings... if I remember correctly. I think we had this issue before... let me look.....

Hmm I see there was two issues surrounding this... 
[Issue 190](https://github.com/vdm-io/Joomla-Component-Builder/issues/190)
[Issue 187](https://github.com/vdm-io/Joomla-Component-Builder/issues/187)

Also seems like @joomlaserbia  had a better solution to the issue... I think I will combine the two :+1: not sure how I missed his last reply.

Please next time help me, by searing the closed issues for past posts surrounding the same issue, and just start commenting on it again.. that way others Googleing can find the answers easier.

**Comment by raysr01** [comment]
Sure, thanks.

**Comment by Llewellynvdm** [comment]
Can you do me a quick favor... can you test this option:

```
public static function getFolderPath($type = 'path', $target = 'folderpath', ($default = JPATH_SITE . "/images/"), $createIfNotSet = true)
```
Since I see the `$default = '{JPATH_SITE}/images/'` is not working.

**Comment by Llewellynvdm** [comment]
O it should look like this instead...
```
public static function getFolderPath($type = 'path', $target = 'folderpath', $default = (JPATH_SITE . "/images/"), $createIfNotSet = true)
```

**Comment by raysr01** [comment]
None of those two work.

'{JPATH_SITE}/images/'
**Returns:** Parse error: syntax error, unexpected ''{JPATH_SITE}/images/'' (T_CONSTANT_ENCAPSED_STRING), expecting '&' or variable (T_VARIABLE) in ...

(JPATH_SITE . "/images/")
**Returns:** Parse error: syntax error, unexpected '(', expecting '&' or variable (T_VARIABLE) in ...

**Comment by raysr01** [comment]
It seems that since it is working for both me and joomlaserbia who at the time was using php 5.6 and I'm using 5.5.15, and it's not working for you being on php 7+, it's best to keep it the way you changed it last night, so it works on all php versions natively.

**Comment by raysr01** [comment]
**Update:**

I get the same error when compiling:
`Parse error: syntax error, unexpected '.', expecting ',' or ';' in ... \administrator\components\com_componentbuilder\helpers\compiler\a_Get.php on line 26`

...same error on line 33, 40 and 275

**Solution:**
**On lines 26, 33 and 40...**
Changed this:`	public $hhh = '#' . '#' . '#';

	/**
	 * The open bracket placeholder
	 * 
	 * @var     string
	 */
	public $bbb = '[' . '[' . '[';

	/**
	 * The close bracket placeholder
	 * 
	 * @var     string
	 */
	public $ddd = ']' . ']' . ']';`
Into this:`	public $hhh = '###';

	/**
	 * The open bracket placeholder
	 * 
	 * @var     string
	 */
	public $bbb = '[[[';

	/**
	 * The close bracket placeholder
	 * 
	 * @var     string
	 */
	public $ddd = ']]]';`

**On line 275...**
Changed this:`	public $langStringTargets = array(
		'Joomla' . '.JText._(',
		'JText:' . ':script(',
		'JText:' . ':_(',
		'JText:' . ':sprintf(',
		'JustTEXT:' . ':_('
	);`
Into this:`	public $langStringTargets = array(
		'Joomla.JText._(',
		'JText::script(',
		'JText::_(',
		'JText::sprintf(',
		'JustTEXT::_('
	);`

**Then same error in another file:**
`Parse error: syntax error, unexpected '.', expecting ')' in ... \administrator\components\com_componentbuilder\helpers\compiler\e_Interpretation.php on line 15678`

**On line 15678...**
Changed this:`	public function getInbetweenStrings($str, $start = '#' . '#' . '#', $end = '#' . '#' . '#')`
Into this:`	public function getInbetweenStrings($str, $start = '###', $end = '###')`

**Comment by Llewellynvdm** [comment]
Well there is a separating `'#' . '#' . '#'` string there because we are moving towards the option of parsing the compiler files when compiling JCB itself (we need that for the language strings and other mind bending future plans), and if those strings are like `###` JCB will pick them up and convert them, or try to pull data from them, which is what it already does with other files.

I would suggest you upgrade your php to the latest, or at least 5.6

We simply can't change those strings, and adding them to a method will slow JCB down as they are used extensively across the compiler.

**Comment by raysr01** [comment]
Ok, no prob. I will do the upgrade and see what happens. Thanks. And thank you for this wonderful component, it's a great project and you have done an excellent job!
