### ISSUE TITLE
Problem updating component

### ISSUE THREAD

**Issue by ebrahimiali9005** [vdm-io/Joomla-Component-Builder#343]
Hello
When I create a component on a computer and transfer it to the server, it is not well updated.
it has error.
I must remove the previous component from the server and reinstall it again
This will erase the previous information on the server.
If the field is added, it's very difficult to update the information manually.

**Comment by peterpetrov** [comment]
hello @ebrahimiali9005, this seems not to be well documented bug but rather you need to find about functionality of JCB. For these purposes please post to the following group in google:

https://groups.google.com/a/vdm.io/forum/?utm_medium=email&utm_source=footer#!forum/jcb

Again - please provide details. The only thing i get from both of your posts is that you have an issue but there is very little to the circumstances that you provide us. When posting question to the group you need to provide the error, screenshots and any relevant information about your case.

**Comment by Llewellynvdm** [comment]
JCB does indeed deal with this in a very powerful way, since it adds the update SQL to the component if you add new fields, views or even change a field database values. It even handles renaming of tables, please watch this [tutorial for more information](https://www.youtube.com/watch?v=zN2M15fzf_M&t=0s&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=53).
