### ISSUE TITLE
Issue with linked view "oops! error....." in generated layout

### ISSUE THREAD

**Issue by fred-the-coder** [vdm-io/Joomla-Component-Builder#344]
### Steps to reproduce the issue
Install both JCB package JCB_AG.zip and JCB_copro.zip
I want to link Copropriete admin view with Assemblee admin view.
Linked record are: child key = copro and parent key = id.
In order to get the list of "assemble" from a "copropriete" in "Details" tab (or in another tab if must be)
[JCB_ag.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/2404502/JCB_ag.zip)
[JCB_copro.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/2404503/JCB_copro.zip)

Thus, go in "Copropriete" admin view, add as linked admin view "assemblee".
Generate and install component "com_copro".
Editing an Copropriete is not working, you have a message like "ops! error....."

### Expected result
list of "assemble" from a "copropriete" in "Details" tab (or in another tab if must be)

### Actual result
Editing an Copropriete is not working, you have a message like "ops! error....."

### System information (as much as possible)
- OS Name & Version: Win10
- MySql Version: 
- Apache Version: 
- PHP Version: 7.1.x
- Joomla Version: 3.8.12
- JCB Version: latest
- Browser: Firefox

### Additional comments
Content of folder "administrator\components\com_copro\layouts\copropriete" is strange, with file named like "_fullwidth.php" for instance...
Notice that there are a few french character like "é" thay may disturb JCB...

Thank you for your help...

**Comment by Llewellynvdm** [comment]
Hi, the **oops! error** is only found one place in [JCB on line 8110](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L8110). Why it happens is because all the details of the linked view is nit set. So please [watch the tutorial](https://youtu.be/CdSKSCTzmRA?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&t=20m55s) on how to link one view to another.

You can also review this[ tutorial](https://youtu.be/91iIAuHZj38?t=1h3m5s) as I also explain a little more about linked views. Watching the whole tutorial will help much to understand custom fields even better, which is used to setup liked views.

**Comment by Llewellynvdm** [comment]
I am closing this, but let me know if you still having trouble by just commenting on this issue.
