### ISSUE TITLE
Feature Request: Select Admin For Buttons

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#346]
This feature request is to select an admin form Buttons that could display on both Admin View and Site View. The idea is that sometimes when we set backend form on front end we might not need all buttons but just "Save/Apply" and "Close/Cancel" or "Save and Close" and "Close/Cancel". For example when editing a particular single record that will never be saved as copy or will never have "Save and New" function. In that scenario it will be extending the user profile with custom fields based on the component requirements.

**Comment by Llewellynvdm** [comment]
To hide save and new, or save as copy just add a return value to the url, or the ref and refid values to the url.

JCB now does full implementation of the return value. This works ideal when you want to return the user to the place where the first click in the edit path was made.

**Comment by peterpetrov** [comment]
I am not following how the actual buttons will hide if i edit the url values?

**Comment by Llewellynvdm** [comment]
I know this is not fool proof... but is the first step to hiding buttons.

Just try it, open a site edit view, and add `&return=xxxxxxxxxxxxxxx` to the url and see it work. This behavior is default to all JCB build components.

We can look at adding it as a hard coded option... try out the above an let me know what you think.

**Comment by Llewellynvdm** [comment]
The code that does this, is found in each view.html.php file of an edit form.

So in JCB look at these few lines.

- On [line 39](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/admin_fields/view.html.php#L39) we get the return value.
- On [line 88](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/admin_fields/view.html.php#L88) we check if we have a return/referral value.

Then we load the buttons based on that.

**Comment by peterpetrov** [comment]
![screen shot 2018-09-25 at 11 42 56](https://user-images.githubusercontent.com/2786810/46003080-56f1c200-c0b8-11e8-9c02-fa2acced6682.png)

I am actually talking about that line. This is a front end of Joomla displaying the buttons. So the feature request is to select which one of them to show on the Admin View and respectively it will show on front end. Please let me know if that make sense?

**Comment by Llewellynvdm** [comment]
The front-end and the back-end edit view works the same at this time, no difference really. So if you look at the front-end of your component in the view.html.php file, you will see the same code.

**Comment by Llewellynvdm** [comment]
So with:
```
/index.php?option=com_anthropometry&view=form&field=member&field_id=1&layout=edit&return=aW5kZXgucGhwP29wdGlvbj1jb21fbWVtYmVyc21hbmFnZXImdmlldz1wcm9maWxlJmlkPTE6bGxld2VsbHluLXZhbi1kZXItbWVyd2UmSXRlbWlkPTE0NjQ1
```
The view looks like this:
![image](https://user-images.githubusercontent.com/5607939/46003738-85b86a00-c0b1-11e8-976a-1fb1bc7f355b.png)

And with:
```
/index.php?option=com_anthropometry&view=form&field=member&field_id=1&layout=edit
```
![image](https://user-images.githubusercontent.com/5607939/46003804-9f59b180-c0b1-11e8-9a28-7a3418abf374.png)

Can you see the buttons are hidden? by just adding a return value, all we need to do then, is in the save method do a validation check. So that if the user try to create more then one item that the system returns an error and does not allow the save to continue. So yes little bit of custom script, but this way you get the behavior you want, and it is unique to your component.

The area to add the custom script in the admin view:
![image](https://user-images.githubusercontent.com/5607939/46004159-7c7bcd00-c0b2-11e8-8c81-61c0aff8d833.png)

Then you write a helper method, that can be used across many views and items to validate the behavior. This is the best option!

**Comment by peterpetrov** [comment]
Thank you very much! I get it now.  The return value works great for me. Cool stuff. Just tested it - works great. I got the idea now. Thank you very much again!
