### ISSUE TITLE
are you correct set tutorial link? 

### ISSUE THREAD

**Issue by saman222** [vdm-io/Joomla-Component-Builder#351]
hi
i want see you tutorial in this link:
https://github.com/vdm-io/Joomla-Members-Manager
but when click on that it show export and import tutorial.can you check that?
also i want suggest use documented tutorial instead of video is better because in the video we need more english language skill. 
thank you

**Comment by Llewellynvdm** [comment]
That is correct, the tutorial is not for [JMM](https://github.com/vdm-io/Joomla-Members-Manager) but to show how to import the JMM package into JCB.

So documentation would be great, I am just not able to do that at this time.

I am closing this issue, since it is not code related, if you continue to have questions like these please [use the forum](https://groups.google.com/a/vdm.io/d/forum/jcb).
