### ISSUE TITLE
Dynamic Get -> Join Table issue

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#361]
### Steps to reproduce the issue
Create new dynamic get and join a table that is not part of the component. For example imported table without the prefix of the joomla structure.

### Expected result
Join the table.

### Actual result

Table name is "table_name":

JDatabaseExceptionExecuting: Table 'db.#__table_name' doesn't exist

It seems the component after being compiled "assumes" that the table should be with prefix. That is probably replacement code that renders the table name.

### System information (as much as possible)
- OS Name & Version: Centos 7
- MySql Version: MariaDB 10
- Apache Version: Nginx 1.12
- PHP Version: 7.2
- Joomla Version: 3.9.1
- JCB Version: 2.9.8
- Browser:

**Comment by Llewellynvdm** [comment]
Yea at this point the dynamic get only retries data from tables that is part of Joomla. I can look into it and see what can be done, give me a few days.

**Comment by peterpetrov** [comment]
This is not urgent at all. I have done a workaround. Just an observation I wanted to report.

Regards
Peter

**Comment by ro-ot** [comment]
We must have a whole new option **External Database** because the real problem here is targeting a database or table outside of the current Joomla database and tables is not that simple. But will require a new `JDatabaseDriver::getInstance()` initialization. The current model does not make this possible without adding more method overrides.

Therefore the way @Llewellynvdm build this is correct, and to expect the above is outside the normal scope of the MVC as set forth in Joomla. The BaseDatabaseModel initialization is not taking any parameters so it defaults to the current prefix and database as found in the config via the Factory class method `createDbo()`.

I would therefore say @peterpetrov rename the table. If that is not an option write your own custom workaround as you did. I don't think we should even try to add this as a feature and should any want this kind of hot-wiring they should custom code it. So it can be done but never by default.

**Comment by Llewellynvdm** [comment]
Thanks @ro-ot for taking the time to look at this, and I think you are right the model is assuming the boundaries as set forth in the config. So yes, @peterpetrov hope you will understand that we will leave this as is (meaning not add the feature, but stay with custom coding this), unless you feel the current explanation of @ro-ot is not fully accurate, then let me know.

**Comment by peterpetrov** [comment]
Hey Guys, Thanks for answering. I will explain myself only for the purpose of the conversation. When i asked the question i have imported a list of towns which created a table which resides within the exported sql file. Now there is no issue to rename the values in the file and then import them. But there is a point to be able to have an option if you import external data and you want to have it in another table which doesn't have the prefix. I can always do custom code but i am explaining possible situations just to make sure you understand my point.  

My other point is that the table actually is listed when i want to select it without the prefix but Joomla assumes it is missing and adds the prefix to the query.  So the term external assumes external for Joomla. Or at least to me.

Having said that i am happy without going forward with any changes on this matter. :)
