### ISSUE TITLE
Custom Codes aren't always being added

### ISSUE THREAD

**Issue by AlexDings** [vdm-io/Joomla-Component-Builder#364]
### Steps to reproduce the issue
Add a custom code reference to other custom codes multiple times at different depths(?)

### Expected result
The custom code placeholders are replaced by their code

### Actual result
A custom code placeholder might be replaced in one spot but left untouched in another

### Additional comments
I have not been able to analyze why some custom code references get replaced and some not. Even the same reference behaves differently in different locations. 
Could it have something to do with nesting custom codes?

I am using the regular JCB custom code implementation [CUSTOMCODE=customcodename]

**Comment by Llewellynvdm** [comment]
Okay so lets do this... get ready it gets messy as we are trying to do what should not really work.

Custom code in other custom code, really only works perfectly two layers down. But @AlexDings like to push the boundaries :+1: and so we see that deeper nested code does not get replaced. Which takes us to the code... so lets look at this.

The center of the actual engine is the method called `setCustomCodeData` on [line 4785](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L4785) of the `Get` class.

You can follow the execution back and forward from there, you will see there is a little debug snippets scripts to sort of peak into the execution. Then on [line 4905](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L4905) we see the `getCustomCode` [method](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L5428) being triggered if custom code was detected in the string. Then again on [line 5472](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L5472) we see that if `$setLang` is false the recursion takes place to look for more custom code placeholders in custom code.

This is because `$setLang` is only `true` in case we are adding custom code that was done in the IDE and is linked to a `Hash (automation)` implementation. We still do not allow custom code place holders to be used in that regard. The madness of all this is still a little head of me, so I have not yet explored those options. Question: is some of your issues related to this type of code?

Okay lets assume you are just working with `JCB (manual)` implementation, which is almost like `traits` well then we are on [line 5479](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L5479) and we are calling the `setCustomCodeData` method on the code string. This should continue over and over again... until all code is updated.

But that is not what you are finding, so could you take the implementation of what you are trying to do, add it to the demo component (just dummy stuff) and add the exported JCB package here for me to use in testing. Since I have not yet seen this happen that the code do not get updated.

Okay here is one more thing, you will see there is a `$not` value passed to `setCustomCodeData` this servers as a trigger to prevent an infinite loop. So that the ID of the current customcode does not get added to the `$bucket` as an option to load again... hmmm this could also cause some strange behavior. So you could remove [line 4887](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L4887) and see if that has an effect.

**Comment by AlexDings** [comment]
Thank you for your response. This issue has halted my development as I am trying to wrap my head around it. If not, I will have to "flatten" all my custom codes for now.

> Question: is some of your issues related to this type of code?
No, all of the code is places with the IDE's [CUSTOMCODE=codename]

> So you could remove line 4887 and see if that has an effect.
I have commented it out, to no effect.

The custom code that doesn't get placed is used inside a template, which is used inside a site view.
When trying to isolate the issue and copy it to the demo component I found something interesting.

I took the following steps:
- Simply use this site view in another empty component (without even linking it to a proper table)
- Look at the templates and see all custom codes get generated accordingly

The only difference between the two components' template would then be that in one it is used across multiple site views. Does that ring a bell or point you in a direction?

**Comment by Llewellynvdm** [comment]
Just as a note upfront, I use custom code everywhere, and inside each other, and in templates and well... everywhere. Yet without the kind of behavior you are encountering... that is why I asked for a exact (dummy) component to test on my end what you are seeing. This will help me resolve the issue.

The template code gets loaded on [this line 3725](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L3725), and templates get generated for each view, if used across multiple site views. Here on [line 3745](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L3745) is the content updated with the custom code using the global method I mentioned is used mostly called `setDynamicValues` This method would every time update every custom code placeholders and all those found in custom code.

The method called `setTemplateAndLayoutData` is used for both Template and Layout data, and is found one [line 3631](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L3631) as you will see it builds an array called `$this->templateData` that is based on target (admin|site|both) and view (name) to [later build the actual files](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L4351). You should be able to see the logic in how we search for more template and layouts in each site view and template/layout.

So this array avoids the templates from clashing across multiple site views, and is never reused due to the avoid exactly that type of behavior. So hmmm it is also strange to me, and why I really would like to know what is happening here :) I resolved this behavior like 5 years ago... so if it is back, I want to patch the leak.

Just for interest sake do you have site views that have the same names as back-end edit views? Since I know that will cause conflicts if those edit views is set to also be available as site-edit views.

This is where the `templateData` array gets started on [lines 2251](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L2251) and so this is where site views with the same names will get erased and only one will remain.

I am sure this is a small issue really, so giving me a packages with that behavior will help.

**Comment by Llewellynvdm** [comment]
Thanks @AlexDings for sharing your component, it did help us find the issue, and I trust it has now been resolved. Please run some test and let me know.

**Comment by AlexDings** [comment]
Thank you. The code compiles as expected.
