### ISSUE TITLE
Feature Request - Add css class option to control-group in edit form

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#367]
Add the ability to add a 'wrapper' CSS class to any field added to an admin view so that the class is added to the edit view (admin/front) at the point where the "control-group" class is added to the div.

example of front-end code currently created:

```
<div class="row-fluid form-horizontal-desktop">
  ::before
 <div class="span12">
    <div class="control-group field-spacer">...</div>
    **<div class="control-group">**
      ::before
      <div class="control-label">
        <label id = ....
      </div>
      <div class="controls">
        ...
      </div>
      ::after
   </div>
```

Being able to target this level of div will allow more options in the layout of the edit forms (without needing to manually override the entire edit form layout.

**Comment by cpaschen** [comment]
I realized that adding the ability to add a unique tag to at field via the gui is just asking for more code to maintain (that would probably be less used than most features) and would also increase the business of that already full field form.

Instead, why not just automatically add the field name as a class to each of those control-labels. That already happens at the label level (each label already has a class applied that is unique to that field).
If we just added that same class at the control-label div then it would only take a couple/few lines of code and no gui interruptions.

So the resulting html might look like:

`<div class="control-label  this-field-name">`

**Comment by TLWebdesign** [comment]
That sounds like a good option.

**Comment by Llewellynvdm** [comment]
Due to the nature of complexity here just adding the field name is not that simple, there can be cross matching behavior since Joomla already uses the field name when building the field. Then most importantly, you do Joomla builds the field HTML and not JCB right?

I mean the code that delivers the HTML code you placed in the opening comment of this issue is generated with this line:
```php
echo $form->renderField($f);
```
In some layout template that JCB build... and then Joomla internal classes take over.

This is because we are using the Joomla core/API to build our forms, which is best practice. Now to see how Joomla builds these fields you need to look at [each class of each of these field types](https://github.com/joomla/joomla-cms/tree/3.10-dev/libraries/joomla/form/fields). Like the [text field](https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/joomla/form/fields/text.php) gets its input layout from a [default layout](https://github.com/joomla/joomla-cms/blob/3.10-dev/layouts/joomla/form/field/text.php) template and its label layout from the [default renderlabel](https://github.com/joomla/joomla-cms/blob/3.10-dev/layouts/joomla/form/renderlabel.php) template. Then it gets combined here in the [renderfield](https://github.com/joomla/joomla-cms/blob/3.10-dev/layouts/joomla/form/renderfield.php) template. All these templates can be manually over written per website, in the template of your website.

So since we are following Joomla conventions the best way to reach in and touch these values will be with either a local template override, or some JavaScript.

The JavaScript that could do the trick very simple looks like this:
```JavaScript
jQuery('#jform_fieldname').closest('.control-group').addClass('whatevername-youlike');
```
So in sort, sorry @cpaschen that area is out of our reach.

**Comment by Llewellynvdm** [comment]
Hmmm that last line was not the whole truth, it is not out of our reach... just out of JCB's reach. You can reach these areas like the control-group, but you need to do some research on the internal workings of the Joomla API.

I quickly again looked over it and on [line 28](https://github.com/joomla/joomla-cms/blob/3.10-dev/layouts/joomla/form/renderfield.php#L28) in the [renderfield](https://github.com/joomla/joomla-cms/blob/3.10-dev/layouts/joomla/form/renderfield.php) template there is being test for a class value. If I was you, I would track that value back to its origin.. and see how I could from the field xml properties load that value, and if it is possible. I just do not have the time right now... but if you can do that and give me some feedback, I can see what I can do to help you adjust JCB "field types" to resolve this issue.

**Comment by Llewellynvdm** [comment]
Okay... this is good news, but also a little tricky. I found the path, was simple actually.

You will see here on [line 948](https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/Form/FormField.php#L948) of the global FormField class, that gets inherited, the class is passed as part of the `$options` array. Now by my own admission JCB triger that method with `echo $form->renderField($f);` the `$f` value is only the field name at this moment.

So I was wrong... JCB can very easy reach this area, but we will need to rewrite a whole are of the field builder, and that is little tricky. Give me a few days to think this over...

**Comment by Llewellynvdm** [comment]
Sorry [this is actually the trigger](https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/Form/Form.php#L664) method...

So we can change JCB to use the following.
```php
$form->renderField($f, null, null, $options);
```
Then in options add the class... 

About the class, I think just using the name directly is not a good idea, I think we should instead add a prefix of our own just to avoid conflicts.

so lets go for:
```php
$class = 'control-' . $fieldname;
```
Then just to make sure we are on the same page, this will add a class value to the `control-group` div that wraps around the label and input divs.

 Give me a few days to think this over... and then I will push out this feature :+1:

**Comment by Llewellynvdm** [comment]
Okay the wrapper class has been added, please checkout the last update to the staging branch.

You will see it adds a class to the fields outer div like this:

```html
<div class="control-group control-wrapper-field_name">
```
Please test and let me know if you have any more questions.

**Comment by TLWebdesign** [comment]
Awesome 😀
