### ISSUE TITLE
No rows are shown - admin list view

### ISSUE THREAD

**Issue by tonypartridge** [vdm-io/Joomla-Component-Builder#375]
It would appear that the default_body.php is near empty and only contains the edit link. Even though fields are set to show is list view and filters to be shown? Last release.

**Comment by peterpetrov** [comment]
Hey Tony, the reason you are not seeing the row is because you have not set the behaviour of the fields in the admin view. You need to chose other then default when you add them to the admin view. 

Also just so you know we have a "google forum" where the community is asking most of the questions related to JCB and they are not a bug. The way it "works here" is we use the forum as first line of questionaries and if we find that it is a bug we log it here with the required information. Here is the link:

https://groups.google.com/a/vdm.io/forum/?utm_medium=email&utm_source=footer#!forum/jcb

Cheers,
Peter

**Comment by tonypartridge** [comment]
Hello Peter,

Thank you for that! Makes sense now I know :-) Thanks for the group too!
