### ISSUE TITLE
Export/Import JCB Packages: Field Category not included

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#385]
### Steps to reproduce the issue
Make sure your component uses at least one field which is assigned to a Field Category.
Export component using `Export JCB Packages`.
Import the exported package in a virigin JCB installation.

### Expected result
See the Field category.
See the Field assigned to the Field Category.

### Actual result
The Field Category is not there.
The Field is not assigned to any category.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: 2.9.11
- Browser: FireFox

**Comment by Llewellynvdm** [comment]
Due to the nature of category id being fully controlled by Joomla and not JCB, we are not exporting the category mapping of fields (of JCB) at this time, sorry about that... 

To putt this simple, the option to remap those categories (and create one dynamically) on import of a JCB package is just been to great of a task, with to small necessity. So I just did not take the time to build that in. Ones you understand the nature of the import of the JCB package more you are welcome to add the needed code to this issue if you like to add this feature. I can't at this time commit to that :+1:
