### ISSUE TITLE
Site View CSS and JS files keep being generated when set to No

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#388]
Site View CSS and JS files keep being generated when set to No

### Steps to reproduce the issue
Open a Site View
Make sure **Add JavaScript (file)** and **Add CSS** are set to `No`
Make sure no view specific CSS and JS files exist in the components frontend `assets` folder.
Compile and install component.

### Expected result
No view specific CSS and JS files in the components frontend `assets` folder.

### Actual result
Both a view specific CSS and JS file exist in the components frontend `assets` folder.

### System information (as much as possible)
- OS Name & Version: JCB 2.9.11
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: JCB 2.9.11
- Browser: FireFox

### Additional comments
Setting either of the mentioned fields to `Yes` without actually adding any code and trying to save the view, results in an error message because those fields are required. So there is no reason to generate those files when they are set to `No`. However, you could consider to generate empty files when they are set to `Yes` and no code was acutally added. The problem is they now possibly interfere with custom library files with the same name, if one would want use that feature.

**Comment by Llewellynvdm** [comment]
Okay the behavior is not ideal, but it is how it works. Meaning the files are being added even if no code is added. hmmm yes we should improve this, the expected result should be, if not code is set then no file is added, but there are some very smart feature that makes it a little more complex, so give me a little slack here.

At the field level you will see the option to also add javascript or css to any view that use the field, either in the edit view or the list view. This means code is not only going to those files in direct relationship of the view settings but also based on each field being added.

At the time of the initial development the trade-off was time, I needed the feature, and did not have the time to iron out the whole mapping of whether there is actually code for the file, so we generate the file and then if code exist we just dump it in not only then creating the file.

This lazy convention if you will does lower the memory footprint and helps focusing on more advance issues. So yes we may change this at some time, when I have time to improve the trigger event on the file build, as this happens before all the code is complete. So it is a limitation at this time, but there is so much tied into it, then moving things will break other things due to timing (when what is written where) and searching coexisting with the compiling of the component.

So I am closing this with an apology that this little "o no" is really worth it. Then the library files are set on a way different location under [media](https://github.com/vdm-io/Joomla-Component-Builder/tree/staging/media), and not like these in the component under [admin assets](https://github.com/vdm-io/Joomla-Component-Builder/tree/staging/admin/assets) and [site assets](https://github.com/vdm-io/Joomla-Component-Builder/tree/staging/site/assets). So the idea that they will conflict is not possible, and the very reason they are separated to avoid conflicts.

**Comment by Llewellynvdm** [comment]
Little correction, the fields do not add the the file, the conditions (if set) does.
