### ISSUE TITLE
Calendar / Datetime Field:  Default value is not set correct

### ISSUE THREAD

**Issue by TheWhykiki** [vdm-io/Joomla-Component-Builder#393]
### Steps to reproduce the issue

Add a new field type Calendar to an existing component, set to datetime, leave values as JCB provides. Leave also default value at NOW.
Add field to admin view and compile. 

Second approach: Change default date value in the component update section to '0000-00-00 00:00:00'

### Expected result

Get a working now date as default or even the '0000-00-00 00:00:00'

### Actual result

JCB empties the default value, so when installing on a fresh system the error:

"Invalid default value for 'yourfieldname'" is thrown.

In the SQL statement I get '`yourfieldname` DATETIME NULL DEFAULT '','

Even after changing the value manually in the component update section, in the sql update file the default value is emptied.
At the moment I have to fix the sql files manually and rezip the component before uploading on a new system. 

### System information (as much as possible)
- OS Name & Version:  Windows 10
- MySql Version:  5.6.3.4
- Apache Version: 
- PHP Version: 7.1.7
- Joomla Version: 3.9.3
- JCB Version:  Actual from git
- Browser: Chrome

**Comment by peterpetrov** [comment]
Hey, it is tricky with calendar fields. At the moment if there is no production or important data i would suggest to uninstall the component, find the sql update files within the filesystem, remove the file in question (the one that holds the date field creation) or update it. Or at least fix the creation of the field there.

You are experiencing that because you have not defined the default value for the date field and MySQL doesn't like it. I have ran many times into that issue. The best way is to have it done properly the first time otherwise the update files will keep the old value. That is to do with how JCB runs updates on database which is related to the versioning too.

**Comment by TheWhykiki** [comment]
I set the default value to NOW...

**Comment by TheWhykiki** [comment]
I tested some more with a fresh install and another new component and in my case, local with MAMP Pro on a windows machine, everything I add to the default field is emptied out. So installing a component with calendar field always needs manual correction.

**Comment by TheWhykiki** [comment]
I found a workaround:

Just using the date of birth field from demo component and rename it to your needs. Its not the best way, but for the moment it does the trick - but for now you can only use one date field.

**Comment by Llewellynvdm** [comment]
I see there has been some [more comments](https://groups.google.com/a/vdm.io/forum/#!topic/jcb/sQZPGDyfpkw) on this in the [forum](https://groups.google.com/a/vdm.io/forum/#!msg/jcb/jqlqPdowePw/pKnGAuvQBAAJ), I will direct the discussion there, and close this issue.

Should you feel this is a bug and needs fixing let me know, at this point due to the nature of JCB we have left this an open-ended adjustable approach which at times require some more insight as with the date field.

But I get the point, just not think we should hard code a solution, may be instead just add some comment that would be informative... so write something up if you think that will help. Then I will add it in.
