### ISSUE TITLE
Path constants in Component files folders don't work

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#396]
### Steps to reproduce the issue
Add a arbitrary file using the 'Component Files & Folders' functionality of a component on the 'Advanced' tab.
In the target path use one of the documented path constants. 
For example: JPATH_ADMINISTRATOR/models/fields

### Expected result
A folder whose name is the replaced path constant. 
For example: /admin/models/fields

### Actual result
A folder named literally after the path constant used.
For example: JPATH_ADMINISTRATOR/models/fields

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: JCB 2.9.13 Beta Release 2019-03-06
- Browser: FireFox

### Additional comments
When specifying the real path, it works just fine.

**Comment by Llewellynvdm** [comment]
Hmmm I can't say that is correct really (I mean it works), I have a few components and they all use this feature, and actually work. This is due to you being on Windows and is related to an open unresolved issue #231 

SO I will close this and ask that we continue communication about this on the [original issue](https://github.com/vdm-io/Joomla-Component-Builder/issues/231).
