### ISSUE TITLE
MySQL Install Error

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#400]
### Steps to reproduce the issue
Installation of a component DB in MySQL 5.7 results in the following error: 
**error: 0 row(s) affected, 1 warning(s): 1101 BLOB, TEXT, GEOMETRY or JSON column 'params' can't have a default value**

### Expected result
Table would install error free.

### Actual result
The install errors on MySQL 5.7

### System information (as much as possible)
- OS Name & Version: Centos
- MySql Version:  5.7
- Apache Version: 2
- PHP Version: 7
- Joomla Version: 3.9 
- JCB Version: n/a
- Browser: Chrome

### Additional comments
this was the property that caused the error:
`params` text NOT NULL DEFAULT '',

changing to `params` text NOT NULL made it work

This is a new table from a new admin view that I added. I think it is related to HOW JCB is adding the params fields. In another field that I have as TEXT, JCB created the field as `fieldoptions` TEXT NOT NULL, but for params, JCB created the field as `params` text NOT NULL DEFAULT '',. Removal of the DEFAULT '' on params allowed the component to install without MySQL errors.

According to my research, MySQL 5.7 defaults to STRICT mode, which apparently throws an error when DEFAULT '' is used.

**Comment by mwweb** [comment]
Added note: This only appears to occur if the field type is text, blob and json fields

**Comment by Llewellynvdm** [comment]
There is a few places that does this, I mean fields on [line 6243](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L6243) is the part that is related to this issue, but you will see on [line 6303](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L6303) we have more fields using this.

Okay so I need you to confirm that changing this globally will net effect MySQL 5.5 and up, so that we remain backward compatible.

I am little occupied at the moment, but I can push out this update if we were sure the change will not break things :+1:

**Comment by mwweb** [comment]
I just tested in a blank Joomla installed. In my test, I deleted all instances of DEFAULT '' from install.mysql.utf8.sql, and it installed fine with no errors on Joomla 3.9.4 Database version 5.5.5-10.1.34-MariaDB-1~trusty

**Comment by Llewellynvdm** [comment]
Okay please test the staging branch and let me know if the update as really resolved the issue.

**Comment by mwweb** [comment]
I setup a special install using MySQL 5.7, and it installed fine with no errors.
