### ISSUE TITLE
Install Package Broken

### ISSUE THREAD

**Issue by VinylVault** [vdm-io/Joomla-Component-Builder#401]
### Steps to reproduce the issue

Compile Project

### Expected result

Successful install

### Actual result

JInstaller: :Install: Can't find Joomla XML setup file.

Unable to find install package

### System information (as much as possible)
- OS Name & Version: Synology NAS
- MySql Version: MariaDB10
- Apache Version: Tried with Apache 2.2, Apache 2.4 and Nginx
- PHP Version: 7.2
- Joomla Version: 3.9.4
- JCB Version: 2.9.11
- Browser: Chrome, Safari and Opera

### Additional comments

I am sure that a lot of people will assume that the priblem lies with the Synology NAS that the webserver runs on for development, however, this is unlikely to be the case, as there have been no updates to the NAS since it was working perfectly, at the last version of the Component.  I have successfully compiles and installed 11 versions (all with minor changes) on this same NAS, yet when it comes to version 12, again with minor changes and additions, it fails to compile correctly.

Any Suggestions would be appreciated

**Comment by Llewellynvdm** [comment]
I do not get the same issue, but then again I am on Ubuntu and do not have Synology NAS so I can't reproduce the issue.

Have you open the package (since it is simply a zip package) and looked in it to confirm that the xml is indeed not generated? If all the files are not being build this must mean all the needed PHP modules are not installed or not active. Here is a list of all the [modules I have on](https://github.com/vdm-io/Joomla-Component-Builder/issues/90#issuecomment-304946815), it can also be a permission error/issue. Make sure you file system permissions are correct as per/joomla specifications.

If all the modules are on, have you tried to install the (produced) package with Joomla's own installer? I mean the package that JCB creates when you click compile... try and install it directly with Joomla.

I know you made the point that it is not the Synology NAS, and yet I do not get the same error on Ubuntu, or Centos. So hmmm, if you tried the above and yet still no success you may need to look at that point again.

**Comment by mwweb** [comment]
i have encountered this same thing a few times myself. I seem to be able to reconcile and it works. I just tacked it up to being an oddity.

**Comment by VinylVault** [comment]
@Llewellynvdm I have checked each one, and there is no XML file created

**Comment by Llewellynvdm** [comment]
if the xml file is not created, then there will be many files not created, since they are all done with the same methods and implementations. This means your environment is not setup correctly.

I only give support for Ubuntu and Centos, and then I direct developers to the use of docker and other tools like Bitnami to setup the Joomla installed environment as this takes care of all the complexity.

So this is not a JCB issue, and therefore you will need to seek help from the `Synology NAS` community as to ensure the PHP environment is correctly setup. Here is the [help I can give you for setting up a local development environment](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=72), any help beyond this is unfortunately not possible from my side at this time.

**Comment by VinylVault** [comment]
ok now its weird, the test component compiles fine, and i've just added all my admin views to a new component, and thats comiles and intalled fine ....

**Comment by Llewellynvdm** [comment]
Interesting... if you find anything more, you are welcome to comment it here.

**Comment by VinylVault** [comment]
yeah, very strange, the new and old compients are now in the same condition, so on with development, the old one will be discarded
