### ISSUE TITLE
Use of array_unique

### ISSUE THREAD

**Issue by tonypartridge** [vdm-io/Joomla-Component-Builder#402]
Using the select list for usergroups in views the generated code is flawed. IT comes out as:

	protected function getTheUsergroup_twoSelections()
	{
		// Get a db connection.
		$db = JFactory::getDbo();

		// Create a new query object.
		$query = $db->getQuery(true);

		// Select the text.
		$query->select($db->quoteName('g.usergroup_two', 'id'));
		$query->select($db->quoteName('ug.title', 'title'));
		$query->from($db->quoteName('#__listmanagement_user', 'g'));
		$query->join('LEFT', $db->quoteName('#__usergroups', 'ug') . ' ON (' . ($db->quoteName('g.usergroup_two') . ' = ' . $db->quoteName('ug.id') . ')'));
		$query->order($db->quoteName('title') . ' ASC');
		$query->group($db->quoteName('ug.id'));

		// Reset the query using our newly populated query object.
		$db->setQuery($query);

		$results = $db->loadObjectList();

		if ($results)
		{
			$results = array_unique($results);
			$_filter = array();
			foreach ($results as $usergroup_two)
			{
				// Now add the usergroup_two and its text to the options array
				$_filter[] = JHtml::_('select.option', $usergroup_two->id, $usergroup_two->title);
			}
			return $_filter;
		}
		return false;
	}

PHP 7.2 causes a fatal error with array_unique on an object. I'l a little unsure why we are using array_unique in this scenario. IT would make more sense to group by id which we are already doing.

**Comment by Llewellynvdm** [comment]
Well it is because in the compiler the method `setFilterFunctions` where this [code is build](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L10662) is being used from much more then groups, and if I remember correctly it is [your changes](https://github.com/vdm-io/Joomla-Component-Builder/commit/c9d9f8b7a8fc3307abf82785f6dc318a5fbc03e8#diff-001cb31b03c7dade5d5f5df9897ff487R10639) that added the `$db->loadObjectList();` to the area.

So it is not a problem, or needed with groups, but with other implementations at times it is most certainly needed.

I will see how we can remedy this.

**Comment by Llewellynvdm** [comment]
This should fix the issue, let me know :+1:
