### ISSUE TITLE
Feature request: Component config: front and back end separated

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#409]
I think that a feature to add to JCB is to let users to choose to add config fields only to front end, only to back end or to both.

With this we can keep the component clean and simple when all these options are not required.

**Comment by Llewellynvdm** [comment]
Okay for me to be sure we are speaking about the same thing, you will need to give some examples.

We have a component global options area also called the config area, is this what you are speaking about, since it is from this area we can pass fields to the related front-end menu of a site view. I think there is some tutorials about this... but first help me to know if we are taking about the same thing.

For example if you want the field permissions that are also in the config area to only be related to the admin or site area... then that is not possible, since it will create a weakness in security. But more importantly it will make it much more messy and not cleaner.

IF your actual aim is to have config fields only in global options and not in the menu, or just in the menu and not as part of the global options... then I have great news this feature already exist.

But okay let me know if we are on the same page.

**Comment by jcodewalker** [comment]
`IF your actual aim is to have config fields only in global options and not in the menu, or just in the menu and not as part of the global options... then I have great news this feature already exist.`

Yes, is this. 

Example:
I need:
field "abc" with custom value "cde" in a tab named "fgh" in the front end only
field "ilm" with custom value "nop" in a tab named "fgh" in the back end only
So, as you can see, both fields are related to the same tab name but different destination, one for fornt end only, the other for back end only.

If it is already possible, please let me know the video link. Thank you in advance!

**Comment by Llewellynvdm** [comment]
> 

I know we have this in some tutorial somewhere... but its the classic example of to many things in one video so I did not find it at a quick glance... so I just made another one so others can find the solution more easy :+1:

**The new tutorials name is:**
[Manage a Components Global Config Option Field in Relation with Menu Params](https://youtu.be/dhVVQP4KS3Q) _the quality of the video will improve after an few hours as youtube converts it to all the formats... right now it is still in low quality._

Enjoy!

**Comment by jcodewalker** [comment]
To much kind of you!
Thank you!
