### ISSUE TITLE
Ubuntu compile

### ISSUE THREAD

**Issue by RRino** [vdm-io/Joomla-Component-Builder#421]
### Steps to reproduce the issue

Compile and install

### Actual result

JFolder: :delete: Could not delete folder. Path: /opt/lampp/htdocs/jmappas/administrator/components/com_componentbuilder/compiler/com_Hello_World_v1_0_0__J3/admin/helpers
JFile: :copy(/opt/lampp/htdocs/jmappas/images/demo300.jpg, /opt/lampp/htdocs/jmappas/administrator/components/com_componentbuilder/compiler/com_Hello_World_v1_0_0__J3/admin/assets/images/vdm-component.jpg): copy(/opt/lampp/htdocs/jmappas//administrator/components/com_componentbuilder/compiler/com_Hello_World_v1_0_0__J3/admin/assets/images/vdm-component.jpg): failed to open stream: File o directory non esistente
JFile: :copy(/opt/lampp/htdocs/jmappas/images/Full-Bucket-icon-plus.png, /opt/lampp/htdocs/jmappas/administrator/components/com_componentbuilder/compiler/com_Hello_World_v1_0_0__J3/admin/assets/images/icons/greeting_add.png): copy(/opt/lampp/htdocs/jmappas//administrator/components/com_componentbuilder/compiler/com_Hello_World_v1_0_0__J3/admin/assets/images/icons/greeting_add.png): failed to open stream: File o directory non esistente
JFile: :copy(/opt/lampp/htdocs/jmappas/images/Full-Bucket-icon.png, /opt/lampp/htdocs/jmappas/administrator/components/com_componentbuilder/compiler/com_Hello_World_v1_0_0__J3/admin/assets/images/icons/greetings.png): copy(/opt/lampp/htdocs/jmappas//administrator/components/com_componentbuilder/compiler/com_Hello_World_v1_0_0__J3/admin/assets/images/icons/greetings.png): failed to open stream: File o directory non esistente

### System information (as much as possible)
- OS Name & Version: Ubuntu 18.04
- MySql Version: mysqlnd 5.0.12-dev
- Apache Version: Apache/2.4.39 (Unix) OpenSSL/1.0.2s PHP/7.2.19 mod_perl/2.0.8-dev Perl/v5.16.3
- PHP Version: 7.2.19
- Joomla Version: 3.9.8
- JCB Version: 2.9.18
- Browser: Versione 75.0.3770.80 (Build ufficiale) (a 64 bit)

### Additional comments

until a few days ago everything worked well then with Demo it sometimes works with Hello World and my components alarm me: it is not possible to delete.

I try to reinstall Ubuntu, Xampp, joomla  but everything remains the same

Thank you
Rino Ruggeri

**Comment by Llewellynvdm** [comment]
Please check your file permissions, here is [how to insure they are correct](https://stackoverflow.com/a/11512211/1429677). Since that would be the first reason for the error, secondly make sure that your Apache is having access to the files.

Here is an [easy tool I found to setup your local development](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=73&t=0s).

Reality the class used to delete and move files in JCB is a Joomla class, this means if there is an error it is an environment error, or a Joomla error. Since it all still works well for the rest of us, I would first suspect it is an environment issue on your side.

**Comment by RRino** [comment]
[SOLVED] the problem is caused by an update of Ubuntu Mate version 18.04, with an old version 16.04 everything works
Thank you
Rino Ruggeri
