### ISSUE TITLE
Ability to switch of "numberconversion"

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#427]
JCB converts numbers, as in sequence of digits to their alfanumeric counter part
a field 
`
'a2' will result in 'atwo'
`
JTEXT custom code for a button
`
JText::_('J3-ADMIN-2019_CONFIG_000019_Q');
gets renamed to
JText::_('COM_JCPQM_JTHREEADMINTWO_THOUSAND_AND_NINETEEN_CONFIG_NINETEEN_Q');
`

at first i thought it was a minor nuisance bu integrating with third parties is becomming a royal pita.

I understand from discussion that this behaviour was intended to make the code more stable, to me the opposite is becoming reality :( 

I would really appreciate a configuration option to turn off this behaviour

**Comment by Llewellynvdm** [comment]
Hmmm this is not that simple, but okay it not the first time you have brought this up... let me look into this. The reality is we build so many parts of the code from these safe" strings, that just like other changes we recently made to JCB we will be faced with bugs the moment I open that door.

You have found areas where this convention is a pain, but have you seen the result in JCB without these conventions? JCB is a very fine balanced set of conventions, which I have honed into a stable factory line. This piece is one of the foundation stones that is presumed upon all over the compiler. I mean I presume we have only characters, no spaces, only underscores and no strange characters.

If we have a number in the beginning of a string, or only numbers, things will most certainly go honorably wrong.

I can make a forked branch, and I can add some switches to make some provisions for this, then you will need to help me iron out the bugs :)

**Comment by TLWebdesign** [comment]
Wouldn't a quick check to see if it's all numbers or starts with a numbers you should force conversion, and if not, leave it alone? I have ran into difficulties with this auto conversion too.

**Comment by Llewellynvdm** [comment]
Good for us, I have isolated the name convention into [one function](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L2862), but also bad since the change of a name will trigger a database update in any project we are working on. So that is just a heads-up to what will follow.

So in the `getFieldName` we can do some tweaks to try and change the outcome of the current implementation. Going over the function you will realize that there are more at stake then one would naturally think :)

I added a new convention but left it un-active (t[o active we must manually change one value in the compiler](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L761)) so we can test it without causing a major fork or complication. If any of you have time to setup a test environment and run some test with that new convention with feedback... that will be great.

**Comment by TLWebdesign** [comment]
I can do that. Just like to know what exactly i should be testing / looking for. Would i just install JCB in clean enivornment and import my extension and then compile/install and see if front-end/back-end views give errors? or some other things to test?

**Comment by Llewellynvdm** [comment]
Yes that is more or less what is needed, but the component must of cource have fields with names that have numbers in it and that JCB use to convert to just characters an now it does not... so we can see what is the full outcome of that.

**Comment by Llewellynvdm** [comment]
What will help is git, if you could compile to a local git folder (using the old or default convention) then [change the compiler](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L761) and compile again, then use git diff to go over the changes... this will be the more clear review of the impact.

**Comment by Llewellynvdm** [comment]
I just did that with JCB, and very little changed, but that is due to the fact that JCB has not numbers in any of its fields, just in some notes. So it seems stable... but let me know.

**Comment by TLWebdesign** [comment]
Hmm i would have to learn how to that with git. never used it like that. i did install it on bitnami and uploaded my package in it. of course all fields are already renamed to text. When i try to add a number in the text field name like "overige1" after saving it reads overigeone instead of overige1. So it seems it's already converting way before compilation.

**Comment by TLWebdesign** [comment]
![Schermafbeelding 2019-06-18 om 15 34 28](https://user-images.githubusercontent.com/4402824/59688803-b8c20100-91de-11e9-97cf-8cb6faf68e8a.png)

**Comment by Llewellynvdm** [comment]
ha okay yet another tweak needed, I will add it. Yes I did force this point all over... give me a moment and I will push out that change also. It is in the field save method... I do some sanitation.

**Comment by marcodings** [comment]
So this [ line to change](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L144) 
When looking in github be aware that the line is truncated, scroll right for instructions ;)

**Comment by marcodings** [comment]
I did the "hack", compiled a component i'm working on, did the diff and found no difference.
Changed some fields to have numbers and the diff showed changes in all the expected places,

So all seems good atm

**Comment by Llewellynvdm** [comment]
That is great news... this means I can add the switch for those who want to have this option. I must say it was easier to do then I originally anticipated.

[Sermond Distributor](https://github.com/SermonDistributor/Joomla-3-Component) is one of the components and so also [Cost Benefit Projection Model](https://github.com/namibia/CBP-Joomla-3-Component) that should serve as the best trackers of the effect of changes to JCB (since they are making use of all areas in JCB). If you have those JCB packages, and can change a fields to now have a number in each of them, we may be able to confirm our combined results to be fully sure it is stable.

I will also run some test and get back to you.

**Comment by TLWebdesign** [comment]
Sorry for late answer. It's daddy's day to babysit on wednesday and we're in the middle of a move to our new home. I just took time to check with sermon distributor. Can confirm it works fine. Also checked database and that was updated as expected also.

**Comment by marcodings** [comment]
oops
![image](https://user-images.githubusercontent.com/3484222/59941184-df8d6b00-945c-11e9-8a39-8ffb0760d555.png)

**Comment by Llewellynvdm** [comment]
Yes we only _liberated_ name field from the number convertion, I have not widened it beyond that, so you will still see it in places... but it should not effect the code, or the intended outcome. Like that shown here are simply notes, and language strings.

Hmm we may want the language strings to still reflect the number, what do you think?

**Comment by marcodings** [comment]
Language strings should be the same as variables. No conversion, plain
digits ;)

**Comment by Llewellynvdm** [comment]
Okay I have pushed the full implementation into place, please test and let me know. You will see under the global options there is not a radio button called `Field Name Builder` and the following description:
> The default option only uses alphabetical characters and converts all numbers in field names to the English equivalent like 1 becomes one. Alphanumeric keeps the numbers unconverted unless it is at the beginning of the field name. Should you change this it will cause a database updates (during your next compilation) for all fields that has numbers in the name of the field. So it is really not a good idea to change this option every so often, you should rather select what you would like to use and keep it like that. All VDM/JCB components work on the Default option.

The language strings for the field names are also now not converted. :+1:

**Comment by marcodings** [comment]
Field types are still subject to number conversion
