### ISSUE TITLE
names for category fields

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#430]
jcb allow to use a custom field for categories, the field has a mandatory
"name" attribute

1) the naming is not honered, and regardless of the name set in the field, the name in the form is set to "catid"

2) when adding a second category field to a form with a unique name, this is also ignored.
moreover the name of the initial field is renamed to **catid_1** and the second field is named **catid_2**.
At this point the generated component fails to install as the database update tries to add a **catid_2** after column **catid_1**.
I have yet to look at the generated code what happened to the used "catid" variables that now should be referenced as "catid_1". I would be very much surprised if i would not run into problems in my bespoke code

**Comment by Llewellynvdm** [comment]
Due to auto integration with Joomla, this seems like a Joomla limitation.

So yes JCB forces the catid field name implementation (due to this limitation), and yes you can only have one category per/view, yet this is a limitation on the Joomla integration side. Specially in connection to the [history component](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/script.php#L928) and the [router](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/site/router.php#L79)

So to turn off this function is simple, but the implication is many broken conventions all the way down to the router and permissions... (as permissions in JCB are also mapped to the category) and well just a huge issue to not just keep to this basic rule. So unless Joomla has improved the integration that I do not know of, the reality is one item should only have one category, and that category field for best convention should always be called catid. Then it is true that you can use the multiple option on the category field (which allows you to add more then one category), but then the filter (in the list view) does not work, since it does not make provision for json/array of values.

So my advice is, should you need more filtering build your own types (admin view), kinds (admin view), or add tags. The category option is not designed to be used as something else as an category.

Why do you think articles can only be added to one category at a time :+1:

**Comment by marcodings** [comment]
JCB adds additional "behaviour" to all category fields.

I suggest to update the documentation/comments to reflect this nature and indicate that the **name** is of no consequence, nor is the **type**.

Regardless of what is put into the field form, in the xml
**name** => catid
**type** => category

I do not want to add multipe 'categories" behaviour to a single field.
In my project my first category field is the actual category for that admin view, so that is fine.

I want a second field that "only" gets me a **catid** from say another component by specifying the "extension". To this end i would need a second category field that, for lack of a beter description, is NOT linked into code generation.

My workaround sofar.
1) i created a bespoke fieldtype "mdicategory" that extends "category" and lives in mdicategory.php
i had mdicategory extend from JFormFieldCategory and not from JFormFieldList
2) in jcb i created a fieldtype "category plus" with **type** "mdicategory"
3) i added the field bases on (2) to the form, 
name=>**myCatId**
type => **category**

In xml i now get my own name
why JCB would ignore my fieldtype name illudes me

Suggestion: add a mdicategory type to JCB
Question: why does the fieldtype get "overwritten"

**Comment by Llewellynvdm** [comment]
Yea, you have got a point... the additional "behaviour" is a pain if you don't understand why, or how this is done. Basicly JCB has fail safe behaviour at times, when the developer want to do something that will not come out right... JCB ignores it, and avoids the breakage.... and that mostly when I know the error will only com up way down the line in testing long after the error was made.

I like your workaround, and that is really the best way... we can even add that to the fieldtypes globally as a option for all to do the same.

So on the one hand I should add better documentation... and I try to as I get time and you and other make suggestions.

On the other hand I have made a way for the community to improve the field types and its documentation for all. Basically what you do is:

- get a new blank JCB install (where you have not messed with the fieldtypes)
- Import the community JCB package called `FieldType Updater`
- Update the fieldtype documents to what you think will communicate the implementation best.
- Export the JCB pacakge of the `FieldType Updater` component again.
- Follow the instruction in[ this video](https://www.youtube.com/watch?v=zlhFyrCGWik&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=64&t=0s) to push the change upstream.
- You can also what [this video](https://www.youtube.com/watch?v=8FplwKKa708&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=63&t=0s) for more details.

This way all get to help improve the field types :+1: 

So anyone who then needs to update their fieldtypes to the latest versions and documentation, and field types available in JCB... will just import the `FieldType Updater` package. They must of course force the update during the import. So other who build new custom field types like you did, can push it out to all and help me help you with this option.

I will at some time bump a tutorial out on this, I mean how this new option of shipping field types works. It is not that new... all JCB packages basically ships everything down to the field types. So on import if the field types in the package is newer then those found locally it will update them. This is always been the case. I just now made a package that has all field types used in it, to make sure all field types are shipped in the JCB `FieldType Updater` package.

**Comment by marcodings** [comment]
Thank your for the suggestion, its humbling to see how much one does not know. I was not aware of the process possibility. 
I'm now testing my category field type, it has some additional "level" selections to filter on the nested depth, I'll show you on a next call ;)
