### ISSUE TITLE
Undefined variable: url in C:\xampp\htdocs\joomla\administrator\components\com_componentbuilder\controllers\compiler.php 106

### ISSUE THREAD

**Issue by waltraudharror** [vdm-io/Joomla-Component-Builder#440]
After downloading my remote site to a windows 10 box I am still fighting with the problem, that no component can be compiled 

I have me a clean installation with the same PHP version with xampp 

I have turned on the error log with php and geht the message
Undefined variable: url in 

"C:\xampp\htdocs\joomla\administrator\components\com_componentbuilder\controllers\compiler.php"

In the compiler Windows I receive
JFolder: :delete: Could not delete folder. Path: C:...
or
JFolder: :delete: Could not delete 
Folder::create: Could not create ...

### Steps to reproduce the issue
just compile any component

### System information (as much as possible)
- OS Name & Version: win10
- MySql Version: acutal
- Apache Version: acutal
- PHP Version: 7.219
- Joomla Version: 
- JCB Version: actual
- Browser: chrome, IE

**Comment by Llewellynvdm** [comment]
Try Firefox as the browser, then also please search over the forum and closed issues before opening a new one. Did you actually go read the last message of the last issue you opened?

You will see on the forum the [following post](https://groups.google.com/a/vdm.io/forum/#!topic/jcb/1BYIhVE6B1k)
They all seemed to get resolved with using Firefox to compile.

Then lastly I would encourage you to use Linux/Mac and Bitnami for your development and deployment environment for the best results with JCB/Joomla.

**Comment by Llewellynvdm** [comment]
Bitnami can also run on Windows... here [watch this tutorial](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=72).

**Comment by mwweb** [comment]
I'll throw out that you might also look into using the Joomlatools Vagrant Box. Vagrant is a Windows or Mac program that can be installed, and the vagrant box is a preconfigured vm essentially. I've been using the Joomlatools Vagrant Box for some time now, primarily due to issues with the JCB compile in a Windows environment, and it works great. 

Windows Subsystem for Linux (WSL) is another good up and comer that Microsoft has been working on, but the current version still has some issues, namely permissions issues, which i believe is being worked on for the next release. 

I would suggest you take a look at Joomlatools Vagrant: https://www.joomlatools.com/developer/tools/vagrant

**Comment by marcodings** [comment]
To me this sounds as a permissions problem where xamp user has no relevant permission for deletion of the files.
