### ISSUE TITLE
Multiple models in a joomla view and vue.js as library

### ISSUE THREAD

**Issue by Ninja-007** [vdm-io/Joomla-Component-Builder#447]
1. In Joomla, multiple models can be used in a view. How can it be done in JCB?
Basically I want to show and manage multiple lists.
2. How can be vue.js used as a library?

**Comment by peterpetrov** [comment]
Hello @Ninja-007 . There are many videos that have been created by the owner of that software. You can find them here:

https://github.com/vdm-io/Joomla-Component-Builder/wiki

All of your questions can be answered there. I suspect you might be looking for a quick answer but believe me taking the time to actually watch the tutorials pays off in the long run.

On another note that is not an issue with the software itself so it will be best if you have similar queries to post them into the forum. We are active there so any how-to questions can be posted there.

Forum:

https://groups.google.com/a/vdm.io/forum/?utm_medium=email&utm_source=footer#!forum/jcb

Regards,
Peter

**Comment by Ninja-007** [comment]
@peterpetrov Thanks for the reply.
I am going through the tutorials. But I could not find relevant tutorial. I am process of evaluating JCB for component development. 

Let me see the forum. :)

**Comment by Llewellynvdm** [comment]
The fastest way to find answers, if you do not have the time to watch all those boring tutorials is via a google search of the JCB wiki pages, like this: `site:https://github.com/vdm-io/Joomla-Component-Builder/wiki Adding dynamic Get`

![image](https://user-images.githubusercontent.com/5607939/61676354-dd3c5c00-acfb-11e9-9c07-91fd904d7401.png)

To get date from more then one module, instead of the dynamic get (which can pull data from multiple tables and across components) you can use the Joomla API, for which we made a [helper wrapper method called getModel](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L6117) which is added to all components build with JCB in their helper class.

**Comment by Llewellynvdm** [comment]
Then JCB has the option to add your own library, [watch this tutorial](https://github.com/vdm-io/Joomla-Component-Builder/wiki/049-The-New-Library-Manager-Area) and [this one](https://www.youtube.com/watch?v=joT8weuPcwU&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=68) for more help. So yes vue.js can be added very easy.

**Comment by Llewellynvdm** [comment]
I assume the issue is resolved, just comment here if you need more help with this :+1:
