### ISSUE TITLE
[bug] twice all filenames in xml install file

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#455]
Hello,

In a brand new installation (both Joomla v 3.9.10 and JCB Master Branch v2.9.21) the compiled xml install file has the filenames list set twice, both in site and admin folder.
The folders list are correct in both folders.

It seems it doesn't affect the installation at the moment, even on other sites.

**Comment by Llewellynvdm** [comment]
This has been fixed, like I said before, and is just not yet been patched to the master branch but will soon be. Please revert back to [this issue for any more comments](https://github.com/vdm-io/Joomla-Component-Builder/issues/454) and this [comment for the patch](https://github.com/vdm-io/Joomla-Component-Builder/issues/454#issuecomment-519562409), note the second code snippet, since I think you did not add that last time.

Just that you know I have push those [fixes to the staging branch](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/b_Structure.php#L1150).

I like to keep issues communication in one place, so even if I closed an issue with a commit... or other wise. You are welcome to comment on it again if you feel more should be said. So I am closing this issue, and ask that you communicate on the [original](https://github.com/vdm-io/Joomla-Component-Builder/issues/454) should you feel the need :+1:
