### ISSUE TITLE
Feature Request - Add Custom Code ID numbers to Custom Code Warning

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#459]
### Steps to reproduce the issue

Compile a component with custom code that has 'problems' (custom code that can't be added)

### Expected result

Include the ID # of the custom code entry (i.e. the Custom Codes screen/listing), to make it easier when tracking down custom code entries with problems

### Actual result

Presently displays only the file and the line number.

### Additional comments

Having the Custom Codes ID number would make it a bit easier to fix some of these issues.
(This isn't a 'critical' thing, but on some occasions it would be easier to just make the changes within the Custom Codes area.

**Comment by Llewellynvdm** [comment]
Please define what you mean by custom code. Since we have just improved JCB to include custom code from the GUI with all the details you need... and other custom code from the GUI (the initial implementation) actually does add an ID. So I am not sure I follow, can you give some screen shots so I can see what you are meaning.

**Comment by Llewellynvdm** [comment]
I just made this tutorial it should help you understand the subject a little more, let me know :+1: 
https://youtu.be/FEJ8WEbcTys

**Comment by cpaschen** [comment]
Sorry for not being more clear. (Maybe we should start calling it 'GUI Custom Code' vs 'IDS Custom Code' or something).
I was talking about the 'old' method - IDE Custom Code (originally created in the IDE - which is something I'm guessing that at least a few of us have if we have components created a while ago with JCB.
Here's a screen shot of the area I'm talking about:

![Compiler - IDECustomCodeProblem - Administration - 2019-08-16 10_26_36](https://user-images.githubusercontent.com/1929923/63178893-8d0d9c80-c010-11e9-9066-7709606b5c13.png)

It would be very helpful when this happens to just have the ID number to which this piece of IDE Custom Code is related to (from the Custom Code screen).
It would make it easier to locate and fix the issue.

**Comment by cpaschen** [comment]
Sorry, I didn't really mean JUST the ID number (the line number is important also). It would be great if this could be something like:

Custom code #3 could not be added to site/models/reviews_assignment.php please review the file at line 194 ...

**Comment by Llewellynvdm** [comment]
Okay, but the issue can not be resolved from the GUI only from the file... you have to open the file position the code at the right place remove the comments and recompile to fix the issue. There is no way to fix these issues from the GUI, so I still do not see how that could be helpful or am I missing something.

The message basically means we could not add it back since the code above it has changed too much. Be aware that adding the custom code placeholders can also cause this at times if code is added to close to each other in one file.

I can look to see if it will be easy to add the ID... but I really want to understand why you think going to the GUI will help you fix the issue.

**Comment by cpaschen** [comment]
The problem is, when there is a significant JCB change, the line number that is listed is significantly off from where the IDE Custom Code was originally added. If you have several IDE Custom Code items in the file, it can be hard to determine which one is the problem unless you go ahead and install and then see the commented out code.
Yes, it's possible to dig through, but you have to wait for that install to complete.
My thought was that it would just be a helpful piece of info and might save 1-2 min. on each error like this.
And for those of us who are still not up-to-speed on the newer GUI custom code add-ins (or in cases where we can't figure out where in JCB to add the needed code), each time JCB gets updated we have to try to track down all these breakages.
If you wanted to get REALLY fancy, it would be great if it could say "You really should move this code to the GUI in the SITE VIEW <VIEW NAME> ADD PHP (CUSTOM DOCUMENT SCRIPT) area".
That might help some of us slower guys get more up-to-speed :-) [Only half serious there]

Hopefully that explains why. And this should only be considered if it is easy to add to that comment area as hopefully the rest of us Custom Script Laggards will catch up soon to using the GUI methods.

**Comment by Llewellynvdm** [comment]
I have added the ID and a link to the custom code.

I also updated the comment a little to sort of point in the right direction of resolving those warnings.

If you have any more ideas how we can improve that painful path of fixing these issues let me know. I am think to make a little video to demonstrate what I think is the fastest best path. But I don't use that feature that much... so those of you who use the custom code approach more often must help me see.. what I may not have noticed.

I like to remove the fear of upgrade... really JCB and upgrades should be like the best day of the week :+1:
