### ISSUE TITLE
Library/Package Manager

### ISSUE THREAD

**Issue by ro-ot** [vdm-io/Joomla-Component-Builder#46]
Why can't we add a library/package manger to components, so that JCB would download and place libraries every time it compiles the component. Mainly from git repos on github, but also other open repos. Maybe later from [redmine](http://www.redmine.org/) private repos... 

This would be so cool... Who agrees?? I will code it in @Llewellynvdm

**Comment by Llewellynvdm** [comment]
This is a great idea, we can even move some of the local libraries of JCB, like [UIKIT](https://github.com/uikit/uikit), [FOOTABLE](https://github.com/Llewellynvdm/FooTable), and other to make use of this... 

Will be great if we add a new repeatable field to the Joomla_Component area that has a few options in relation to select a library... and a new Library area to add libraries for reuse in component.

OR what was your Idea @ro-ot

**Comment by ro-ot** [comment]
Sure, that can work, I was more focused on the actual back-end code of the compiler that does the work... the UI of JCB is up to you, if you could add a new branch with the UI area in place I will build that logic implementing the actual fetching and adding of these libraries.

I was thinking to use BASH for most of the work, but then this feature will only work for those on LINUX or MAC... or should it be all PHP?

**Comment by Llewellynvdm** [comment]
I would think as much as we can, we should stay in PHP so we can insure it works everywhere with as little issues as possible. If Joomla works the JCB should also just work on the same server. I know of users already running JCB on windows :-1: , that is why we had to change the line breaks... to `PHP_EOL`

Anyway PHP can do what BASH does just with heavier load on the server (but not for long since PHP7 is here)... so it can be done. That brings up another issue... start thinking of PHP7, we need to port JCB to work on PHP7 very soon. I will open an issue on this and see if someone would be willing to help.

**Comment by Llewellynvdm** [comment]
Hmm why not use [composer](https://github.com/vdm-io/composer)...

**Comment by ro-ot** [comment]
Let me look into this some more.

**Comment by Llewellynvdm** [comment]
Is anything happing here?
