### ISSUE TITLE
Automatic import of custom code during compilation in JCB failed

### ISSUE THREAD

**Issue by Goral64** [vdm-io/Joomla-Component-Builder#472]
### Steps to reproduce the issue
I added my own code (see accf01.png) to the code generated by JCB (see accf00.png).
accf00.png
![accf00](https://user-images.githubusercontent.com/4144852/64154591-7b5e2e80-ce31-11e9-931f-c01dd45ec349.png)
accf01.png
![accf01](https://user-images.githubusercontent.com/4144852/64154593-7b5e2e80-ce31-11e9-9ea8-8b1a2ff2e70e.png)

### Expected result
After compilation, I expected to receive the code I changed (see accf04.png).
accf04.png
![accf04](https://user-images.githubusercontent.com/4144852/64154596-7bf6c500-ce31-11e9-8876-56633db5cd08.png)

### Actual result
During compilation, JCB put my code in a different place (see accf03.png) instead of in the place I indicated (see accf02.png).
accf02.png
![accf02](https://user-images.githubusercontent.com/4144852/64154594-7b5e2e80-ce31-11e9-80c8-af289f665c89.png)
accf03.png
![accf03](https://user-images.githubusercontent.com/4144852/64154595-7b5e2e80-ce31-11e9-8e08-b2e2de5e857c.png)
I checked in Custom Code and there are correct lines in which my code is to be inserted (see accf05.png)
accf05.png
![accf05](https://user-images.githubusercontent.com/4144852/64154598-7bf6c500-ce31-11e9-8205-8458f5ab81db.png)

### System information (as much as possible)
- OS Name & Version: Windows 10 Pro 64b
- MySql Version: 5.5.54 (linux)
- Apache Version: 2.4.34 (xampp)
- PHP Version: 7.2.10 (xampp)
- Joomla Version: 3.9.11
- JCB Version: 2.10.1
- Browser: Firefox 68.0.2

**Comment by Llewellynvdm** [comment]
The line numbers are not what is used to add the code back, but the `Start Hast Target` and the `End Hash Target` which use a much more sophisticated method to identify the placement.

Those line numbers is what is used when we can't find the placement we place the code on those lines and escape the code and give you a warning to investigate. So normally the line numbers are never used.

You will see the `Start Hash Target` is `7__` that means we use 7 lines of code above the placement to create a fingerprint to target the start of the replacement. Then the `End Hash Target` has a `3__` which means we use 3 lines at the end of the replacement to target the beginning of the end of the replacement. So that when other code is added above the 7 lines or below the 3 end lines the code is still added correctly without any complication.

Yet this also means if you have a file with lots of repeated code that are **identical** you my find conflict, but this hardly ever happens. Yet in those cases you can position your replacement code in a way to insure the code above and below are still unique.

Hope this helps, let me know if you have more questions.

**Comment by Llewellynvdm** [comment]
To move existing replacement code, compile the component to place the code with placeholders. add the `<>` and move the placeholders up or down. This would help change the placement. I have not tested this but think it should work.

**Comment by Goral64** [comment]
Thank you for your help.
I chose the place and area of change more precisely and now the change was successful.
![accf06](https://user-images.githubusercontent.com/4144852/64160980-27594700-ce3d-11e9-9398-5e80abb00918.png)
