### ISSUE TITLE
Not able to set permission in JCB -> view (both admin and site)

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#473]
### Steps to reproduce the issue
JCB -> admin view -> permission tab -> change permission
JCB -> custom admin view -> permission tab -> change permission
JCB -> site view -> permission tab -> change permission

### Expected result
Permission switched

### Actual result
spinner icons show up and nothing happens, no matter how much time you wait (until 10 minutes it didn't happen anything)
![Schermata 2019-09-05 alle 14 58 07](https://user-images.githubusercontent.com/49115855/64344773-6929ef00-cfef-11e9-9857-bffabae651e3.png)

### System information (as much as possible)
- OS Name & Version: OSX Yosemite 10.10.5
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.9.11
- JCB Version: 2.10.1
- Browser: Firefox , Chrome, Safari

### Additional comments
I can switch permission in the backend of the installed component without problem, but it is out of JCB in this case

**Comment by Llewellynvdm** [comment]
Can you give me the information you see in the console... the errors?

This area is an ajax driven system of Joomla it self, and why it does not work is just beyond me... so if you can give me some error reports it will help.

What is important to note in terms of functionality... the item level permission can only make the access stricter not loser. So that means if globally the public can not access the item, you can not on item level give access.

The reason behind it is basicly admin has the most power, and therefore has the last say... not the lower levels they can only add more restrictions but not open restrictions that were set by admin.

So try restricting access instead and see if the issue continues.

**Comment by jcodewalker** [comment]
Here you are:

**Comment by oxido21** [comment]
Just press the save button in left corner, it will work

**Comment by jcodewalker** [comment]
Hello,

Great! thank you, it works. I don’t know why but.. works.

Best regards!
