### ISSUE TITLE
Strange error message - getBible global options

### ISSUE THREAD

**Issue by jonasborneland** [vdm-io/Joomla-Component-Builder#475]
### Steps to reproduce the issue
Go to `/administrator/index.phpoption=com_componentbuilder&view=import_joomla_components&target=smartPackage
`
### Expected result
Error with a clear description on where to put to access token.

### Actual result
Error with message:
You can add an access token to getBible global options to make authenticated requests. An access token with only public access will do.

### System information (as much as possible)
- OS Name & Version: windows 10
- MySql Version:  5.5.5-10.3.17-MariaDB-1:10.3.17+maria~bionic 
- Apache Version: 
- PHP Version: 7.2.22 
- Joomla Version: Joomla! 3.9.11 Stable [ Amani ] 13-August-2019 15:00 GMT 
- JCB Version:  2.10.1
- Browser: Edge / Chrome (tried both)

### Additional comments
What and where is "getBible global options" ? In other words, where do I add the access token? :)

**Comment by Llewellynvdm** [comment]
What package did you try to import? did you watch the tutorials on how to import a JCB package?

The error is weird since I don't think we have getBible linked to any package... well it could be a shared note that I mistakenly updated that is used in both JCB and getBible.

But lets start with what package you tried to import.

**Comment by Llewellynvdm** [comment]
O yes and before I forget... please use **Firefox** when working in JCB GUI.

I build JCB on Linux in Firefox just for my own use, but have since 2015 started sharing it with the larger Joomla community. Who has from time to time run into quarks due to my development environment. So for best experience try to get as close to my environment as is possible to you.

Here is a little video on using the [Bitnami stack](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=73&t=0s), which has become sort of the standard for JCB.

**Comment by jonasborneland** [comment]
I tried several. It’s the same getBible massage on them all :)
And yes I watched the tutorial, but this comes as soon as I open the import view






Venlig hilsen
Jonas Borneland

Phone: +45 60141440

**Comment by Llewellynvdm** [comment]
Do you have curl turned on?

Please send me a screen-shot of the error message.

**Comment by jonasborneland** [comment]
Yes, and It's on a shared host. But I don´t have the error on a bitnami stack I just installed. So that solved it :)

Anyways, where do I put the access token if I have to?

![image](https://user-images.githubusercontent.com/6105278/64590245-63ddf300-d3a7-11e9-9b67-bac03a33a162.png)

**Comment by Llewellynvdm** [comment]
For this area to work (import of JCB packages), it makes API calls to github. If you have other applications who also made calls from the same IP (if shared host - other clients on the same host) then github will reach its limit on free unofficial calls, and will start asking for a token, and that triggers this warning.

The error is also used in another component I build called [getBible](https://getbible.net) so I need to fix that message to be more JCB related (that is why I asked for a screenshot). At this time JCB does not have a place to add a token, since the amount of calls it makes is very low that we have hardly ever seen this error come up (well I have never seen it and I use JCB everyday). But I guess the time has come to add it in and give better instructions in the message. Everything for it is ready (back-end) we simple need to add it to the GUI.... so I will push it out on the next release.

I just when over the code and found where I should fix the message:
![image](https://user-images.githubusercontent.com/5607939/64596816-eb7e2e80-d3b4-11e9-8172-f6d2c4f4ec15.png)

So it is in a [helper method called](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L2475) `githubErrorHandeler` that is used in both JCB and getBible as you can see above.

For the future, the global options of any component is found at the top right corner in any of its list admin views. The button that says [options]
![image](https://user-images.githubusercontent.com/5607939/64597139-7a8b4680-d3b5-11e9-9b26-cb2d0efe756e.png)

So looking at the code you reached the API free limit on that shared host, so that error came up to have you add a token for which JCB at this time did not have a field... but will soon, with better message :+1:

**Comment by jonasborneland** [comment]
Okay perfect! That answer all my questions!
Thank you for taking your time to figure it out and help me.
