### ISSUE TITLE
Edit the "edit views" in JCB

### ISSUE THREAD

**Issue by jonasborneland** [vdm-io/Joomla-Component-Builder#477]
Is there a way to edit the edit views via JCB ?
If I edit the files directly on my FTP, they will be deleted when re-compiling the component.

If it dosent exist, I would suggest a tab like "Admin views" to edit the "Edit view" ? :)

**Comment by peterpetrov** [comment]
Hey Jonas,

there is no option to edit exactly the edit views. However there are plenty of options to manage them - add code to the model and controller some javascript options etc. It depends on what exactly you want to do with it. So if you could add more details regarding what do you need we could be able to point you in the right direction.

Regards,
Peter

**Comment by jonasborneland** [comment]
Okay, thanks @peterpetrov!
I wanted to make the save & close button redirect to the item you are editing. Can you give me a hint about where to put that code in JCB? :)

**Comment by peterpetrov** [comment]
Jonas,

I will give you my solution but I think you need to dig deeper on how Joomla works and how the joomla component file structure is and following how JCB compiles the code. Many of us have spent time learning about it and found own solutions. Also in the forum you could search for answers since a lot of your questions are duplicates in a way of the questions that were already answered.

So in that instance you need to add the code to the postSaveHook method. What that method does is executing actions after the item is saved to the database.

// get the application framework
$app = JFactory::getApplication();

//check if it is siteotherwise it will do it in both admin and site and one of them will fail
if ($app->isSite())
{
//assign the model params to variable
$item = $model->getItem();

// get the slug or id
$slug = $item->get('alias');

//Set the redirection
$this->redirect = "address-where-your-single-time-view-is/" . $slug ;
}


I hope this helps.

Peter

**Comment by jonasborneland** [comment]
Arhh okay. Thanks @peterpetrov! thats a big help.
I will keep that in mind for the next time :)

**Comment by jonasborneland** [comment]
@peterpetrov Where in JCB should i put the code? In the dynamic get?

**Comment by peterpetrov** [comment]
Come one Jason :) Be proactive. I have answered your question about 3 times where to put the code :)

Go to JCB -> Admin Views -> "The admin view in question" -> go to PHP tab -> find postSaveHook method and activate it -> put the code there. -> Save and close -> Recompile and install.

Peter

**Comment by jonasborneland** [comment]
Ohw sorry! I couldn´t find it. Thanks for the extra extra answer! Now it is complete and working. Thanks!! 😃
