### ISSUE TITLE
[Feature request] Custom folders not updated

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#479]
In Custom Component File & Folders, for files we have the option to not update the files.
Can we have the same for folders too? To upload folders (and their contents) only on installation so users can custmize some files which will be not overwrite.

**Comment by Llewellynvdm** [comment]
I think you did not understand what the do not update means. In terms of the JCB adding files, you have placeholders and renaming and the updating will update the actual file when adding it to the component with the JCB placeholders and custom-code placeholders and rename the file. But if set to not update, we just move the file into the component.

This means the updating has nothing to do with the actual install process of the Joomla component package into another or the same Joomla website.

Views, templates, and layouts (display) have an overriding concept build into Joomla, and you can Google around to find more info on that. So if your clients need override any of those, they can do it without hacking the core of your component.

Next the best way to give your end user the option to change files in your component and then this in turn gives them the option of some other kind of customization will be for them, since they are already on the file system, just rename the file, or better copy the file to an agreed name, which you can check if it exist and if not fall back on the default.

So this fall outside of the scope of new features as it can already be done very easily :+1: 

I am closing this issue, but you are welcome to let me know if you have anymore questions...
