### ISSUE TITLE
Site View > Dynamic Values displayed incorrectly.

### ISSUE THREAD

**Issue by hennysmafter** [vdm-io/Joomla-Component-Builder#480]
### Steps to reproduce the issue
Install the latest version of JCB and follow the first YouTube tutorial at 19 minutes into the video you are creating a Site View. Into the video it says by Dynamic Values:

```php
<?php echo $this->item->greeting; ?>
```
In the component however it says:
```php
<?php echo $this->item->greeting_greeting; ?>
```

I noticed this immediately but thought that this was just due to updates since the video was aired and I started the tutorial. So I just continued the tutorial. Until I came upon the 35 minute mark.

### Expected result
Here I expected to be able to click on a greeting in the site link and see just that greeting.

### Actual result
But the result was the error:
```
Notice: Undefined property: stdClass::$greeting_greeting in /.../components/com_hello_world/views/greet/tmpl/default.php on line 28
```

### System information (as much as possible)
- OS Name & Version: Win10 v1803 / 17134.1006
- PHP Version: 7.3.6
- MySql Version: 5.6.24
- Apache Version: 2.4.39 
- Joomla Version: 3.9.12
- JCB Version: 2.10.1
- Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)

### Additional comments
So I changed this `greeting_greeting` into just `greeting` at the site view and compiled again and now there is no error and everything works as expected.

I double checked all the screens from the tutorial with my own and everything was exactly the same so I really think that the `greeting_greeting` part is a bug and not something which is by my own doing. 

I would like to finish that I am just starting with this component but I am already loving it and seeing a lot of potential. Thank you very much for all the effort you have put in!

**Comment by Llewellynvdm** [comment]
I just imported the hello world tutorial into a blank new Joomla website as a JCB package and then opened that view... and behold it looks as expected.
![image](https://user-images.githubusercontent.com/5607939/66215446-d9499480-e6c3-11e9-9687-6b2606601a65.png)

So my advice is import the hello word package from the JCB package manger, and compare the dynamicGet setup with yours in more detail. I suspect that it has todo with the linked view being set as single, instead of multi or something like that.

To install the JCB hello world package watch this tutorial.

Yea I know the tutorials are a little old... but it works for the most part. My time has just become increasingly limited. So I can't for see me making new tutorials any time soon. I would hope someone with better tutorial making skill can at some time give it a go :+1: I would even be willing to pay someone to do it I suppose. Since JCB is getting more and more advanced by the day.

Let me know if you have any updates on this, enjoy!
