### ISSUE TITLE
How to get input values from a `view` and use it in custom PHP areas?

### ISSUE THREAD

**Issue by hennysmafter** [vdm-io/Joomla-Component-Builder#496]
Could you please make a video or tutorial about how to get input values from a `view` and use it in custom PHP areas.

For instance: I have an admin view with a textarea and a custom button. On clicking of the button it needs to email the textarea as body but for some reason nothing that I have tried works and I tried a lot of the suggestions found on the wide web.

The email part works as I have received plenty of emails after clicking the button it only never shows up with the value that is inside the textarea.

mail.xml
```
		<!-- [Fields 1411] Message Field. Type: Textarea. (joomla) -->
		<field
			type="textarea"
			name="message"
			label="COMPONENT_MAIL_MESSAGE_LABEL"
			rows="11"
			cols="10"
			description="COMPONENT_MAIL_MESSAGE_DESCRIPTION"
			class="text_area span12"
			filter="HTML"
			hint="COMPONENT_MAIL_MESSAGE_HINT"
		/>
```
The custom button target controller method is `sendMail` and below it inside PHP (Controller Methods)

```
function sendMail()
{
  // Check for request forgeries
  JSession::checkToken() or jexit(JText::_('JINVALID_TOKEN'));

  // Getting variables
  $id = $_GET['id'];

  // Testing variables
  $staffname = 'staff';
  $staff = 'staff@domain.eu';
  $username = 'testuser';
  $user = 'testuser@domain.eu';

  // Fetching the mail object
  $mailer = JFactory::getMailer();

  // Setting the sender
  //$config = JFactory::getConfig();
  $sender = array( $staff , $staffname );
  $mailer->setSender($sender);

  // Setting the receiver
  //$user = JFactory::getUser();
  //$recipient = $user->email;
  $recipient = $user;

  $mailer->addRecipient($recipient);

  // Creating the mail
  $test = 'GRABBING INPUTS';


  $body   = $test;
  $mailer->isHtml(true);
  $mailer->Encoding = 'base64';
  $mailer->setBody($body);

  // Sending the mail
  $send = $mailer->Send();
  if ( $send !== true ) {
    JFactory::getApplication()->enqueueMessage('<div class="mail-notice-details">Error sending email!</div>', 'warning');
    JFactory::getApplication()->redirect(JRoute::_('index.php?option=component&view=mail&layout=edit&id=' . $id, false));
  } else {
    JFactory::getApplication()->enqueueMessage('<div class="mail-notice-details">Mail sent</div>', 'notice');
    JFactory::getApplication()->redirect(JRoute::_('index.php?option=component&view=mail&layout=edit&id=' . $id, false));
  }
}

```

With the code as is above described I am receiving mails with `GRABBING INPUTS` as the body. This is obvious as that is what is hardcoded but of course, I need to get the content of the textarea to be the body. So I tried numerous ways to get this done but all failed. All methods have been placed inside the code overwriting this part: `  $test = 'GRABBING INPUTS';`

method1
```
$test = JFactory::getApplication()->input->get('message', null, 'string');
```

method2
```
$params = &JComponentHelper::getParams('component');
$paramValue = $params->get('message','default');
$test = $paramValue;
```

method3
```
$test = $_GET['message'];
```

method4
```
$test = $_POST['message'];
```

method5
```
$app = JFactory::getApplication();
$input = $app->input;
$test = $input->json->get(message);
```

method6
```
$app = JFactory::getApplication();
$input = $app->input;
$test = $input->get->get(message, default_value, raw);
```

method7
```
$app = JFactory::getApplication();
$input = $app->input;
$test = $input->post->get(message, default_value, raw);
```

`Some parts of the code have been replaced to not give away email addresses and the naming of certain items.`

Please let me know what I am doing wrong and/or what I need to adjust.

**Comment by peterpetrov** [comment]
Hello @hennysmafter ,

I would like to start with the fact this is not an issue with JCB itself but rather it is a query about how to work with it. Therefore you should direct such inquires to our forum here:

https://groups.google.com/a/vdm.io/forum/?utm_medium=email&utm_source=footer#!forum/jcb

Having said that there are a lot of tutorials in the YouTube channel and there are places where you can see how to use the Admin php sections and how to apply custom coding to them. You should start here:

https://www.youtube.com/watch?v=IQfsLYIeblk

Your next stop should be here:

https://www.youtube.com/watch?v=CdSKSCTzmRA&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&t=00h00m00s


Do you want to use your sendMail function on a list view or single item view? 

Have though if there is no data in the field how to handle it?

I will try to get an example out later tonight with the demo component in JCB.

Regards,
Peter

**Comment by peterpetrov** [comment]
OK, so your controller method lacks the data required. First you need to get the ID and then use the array as you need. Here is an example:


`function sendMail()
{
 // Check for request forgeries
  JSession::checkToken() or jexit(JText::_('JINVALID_TOKEN'));
  **$data  = $this->input->post->get('jform', array(), 'array');**

  $staffname = 'staff';
  $staff = 'staff@domain.eu';
  $username = 'testuser';
  $user = 'testuser@domain.eu';

  $mailer = JFactory::getMailer();
  $sender = array( $staff , $staffname );
  $mailer->setSender($sender);
  $recipient = $user;
  $mailer->addRecipient($recipient);
  $body   = $data['description']; // replace description with your field name

  $mailer->isHtml(true);
  $mailer->Encoding = 'base64';
  $mailer->setBody($body);
  $send = $mailer->Send();

if ( $send !== true ) {
    JFactory::getApplication()->enqueueMessage('<div class="mail-notice-details">Error sending email!</div>', 'warning');
	**JFactory::getApplication()->redirect(JRoute::_('index.php?option=' . $this->option . '&view=' . $this->context . '&layout=edit&id=' . $data['id'], false));**

	JFactory::getApplication()->redirect(JRoute::_(JUri::current(). $id, false));
  } else {
    JFactory::getApplication()->enqueueMessage('<div class="mail-notice-details">Mail sent</div>', 'notice');
	**JFactory::getApplication()->redirect(JRoute::_('index.php?option=' . $this->option . '&view=' . $this->context . '&layout=edit&id=' . $data['id'], false));**
  }
}

`


Please note the bolded sections. I have updated them with proper placeholders which makes it much easier to use them anywhere in the same manner.

Let me know if that helps.

Peter

**Comment by hennysmafter** [comment]
Hey @peterpetrov ,

First of all, you are completely right that this question should belong to the forum. 
And in regards to the tutorials, I did watch both of them and wherever possible I followed it to the T. 
I also created the Hello World component with JCB and that impressed me a lot but I can't remember seeing this:

```
$data  = $this->input->post->get('jform', array(), 'array'); 
```

And that one line of code made all the difference and I am very happy that you posted it! 
And not only posted you that line of code you also inserted it and more into my code and that is absolutely above and beyond!
Thank you so much for both your answers and the time you put into them.

I do however have a question though. 
Inside the `if ( $send !== true )` you redirect twice. Why is that?

**Comment by peterpetrov** [comment]
Hey, no worries :)

about the two lines  - i was experimenting and left the experiment there. So this line:

	JFactory::getApplication()->redirect(JRoute::_(JUri::current(). $id, false));


Is obsolete. Please ignore it.

Peter

**Comment by hennysmafter** [comment]
Okay, thank you I will. 
Once again thank you very much!

**Comment by hennysmafter** [comment]
@peterpetrov 

I got one more question about this:
```
$data  = $this->input->post->get('jform', array(), 'array'); 
```
What does the `$this` stand for?

The reason I am asking is that I used this code in another area of the admin view: PHP Tab > Add PHP (custom document script) *

And then it creates an error:
`Using $this when not in object context`

**Comment by peterpetrov** [comment]
Hello @hennysmafter , don't take this the wrong way but you definitely need to watch more and experiment more. Also i am not the best source to learn how MVC works. I could give you little bits and pieces but you have to push harder, read more and test much more.

Said that i have to say you need to watch more tutorials about JCB as well (i know i am getting boring with all that "more reading", "more watching" etc.) as our fearless leader and founder of the software has explained very well. Believe me when i tell you when i started with JCB i had very basic knowledge of how all that works and had to read, watch experiment, break and generally research how it works. I also had to read more code, more forums to get an understanding why it has been done this way. I also have a lot to learn and i plan to do it :)

One advice is to open the code of already working function and try to dissect and learn from it. My favorite PHP function is var_dump($whateveriwanttodump) and jexit().  So use them in all cases. That will show you what output comes in different variables and will help you understand in your own pace.

If you are looking to add some code to the PHP tab it means you need to apply it within the order of functions that are happening in the controller or the model parts. Every function has definition what kind of data and variable is coming into it and you should use that in your advantage. In your case you want to use the custom document script which is on the bottom of the view. You can do (again)

var_dump($this);
jexit(); 

and you will see what is the output. There is a difference between normal variable value and an object in PHP and within $this->input the "input" part is an object that doesn't exist in this particular function. There are other objects and you should explore them in order to understand. 

Also keep in mind that your main consideration have to be what exactly you are trying to achieve. That will definitely point you to the correct path.

Enough said. You should start dumping now ;)

Cheers.
Peter
