### ISSUE TITLE
New module generator issue

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#501]
### Steps to reproduce the issue
1. Make a new module
2. Give it a System Name and Name
3. Under default tmpl add: <h1>Agenda</h1>
4. Select a Custom gets
5. Save Module
6. Add module to component
7. Install module and display on screen

You will see:
/***[JCBGUI.joomla_module.default.2.$$$$]***/
Agenda
/***[/JCBGUI$$$$]***/ 

It seems that JCBGUI insert is not removed form the template. 

### Expected result
No JCBGUI -code

### Actual result
JCBGUI code is showed

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7.24
- Apache Version: Apache/2.4.35 (Win64) OpenSSL/1.1.1b PHP/7.2.19 
- PHP Version: 7.2.19
- Joomla Version: 3.9.14
- JCB Version: 2.10.9
- Browser: Firefox (latest)

**Comment by Llewellynvdm** [comment]
This code shows because you have `Add Custom Code Placeholders` turned on during compilation.


- at the compiler
![image](https://user-images.githubusercontent.com/5607939/71097849-6081b100-21b9-11ea-9e9e-736e36d5aab1.png)

- or at the component
![image](https://user-images.githubusercontent.com/5607939/71097909-7c855280-21b9-11ea-89fc-3c15b2217669.png)

if you turn these off the GUI placeholders will be dropped.

**Comment by Schrijvers123** [comment]
Thanks, indeed this in at the componemt it was still on.
