### ISSUE TITLE
Module builder: Twice the code in Module code

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#502]
### Steps to reproduce the issue
In the new module builder I see an unexpected behavour.
Add two custom gets and it will add twice the same code in the module. This will result in twice the output.

Removing one or more customgets add also code to the module code.

### Expected result
ONly one code in module code

### Actual result
Duplicated code in module code.

### System information (as much as possible)

    OS Name & Version: Windows 10
    MySql Version: 5.7.24
    Apache Version: Apache/2.4.35 (Win64) OpenSSL/1.1.1b PHP/7.2.19
    PHP Version: 7.2.19
    Joomla Version: 3.9.14
    JCB Version: 2.10.9
    Browser: Firefox (latest)

### Additional comments
![2019-12-18_16-19-17](https://user-images.githubusercontent.com/3889668/71099003-e0584d00-21b2-11ea-8351-22a448c3360e.png)

**Comment by Llewellynvdm** [comment]
Please check the console output when you make changes, so we can see what errors are found. Basically the JavaScript checks to see it the code is already set, and if it can't find it, adds it again. Since it is adding it more then once, it means something is preventing it from finding it.

You can look at the code that does the work over here, and give us your debugging feedback.
https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/forms/joomla_module.js#L590

The work around is to just remove the duplicates. Just know that in all my test it work as expected, and your experience can therefore not be duplicated on my side.

**Comment by Schrijvers123** [comment]
Hello Llewellynvdm,

No errors in console.log. See: https://vimeo.com/380279180

I will go debugging the code to see what is happening.

**Comment by Llewellynvdm** [comment]
Once you have more info on this let me know.
