### ISSUE TITLE
Custom code changes not being included on compile

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#504]
### Steps to reproduce the issue

Add custom code via the GUI (i.e. JCBGUI.admin_view.php_getform)
Compile (and install)
Edit the custom code in editor
Change the "." in the custom code comment to "<>"
re-compile (and install)

### Expected result

Changes are added

### Actual result

Changes are lost

### System information (as much as possible)
- OS Name & Version:  Win 10
- MySql Version: 5.7.19
- Apache Version: 2.4.38
- PHP Version: 7.2.14
- Joomla Version: 3.9.13
- JCB Version: 2.10.9
- Browser: Firefox Dev 72

### Additional comments

If changes are added to the GUI they are properly added to the code.

This was working fine prior to updating JCB to 2.10.9 
Is there some new setting somewhere that might be causing the code changes in the file to be ignored?

**Comment by Llewellynvdm** [comment]
Okay it seems like we have a bug, not sure how it could work before.

To fix this until the next update, just add this fix.

Change [line 7978](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L7978) in the get compiler class to:
```php
if (is_array($query) && count($query) >= 3)
```
Then all should work as expected.

**Comment by cpaschen** [comment]
This doesn't appear to have been merged into the 2.10.9 release.

Sorry, I'm not 'fluent' in github to be able to follow the merging process, I can just tell that this code change is not in 2.10.9.

**Comment by Llewellynvdm** [comment]
:) no worries I fully understand, I think it will be part of the next release version 2.11.x and up. The best way to see is to open the [compare view](https://github.com/vdm-io/Joomla-Component-Builder/compare/master...staging). The you can see if the commit that closed the issue is still in the list, if it is then it is not yet part of the current release, and in this case that is true.

![image](https://user-images.githubusercontent.com/5607939/74682714-85050400-51cf-11ea-92f7-4dda7cbccd85.png)

Sorry for the delay... I will move the assistant aside and try and get this update out ASAP. Then I can continue with the assistant after.

**Comment by Llewellynvdm** [comment]
Okay the next release is out, you should be good to go now :+1: let me know if you still have issues.
