### ISSUE TITLE
Feature Request: Allow auto code change inclusion for Admin Custom Tabs HTML

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#506]
### Steps to reproduce the issue

Add an Admin Custom Tab
Add code in the HTML

### Desired result

Code wrapped in a:
/***[JCBGUI.admin_view.php_....
/***[/JCBGUI$$$$]***/
block.

### Actual result
Code is just inserted into the edit.php view file

### System information (as much as possible)
- JCB Version:  2.10.9

### Additional comments
Not a critical feature, but sure make it easier (and more consistent) to have this area work like other code areas of the GUI.

**Comment by Llewellynvdm** [comment]
Yes that would be nice, I left those out originally since they are not like the rest of the JCBGUI fields being targeted. Since they are stored like other in subform/json fields, which means we can't just update a field like with the other, we will need to be able to target only part of the field inside the json object.

We have other more pressing features in the works, but I will add this on the todo list :+1:
