### ISSUE TITLE
site view model redirect fails

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#525]
### Steps to reproduce the issue
Dynamic get returning empty $data, so the following if statement is executed
```php
if (empty($data))
{
	$app = JFactory::getApplication();
	// If no data is found redirect to default page and show warning.
	$app->enqueueMessage(JText::_('COM_BPISSUESTRACKER_NOT_FOUND_OR_ACCESS_DENIED'), 'warning');
	$app->redirect(JRoute::_('index.php?option=com_bpissuestracker&view=projects'));
	return false;
}
```

### Expected result
Succesfully redirected to the project view

### Actual result
A browser white page with the message "This page does not redirect in a correct way. Too many redirects." and not redirection.

### System information (as much as possible)
- OS Name & Version: OSX Yosemite 10.10.5
- MySql Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $ 
- Apache Version: Apache/2.4.16 (Unix) PHP/7.2.7
- PHP Version: 7.2.7
- Joomla Version: Joomla! 3.9.15
- JCB Version: 2.10.11
- Browser: Firefox, Opera, Chrome

### Additional comments
Now I really need to fix this, either to have an option to add or not that routine by default by JCB or to have it working.
The problem is made by JRoute. If I edit the if statement to:
```php
if (empty($data))
{
	$app = JFactory::getApplication();
	// If no data is found redirect to default page and show warning.
	$app->enqueueMessage(JText::_('COM_BPISSUESTRACKER_NOT_FOUND_OR_ACCESS_DENIED'), 'warning');
	$app->redirect('index.php?option=com_bpissuestracker&view=projects');
	return false;
}
```
it works, but obviously I loose the routing.

**Comment by Llewellynvdm** [comment]
I do not think the problem is `JRoute` I think there is another problem, either you have not set the permissions correctly, or you do not have a public view.

The redirections must end at a view that is fully accessible to a public visitor. So you settings most look like this:
![image](https://user-images.githubusercontent.com/5607939/75488524-2c94ea00-59b9-11ea-9313-3c9cec7737df.png)
So you see that they are both public/default access. Should you not want that, then at-least one should be, and that should be the default site view. Like this:
![image](https://user-images.githubusercontent.com/5607939/75488632-6534c380-59b9-11ea-90ae-ab88f6177fa9.png)

**Comment by jcodewalker** [comment]
Thanks for your reply.
As I want to fully understand how I can avoid this issue I’m working with a very basic component which has not access control at all.


Anyway, your answer given me the direction to dig in:
first of all, working in a local machine I’ve this SEO setting:

Now, if there is an ID in the navigation bar (#5 in this pic):

Route works as expected.

If the ID is missing:


JRoute fails.

I sometimes need to list all the items if a specific ID is not found… or (if this is not possible) at least let it redirect correctly.

Any hint for a workaround? 

Thanks in advance!

**Comment by Llewellynvdm** [comment]
You can build a list view like I explain in the [Hello World](https://www.youtube.com/watch?v=IQfsLYIeblk&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=45) tutorial.
