### ISSUE TITLE
Datetime field: Translate format

### ISSUE THREAD

**Issue by dyvel** [vdm-io/Joomla-Component-Builder#526]
### Steps to reproduce the issue
If a datetime field type has param translateformat set to true, then I'm unable to save the date time to the database. 

When I use the calendar/datepicker the field in my case, is translated to e.g. 19-03-2020 17:26:01. 
The database normally expects a format like YYYY-MM-DD 00:00:00 for datetime fields.

Could this be the reason?

I'm using the latest JCB 2.10.11

**Comment by Llewellynvdm** [comment]
The datatime field is a tricky field, since saving it to the DB require understanding of the SQL format surrounding the fields settings selected.

So the match up of the field to the DB is something you must line up correctly. This means that it is really not a JCB issue, but a settings issue.

That being said, take a look at the core of Joomla and how they deal with these fields, and try to follow what they do. Lookup the correct datetime format, and set the field accordingly.

Then lastly since JCB just builds the XML that is used by Joomla to build the fields, and JCB really does no house cleaning when saving the field, you may want to look at how the core components deal with that, and if any house cleaning is needed. Should this be the case, then let me know and we can try and improve this... but as far as I remember this field just works.

**Comment by dyvel** [comment]
Thank you for the very informative answer. If I understand correct, this is more a case of expectations, where I thought it would "just work" out of the box, but reality is more like the file field type, that requires a bit of effort to get working. Right? 

But the more I learn about JCB, the more I get to appreciate the tool. It's amazing how powerful it is, and I've only scratched the surface.
