### ISSUE TITLE
Upload files from within repeatable/subform field

### ISSUE THREAD

**Issue by dyvel** [vdm-io/Joomla-Component-Builder#527]
### Steps to reproduce the issue
Please see this video, explaining my issue and how to reproduce it:
https://drive.google.com/file/d/1xdPA3smKMt43F-PGl2hIe_3JQhFnTTLo/view?usp=sharing

Also worth noticing: The file field type worked fine before I used it in a repeatable field. By adding it to the repeatable field, the files are no longer uploading to the server.

I suspect this to be a code issue, with the file field not coded to operate this way, rather than a JCB issue, but thought I would hear your opinion?

**Comment by Llewellynvdm** [comment]
Repeatable fields are depreciated in Joomla 4 so I would suggest using subforms instead.

Let me know if this resolved the issue for you.

**Comment by dyvel** [comment]
I've tried with subforms just now, but still no cigar :-) 

In the database, I see the item stored like this: {"attachments0":{"attachment_title":"test"}} - the file itself is not uploaded, and I guess, therefore not added to the database.

**Comment by Llewellynvdm** [comment]
Sorry just watched you video, my bad.... you will need to adapt the PHP to dig into the repeatable field.

So since you are new to PHP, or so it seems. I would suggest first get the field to work outside of the subform, [exactly as demonstrated in the tutorials](https://github.com/vdm-io/Joomla-Component-Builder/wiki#how-to-use-the-file-field-type-to-upload-a-file-in-jcb).

Then to upload multiple files, I would not use the repeatable/subform field. Rather use [this method](https://github.com/vdm-io/Joomla-Component-Builder/wiki#drag-and-drop-upload-functionality-in-jcb) with a few small tweaks.

Once you are at this step let me know, and I will help you change the field to allow for multiple uploads.

To see this uploader in action checkout the member-manager ([JCB package](https://github.com/vdm-io/JCB-Community-Packages) and the [Joomla package](https://github.com/vdm-io/Joomla-Members-Manager))
