### ISSUE TITLE
Allow output note or none db fields in admin list view

### ISSUE THREAD

**Issue by oriolun** [vdm-io/Joomla-Component-Builder#536]
### Steps to reproduce the issue
Create note or none db field.
Add it to admin list view in linked fields section.
Compile.

### Expected result
New columns in items list view

### Actual result
No new columns

### Additional comments
It will be very helpfull to ouput note or some none db fields in admin list view without creating new columns in database or custom list view. 
![screenshot-95 214 62 67-2020 03 22-15_10_37](https://user-images.githubusercontent.com/47156894/77249339-5ad0b700-6c51-11ea-8a60-a886bda48962.png)

**Comment by Llewellynvdm** [comment]
You should do that with the relationship builder, by defaut JCB will not allow none DB fields.

But you can add it with the relationship builder easy.
![image](https://user-images.githubusercontent.com/5607939/77250413-856e4000-6c50-11ea-9703-00f457d91734.png)

Since you can select a field in your case the one marked in red, and then just add custom html to show after the field:
![image](https://user-images.githubusercontent.com/5607939/77250485-f01f7b80-6c50-11ea-95ea-9694681c6306.png)

This is your best choice.

**Comment by oriolun** [comment]
No, it doesn't seem to be a best choice.
Relations means using existing db field in existing column. I don't need to modify existing column. I need to add a new one.

**Comment by Llewellynvdm** [comment]
The answer is still **no**, JCB does not allow none database values in the list view, and there are some real serious reasons for that, which I do not now have the time to explain.

But you are welcome to look at the compiler and see for your self why.

So take my advice to use the relationship area, or don't that is up to you. Since the only other way is with custom code which is outside the scope of the github issue area, for that kind of help [please use the forum](https://vdm.bz/jcb-forum).

**Comment by oriolun** [comment]
Very strange. There are a lot of cases when we need to add some system fields like created or user id, etc, custom code to the list view with only one new column. Creating hole custom view or overriding list template for the one column - is, emmm, a bit strange.

So for those who interrested to solve this problem without a mess in a database, here is a simple solution:
1. Add twice any new db field in a list view or create two or more diff fields with the same name.
2. Compile. No columns will be added to the db, but now you have two new columns in a list view (see pic), that can be edited in php getItems after all section.
3. Enjoy.
![screenshot-95 214 62 67-2020 03 22-18_08_18](https://user-images.githubusercontent.com/47156894/77252948-62e82100-6c68-11ea-8099-3e1d40478c7c.png)

**Comment by Llewellynvdm** [comment]
Looks like you did not understand my first reply. Whatever works for you man... what do I know.
