### ISSUE TITLE
Cannot load boilerplate in localhost environment

### ISSUE THREAD

**Issue by ManfredHuebner** [vdm-io/Joomla-Component-Builder#538]
### Steps to reproduce the issue
Try to get the plugin boilerplate on my XAMPP localhost environment

### Expected result
Methods and properties should be installed

### Actual result
Only plugin groups will be installed. 
### System information (as much as possible)
- OS Name & Version: XAMPP localhost
- MySql Version: 5.7
- Apache Version: 
- PHP Version: 7.3
- Joomla Version: 3.9.16
- JCB Version: 2.10.13
- Browser: Firefox

### Additional comments
Also, tried to export methods and properties from my server environment (where boilerplate could be loaded) but after import the asset id got mixed up and properties and methods are associated with the wrong plugin groups.

**Comment by Llewellynvdm** [comment]
Okay I am only working in localhost environment, so I think this is a local limitation in your setup, and not JCB related.
Please check that your local environment is the same as your host environment when it comes to PHP, and Apache.

**Comment by ManfredHuebner** [comment]
Any idea what module might be missing in Apache or PHP? As far as I can see, there should be no noticeable difference...

**Comment by ManfredHuebner** [comment]
And why didn't export / import not work (worked but wrong asset id links)

**Comment by Llewellynvdm** [comment]
> Any idea what module might be missing in Apache or PHP? As far as I can see, there should be no noticeable difference...

This you will need to check yourself....

**Comment by Llewellynvdm** [comment]
> And why does export / import not work (worked but wrong asset id links)

This could be memory limitations just because of your local desktop/laptop. I am working in a 16G memory environment. This has always been an issue, and to change this is very hard when keeping everything local.

**Comment by Llewellynvdm** [comment]
> And why does export / import not work (worked but wrong asset id links)

This could be a bug, what are you trying to import, and in what version are you. I have not been testing that area in a while.

**Comment by ManfredHuebner** [comment]
> 
> 
> > And why does export / import not work (worked but wrong asset id links)
> 
> This could be memory limitations just because of your local desktop/laptop. I am working in a 16G memory environment. This has always been an issue, and to change this is very hard when keeping everything local.

My machine as 32GB of memory ... all php modules like my web server.

**Comment by ManfredHuebner** [comment]
> 
> 
> > And why does export / import not work (worked but wrong asset id links)
> 
> This could be a bug, what are you trying to import, and in what version are you. I have not been testing that area in a while.

I am export from JCB 2.10.13 and import it in JCB 2.10.13

**Comment by Llewellynvdm** [comment]
@ManfredHuebner where is this issue status. I have not been able to reproduce this issue as yet. If this is still not resolved, please give me some screenshots of the process and the errors so we can try to seem more clearly what the real issue is.

Just that you know... I export/back-up all my JCB component via the JCB package system, and restore them all into other new system without any errors or ID mismatching or lose. I have been doing that for years... and I have never had any issues. Which is weird actually since you are not the only one who has had a challenge in this area. But it does give me the idea that it is environment related.

But anyway... we are planning to move to the GUID method path... we added the GUID many versions ago as you can remember... and I have been waiting to finally more the JCB package export and import over to this method. Since we will then not have the need of this extremely complicated search to identify items and remap all ID's (yes we will still remap ID's) but with far more accuracy.

So let me know what the status is on this issue at this time. I have improved that area in the last few releases, but nothing major. 

The new release v2.12.2 will be the first step towards Joomla4 since it will have the new filtering system added :+1:
