### ISSUE TITLE
Cannot compile Demo component

### ISSUE THREAD

**Issue by grantg182** [vdm-io/Joomla-Component-Builder#543]
### Steps to reproduce the issue
Install downloaded JCB github component. Attempt to compile "Demo" component.

### Expected result
Demo component gets compiled.

### Actual result
Catchable fatal error: Argument 2 passed to Get::setLangPlaceholders() must be an instance of int, integer given, called in /htdocs/administrator/components/com_componentbuilder/helpers/compiler/f_Infusion.php on line 2255 and defined in htdocs/administrator/components/com_componentbuilder/helpers/compiler/a_Get.php on line 7386

### System information (as much as possible)
- OS Name & Version: XAMPP on OSX
- MySql Version: 5.0.11
- Apache Version: 2.4.23
- PHP Version: 5.6.24
- Joomla Version: 3.9.8
- JCB Version:  2.11.0
- Browser: Chrome 81

### Additional comments
Unable to find anybody else with this issue...

**Comment by grantg182** [comment]
We can close this issue; found that the scalar type `int` found in /administrator/components/com_componentbuilder/helpers/compiler/a_Get.php for the `setLangPlaceholders` function can only work from php7.0+. The XAMPP version I am using (not Xampp-VM) only has php 5.6; hence the fatal error. In the meantime, I have removed the `int` declaration on this function param and all is well thus far.

In saying that...I don't see environment requirements defined anywhere for this project?

**Comment by Llewellynvdm** [comment]
Okay I understand, yes there is no official environment requirements defined, because I have been pushing the use of [Bitnami (docker) environment ](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=73&t=0s) which is what I use for my offline development environment.

But you we should setup something more official I suppose. I have shared some of my development setup over the years in the issue threads here on GitHub. But don't think it is easy to find.
