### ISSUE TITLE
FooTable -> Dynamic... is not dynamic.

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#544]
### Steps to reproduce the issue
Set fooTable to Dynamic in Lib & Helpers component setting tab.
Include a view in another view

Works fine when explicitly set to either fooTable-v2 or fooTable-v3

### Expected result
fooTable-v2 folder installed accordingly with the include files command

### Actual result
looks for not existings files in footable-v2 folder (in media folder) and generates errors for not found files (look in terminal panel of your browser), because the folder doesn't exist nor it is listed in the componente xml manifest file.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
The dynamic feature of the footable include, allows for the footable to be added only if it is linked to a custom_admin_view or a site_view:
![image](https://user-images.githubusercontent.com/5607939/80800789-abb9c080-8baa-11ea-9332-1c2280c1cbb3.png)
Like This:
![image](https://user-images.githubusercontent.com/5607939/80800810-ba07dc80-8baa-11ea-9cbb-aae24784468c.png)

So when you say with the "include files command" I take that as meaning when you add the code manually to your view. Check the above option and let me know if the issue continues.

**Comment by jcodewalker** [comment]
Hello,
Thanks for your fast reply, even today!

I think we are on different pages..
First of all,  I'm speaking about admin side, using JCB built-in view-in-view.

As soon as you add a view in another view (admin side) JCB add "include fooTable files" in setDocument method of the parent view, only it doesn't add any fooTable folder in media folder, so those includes generate error because those files are missing (obviously). All of this with the fooTable library setting to "Dynamic" (see attached image).
It works fine if I set it to either v2 or v3.
![Schermata 2020-05-01 alle 13 23 30](https://user-images.githubusercontent.com/49115855/80802274-36042380-8baf-11ea-9c65-1b459d2fbcaa.png)

I hope this is a bit more clear.

**Comment by Llewellynvdm** [comment]
The dynamic option falls back to the site-view linkages, so if you have it set to dynamic, you must like it to a site view to get it added to the project. Selecting the actual library in the component, will force it to be added to the project, but not to a site_view ( so you can include it manually as you like). Yet adding it to a site view will add to the site view and to the project.

This feature acts this way due to a number of improvements to JCB over the years. We did not have the option original to add the libraries to a site_view, you had to do it all manually. I then added the site_view implementation as an improvement, but did not remove the option to globally force the files to be added to the project, since it excised already, and many are using it that way.

That means working with libraries from the site_view linkages is the newer and better option. The only improvement I can see that still needs to happen, is the ability to link libraries to admin_view as we are doing in the site_view. Other then that I can't see us making any more changes :+1: here.
