### ISSUE TITLE
Feature request - Custom code manually repositioning

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#545]
### Steps to reproduce the issue
set two different replaced custom code in the same file (one php replace and one html replace in my case but I think this doesn't matter)
Change something in the first replaced block, the second block can't be added because something is changed above...

### Expected result
Still be able to auto-repositioning the second block (as there are che comment referring #id blocks) or at least set only the warning message and include the block following the position rows values. So, updating the position rows we can manually reposition the block.

### Actual result
adjusting the position rows in the second block, the custom code is set in the proper position but it is commented and the original block is added below.
Why?
Is there a way to bypass it and have only the warning message?

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
When you add custom code closer than 10 lines to each other, you are encouraged to combine them into one block. Since the custom code engine uses between 8 to 4 lines depending on the custom code engine search algorithm to generate a finger print to add the code back. The engine does not use the line number as it can change so rapidly. There is no workaround for this, so either combine the code into one block, or accept the pain that comes  if you change the above code block. Sorry!
