### ISSUE TITLE
localisation of calendar time not correct in list view

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#555]
### Steps to reproduce the issue
Create a calendar field in an admin view.
Add the field to both the admin list view and the detail view.

Set global configuration to london or not UTC time zone.

Pick a time in the detail view and click save and close

The time shown in the list view will be UTC.  If you go back to the detail view it will be the original picked time.

So currently london is UTC +1 hour to cope with daylight saving.

You could pick a time in detail view of 15:08:00
and it will show in the admin list view as 14:08:00
### Expected result

time to match in list and admin view

### Actual result

doesn't take account of time zone (only in list view)

### System information (as much as possible)
- OS Name & Version: CentOS Linux 7.8.2003 (Core)
- MySql Version: 5.5.65
- Apache Version: 2.4.6
- PHP Version: 7.3.20
- Joomla Version: 3.9.18 (doesn't work with earlier versions either)
- JCB Version: 2.11.0
- Browser: Firefox, Chrome, Edge etc

**Comment by Llewellynvdm** [comment]
This seems to be a serious issue actually, and my silence has only been due to me contemplating a solution. I will see when I have time to investigate how Joomla manages this in the content component, since they also has date field in the list view. Once I have done that I will revert with an answer, if you get to look at it before me, let me know what you found.

**Comment by TLWebdesign** [comment]
I noticed this issue too. I found this in the default.php of the listview of com_content:

echo $date > 0 ? JHtml::_('date', $date, JText::_('DATE_FORMAT_LC4')). : '-';

i tried it on my own component in default_body.php and it translates the date wrongly because it doesn't take into account the 3rd parameter which is $tz. 

https://api.joomla.org/cms-3/classes/Joomla.CMS.HTML.HTMLHelper.html#method_date

Adding true or false after the date format according to the field settings user_utc (true) or server_utc false made it work perfectly in my component. 

What JCB needs to do is check the field settings to see if showtime = "true" and use the correct DATE_FORMAT_LC4 for no time and DATE_FORMAT_LC6 for showtime true. Or maybe you could use the format attribute of the field. There are some things to consider like translateFormat attribute. Joomla has this hard coded since there is no variety here in joomla.

**Comment by TLWebdesign** [comment]
@Llewellynvdm Where in the compiler would this have to be changed? I tried looking for it but came up short. 

Also in that part do we have the form field info available? 

Kind regards,

Tom

**Comment by Llewellynvdm** [comment]
You see @TLWebdesign JCB does not touch the date field at all, and that is why you can't find it.

So we will need to add some code to the compiler instead. I have not done this for a few reasons, the most serious one is the fact that adding a fix to this issue will affect all date fields in all components build, and so I don't want to just try this or that. I need to be absolutely sure it will solve all use cases.

That said, did you know that the **fields relations** area allows you to override the field behavior in the model, and the view. So this code you have given above can be added in the field relations area and fix the issue completely for you.

Here is picture of the setup:
![image](https://user-images.githubusercontent.com/5607939/86647078-0d017400-bfe0-11ea-9975-fa991ee8139f.png)

So the above code will display your **date field** correctly :+1:

**Comment by TLWebdesign** [comment]
Can i create a relation without a join field? I always figured it needed a join field. OMG i can't believe i never tried it without a join field! 

Of course that would work. Guess we should just document it somewhere so people know about this. 
I suggest we should make this improvement for J4 compiler instead of the current J3 version. That seems like a good time to do B/C improvements anyway.

I was not trying to find where the date is changed. Just where that view file is being generated. But i just don't know enough about the compiler.
