### ISSUE TITLE
Admin View Fields selection - descriptions should be in tooltips

### ISSUE THREAD

**Issue by Sophist-UK** [vdm-io/Joomla-Component-Builder#557]
### Steps to reproduce the issue
Open the fields chooser from Admin View. .

### Expected result
The form descriptions should be shown in a tooltip.

### Actual result
The header row shows the label with the description below.

### Additional comments
I spent some time trying to work out why form xml description=something normally comes as a tooltip but for this form it comes in the header row, and I cannot work out why.

If someone can point me in the right direction I would be happy to submit a PR with a fix.

**Comment by Llewellynvdm** [comment]
Please give me some screenshots to explain...

**Comment by Sophist-UK** [comment]
Text circled should be in a tooltip rather than being displayed. (Also, I thought this should be in a modal popup iframe but instead it is navigated to by the main window.)

![image](https://user-images.githubusercontent.com/3001893/81740428-3f3d9c00-949d-11ea-9db6-01548b0735b6.png)

**Comment by Llewellynvdm** [comment]
Okay, ya that is how Joomla does it. JCB is just building the XML, Joomla builds the form, so to improve this we must improve Joomla. The package JCB generates is where JCB ends, remember that, since it will help you see where JCB ends and Joomla begins.

JCB is really just building a native Joomla component and Joomla makes it work via its own internal API, or classes. JCB is not responsible for how the subforms are rendered, we are trying to stay out of the way of Joomla as far as we can, meaning not to change Joomla and create our own world in the world of Joomla. No we are trying to blend in with Joomla so much that you can't even see the difference between native Joomla components like the Article Manager and components build with JCB. Well lets say that is the aim, yet since Joomla has many more developers, I am behind at some areas, but we will get there.

I am going to close this issue, since we can't make changes to the Joomla core in this repository, for that you must got to https://github.com/joomla/joomla-cms read over their contribution laws and stuff and make a pull request there to change the subform implementation.

**Comment by Llewellynvdm** [comment]
Oops then I forgot and important part, yon can override the default template that renders the subform in Joomla. Take a look at the sub branch of JCB called the [assistant](https://github.com/vdm-io/Joomla-Component-Builder/blob/assistant/admin/views/assistant/view.html.php#L77) where I am demonstrating this overriding options, that can already be done in JCB.

IF you need more help to understand this, let me know and I can make a quick tutorial to explain.

**Comment by Sophist-UK** [comment]
Yup - I understand that Joomla builds the form, but doesn't it use view templates and layouts to do it?

Is there a view template for the header row of the table? And if there is, can't we tweak it to put these into tooltips?

**Comment by Sophist-UK** [comment]
The example code in the assistant seems like a lot of code to achieve something that is not so important.
