### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bokoth** [vdm-io/Joomla-Component-Builder#566]
### Steps to reproduce the issue
Set up a local installation of Joomla 3.9.16
Attempt to install zipfile JCB_v2.11.2.zip

### Expected result
Component is installed

### Actual result
```
Warning
JInstaller: :Install: Error SQL Error on rename of './startupdb/#__assets' to './startupdb/#sql2-1-5f9' (errno: 168 "Unknown (generic) error from engine")
Extension Install: SQL error processing query: DB function failed with error number 1025
Error on rename of './startupdb/#__assets' to './startupdb/#sql2-1-5f9' (errno: 168 "Unknown (generic) error from engine")
SQL =
ALTER TABLE `#__assets` CHANGE `rules` `rules` MEDIUMTEXT NOT NULL COMMENT 'JSON encoded access control.';
```

### System information (as much as possible)
- OS Name & Version: Linux eec26637f755 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64
- MySql Version: 5.5.5-10.4.12-MariaDB-1:10.4.12+maria~bionic
- Apache Version: Apache/2.4.38 (Debian)
- PHP Version: 7.4.3
- Joomla Version: 3.9.16
- JCB Version: 
- Browser: brave with shields (script blockers) down

### Additional comments
same thing happens when I try to install directly from within Joomla backend admin extension installer

**Comment by Llewellynvdm** [comment]
Okay that error seems related to a script that has been in JCB for many years now... so there must be something else wrong here.

You can test it, download JCB as a zip, then unzip the package, and go to the [/admin/sql/install.mysql.utf8.sql](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/sql/install.mysql.utf8.sql#L2431) and remove those last two queries from the file.

So remove these and save the file and zip the package back up and install.
```sql
--
-- Always insure this column rules is large enough for all the access control values.
--
ALTER TABLE `#__assets` CHANGE `rules` `rules` MEDIUMTEXT NOT NULL COMMENT 'JSON encoded access control.';

--
-- Always insure this column name is large enough for long component and view names.
--
ALTER TABLE `#__assets` CHANGE `name` `name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The unique name for the asset.';
```
If this works then there could be a database mismatch in your setup, since those lines has been in JCB for a very long time. See most component use large permissions, and those fields are to small, so we enlarge them by default for everyone.

**Comment by bokoth** [comment]
thanks for the prompt response, I will retest with that in mind
