### ISSUE TITLE
Module Builder Issues

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#567]
### Steps to reproduce the issue
Create a new module. Set the system name and version. Compile and install.

### Expected result
In my module, I set version as 3.3.0,, and the version listed should be @version	3.3.0.

### Actual result
When the module compiles, it uses the component version that I have (3.7.0), and not the version that I set in the module, resulting in the comments showing @version 3.7.0, instead of @version 3.3.0.

### System information (as much as possible)
- OS Name & Version: CentOS 7.8
- MySql Version: MariaDB 10.3
- Apache Version: 2.4
- PHP Version: 7.3
- Joomla Version: 3.9.19
- JCB Version: 2.11.2
- Browser: Chrome

**Comment by Llewellynvdm** [comment]
I will take a look, but this seems strange.

**Comment by Llewellynvdm** [comment]
Ahaa I get it now, the licensing template is set via the component at this point, so the component version is used. To change this will take same serious work around. Best option is to drop the version from the main header and add versions to the function comments instead.

When I first ready you post, I missed the fact that you where speaking about the comments "code comments", since the correct version is used in the XML, and what gets shown in Joomla. Just the header Licensing notice that gets ported from the component at this time.
