### ISSUE TITLE
hidden field default value always set automatically to 1 (ignoring the setting)

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#573]
### Steps to reproduce the issue
create a hidden field, set a default value to it, save
add the hidden field to you component

### Expected result
the hidden field rendered with preset default value

### Actual result
hidden field rendered with 1 as default value

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.11.2
- Browser:

**Comment by Llewellynvdm** [comment]
What database setting does this hidden field have?

**Comment by jcodewalker** [comment]
varchar 256
default value null

**Comment by Llewellynvdm** [comment]
I am trying to see where this is happening, but my hidden fields do not have this problem:
![image](https://user-images.githubusercontent.com/5607939/86983596-8ccc4180-c18c-11ea-9c37-69608755d611.png)

Then in the HTML:
![image](https://user-images.githubusercontent.com/5607939/86983660-be450d00-c18c-11ea-8ff4-51ad13a5f44f.png)

Then I just changed it to a string instead of numbers, again testing...
![image](https://user-images.githubusercontent.com/5607939/86983715-e46aad00-c18c-11ea-952d-3791823657c7.png)
But again it is correct in the XML:
![image](https://user-images.githubusercontent.com/5607939/86983738-f77d7d00-c18c-11ea-8f5b-8c0e9c3e8372.png)
Also correct in the HTML when rendering:
![image](https://user-images.githubusercontent.com/5607939/86983770-082df300-c18d-11ea-9e34-9ab12025395f.png)

Therefore I am not able to reproduce the issue.

**Comment by jcodewalker** [comment]
please, try with an empty default value (default="")
