### ISSUE TITLE
custom value doesn't work in component config tab

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#579]
### Steps to reproduce the issue
create a new field
![custom-value-1](https://user-images.githubusercontent.com/49115855/87456579-6fbdc580-c607-11ea-9997-633c822c13f5.jpg)

![custom-value-2](https://user-images.githubusercontent.com/49115855/87456553-65033080-c607-11ea-87ed-f2c4cbcc6901.png)

add the field to component configuration tab and set a custom value
![custom-value-3](https://user-images.githubusercontent.com/49115855/87456644-87954980-c607-11ea-87a5-f2db305d807e.png)

### Expected result
Option with value 2 to be shown selected

### Actual result
![custom-value-4](https://user-images.githubusercontent.com/49115855/87456729-a398eb00-c607-11ea-9743-1987f034e824.png)

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.11.2
- Browser:

**Comment by Llewellynvdm** [comment]
The custom value in the config does work, since it works as the default on install, not after. So if you uninstall your component and the install you will see the default working. So it can't be used after the release of your component.

But then you can also set the default of the field and that make sure the field is by default set to that value, but not completely the same as the config default (which gets placed in the DB). So setting both the config and the field default the same is the best option.

So example:
![image](https://user-images.githubusercontent.com/5607939/87843179-9eab9400-c8b2-11ea-8030-63a944465881.png)

In the component install script.php:
```php
/**
 * Called after any type of action
 *
 * @param   string  $type  Which action is happening (install|uninstall|discover_install|update)
 * @param   JAdapterInstance  $parent  The object responsible for running this script
 *
 * @return  boolean  True on success
 */
public function postflight($type, JAdapterInstance $parent)
{
	// get application
	$app = JFactory::getApplication();
	// set the default component settings
	if ($type === 'install')
	{
		// Install the global extenstion params.
		$db = JFactory::getDbo();
		$query = $db->getQuery(true);
		// Field to update.
		$fields = array(
			$db->quoteName('params') . ' = ' . $db->quote('{"autorName":"Llewellyn van der Merwe","autorEmail":"joomla@vdm.io","default_accesslevel":"1","add_isis_template":"1","activate_that_info":"0","the_relation_type":"1","placeholder_prefix":"member","check_in":"-1 day"}'),
		);
		// Condition.
		$conditions = array(
			$db->quoteName('element') . ' = ' . $db->quote('com_mycomponent')
		);
		$query->update($db->quoteName('#__extensions'))->set($fields)->where($conditions);
		$db->setQuery($query);
		$allDone = $db->execute();
```
![image](https://user-images.githubusercontent.com/5607939/87843258-56d93c80-c8b3-11ea-849e-d8b2685c5202.png)

But as you can see it will only be added on install, and not again there after.

**Comment by jcodewalker** [comment]
I think this option can be applied in a more powerful way letting it go in the xml code of the field, overriding what is set (if any) in the field definition. In this way there is no needs of a postflight script. But more important we can use the same field in different instances, customizing it a bit on every instance.

If you remember, one of my first concerns was related to the use of fields. Right now we have to produce two different fields even if we just want to assign a different default value to them (or write a lot of code for a post flight, that is the way I do it right now, not to mention we have to change it accordingly with the field changes, and this is when it comes my willing to use the custom value option)... From my personal point of view, a big step would be to have the option to add custom label, description, default value and display option when we add a field to either an admin view or component/module/plugin config/menu. We could save an incredible amount of work, not to mention the better field organization.

I saw you rewrote the admin view fields add form, so now there would be the space to include these options and the same could be done with the component config fields. I this this is the best way to use the field type and field definitions you set in JCB, which are very powerful tools but they are not fully exploited.

Just my point of view.

**Comment by Llewellynvdm** [comment]
This is done in the field, just add the default to the field to get it in the XML.

**Comment by Llewellynvdm** [comment]
This is done in the field, just add the default to the field to get it in the XML.

So the script default is done with the default value you set when you add the field to the config area of the component, and the field default is used in the XML. This is how JCB works everywhere the fields are used, like the plugins, and modules.

This has worked for us in all our projects with JCB, and when we needed more we wrote custom code in the getForm are of the admin view.

We will not be changing this anytime soon, since it will break things for many upstream developers, and I hate it if that is being done to me, so I will not just do that.
