### ISSUE TITLE
jcb can not compile placeholder in Target Path

### ISSUE THREAD

**Issue by saman222** [vdm-io/Joomla-Component-Builder#589]
hi
### Steps to reproduce the issue
go to edit the compnent>Settings tab>click on "Edit component files folders for this joomla component" and go to Editing the Component Files & Folders
and use component placeholder such as [[[component]]] in Target Path, then save and close then compile component.

### Expected result
work and translate [[[-------]]] to correct word.

### Actual result
return this error:
Warning
Field required: Target Path
and exit and not save anything. when you click on "Edit component files folders for this joomla component" button
and then come back to that page, there is no change in Target Path. 

### System information (as much as possible)
- OS Name & Version: last 
- MySql Version: last
- Apache Version: last
- PHP Version: 7.2
- Joomla Version: 3.9.20
- JCB Version: last
- Browser: chrome

**Comment by Llewellynvdm** [comment]
The target path at this time only has the following placeholder options:
```
Constant Paths

// The path to the administrator folder.
JPATH_ADMINISTRATOR
// The path to the installed Joomla! site, or JPATH_ROOT/administrator if executed from the backend.
JPATH_BASE
// The path to the cache folder.
JPATH_CACHE
// The path to the administration folder of JCB component.
JPATH_COMPONENT_ADMINISTRATOR no ideal to use
// The path to the site folder of JCB component.
JPATH_COMPONENT_SITE no ideal to use
// The path to the JCB component.
JPATH_COMPONENT no ideal to use
// The path to folder containing the configuration.php file.
JPATH_CONFIGURATION
// The path to the installation folder.
JPATH_INSTALLATION
// The path to the libraries folder.
JPATH_LIBRARIES
// The path to the plugins folder.
JPATH_PLUGINS
// The path to the installed Joomla! site.
JPATH_ROOT
// The path to the installed Joomla! site.
JPATH_SITE
// The path to the templates folder.
JPATH_THEMES

JPATH_SITE is meant to represent the root path of the JSite application,
just as JPATH_ADMINISTRATOR is mean to represent the root path of the JAdministrator application.
JPATH_BASE is the root path for the current requested application.... so if you are in the administrator application:
JPATH_BASE == JPATH_ADMINISTRATOR
If you are in the site application:
JPATH_BASE == JPATH_SITE
If you are in the installation application:
JPATH_BASE == JPATH_INSTALLATION.
JPATH_ROOT is the root path for the Joomla install and does not depend upon any application.
```
Those are just in the advanced area, on the **File Path** values. Then the **Target Path** can only be set in relation to the installation package. Like the description says `Path in relation to the folder structure in the install package, unzip the compiled zip file to see the structure.`

So the component name is not ever available int the **Target Path** since we are in the installation zipped package. I will close this issue, since we do not see the need to add any dynamic values inside this area. As the Component Files & Folders area can just be linked to one component, should you want the component name in a path, you can just manually add it, since no other component will reuse this Component Files & Folders area.
