### ISSUE TITLE
Problem with component creation

### ISSUE THREAD

**Issue by antarey** [vdm-io/Joomla-Component-Builder#611]
I did everything according to the instructions 
https://www.youtube.com/watch?v=1KBBtQUxMTc&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=2&t=0s
In the Dashboard of my component, when I click the add button, a completely empty form opens - my fields are gone.
If I open the list and click the add button, nothing opens.
All rights are set - allowed.
What am I doing wrong?

https://www.dropbox.com/s/mt8vt7w1nbhittf/JCB_test.zip?dl=0

### System information (as much as possible)
- OS Name & Version: Win10
- MySql Version: 5.7.28
- Apache Version: 2.4.35
- PHP Version: 7.3.12
- Joomla Version: 3.9
- JCB Version: lates
- Browser: opera

**Comment by Llewellynvdm** [comment]
Greetings @antarey, it can be one, or more of a thousand things... I am sorry but I can not help you resolve this issue since I do not work on Windows at all. For best result please try to use the [bitnami stack](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=72) this could resolve things.

For more help please share your problem [on the forum](https://vdm.bz/jcb-forum), since many in Joomla agree that Windows is an excellent OS, and so there could be some on the [forum](https://vdm.bz/jcb-forum) that could help you.

Please understand that your issue is not directly JCB related but, related to your environment, for which reason I will close this issue. My company and nearly thousands of other developers use JCB every day, so for that reason I believe we have a stable working system, when the environment is correct.

Let me know if you have any further questions on this, you are most welcome.
