### ISSUE TITLE
Permission settings in component view wont change by AJAX request

### ISSUE THREAD

**Issue by bM8qwa** [vdm-io/Joomla-Component-Builder#629]
### Steps to reproduce the issue

- Compile the Demo component (or any other component)
- Create new Look or open an existing one
- Enter "Permissions" tab of the Look
- Select any usergroup and any action, try to change "Select new setting"

### Expected result
Selected setting appears in "Calculated setting" immediately without saving page.

### Actual result
Selected setting does not appear in "Calculated setting", spinner rolls. Though if you save the page, selected setting for permission saves too.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 5.5.5-10.4.17-MariaDB 
- Apache Version: 2.4.46
- PHP Version: 7.4.13 
- Joomla Version: 3.9.23
- JCB Version: 2.12.3
- Browser: FF 84.0

### Additional comments
1. On selecting new setting, error appears in the console:
```
Uncaught TypeError: document.getElementById(...) is null 
in http://localhost/Site/media/system/js/permissions.js at 1:823
```
2. In global settings (in "Configuration") of the same component AJAX works like a charm, no problem.

**Comment by Llewellynvdm** [comment]
This is a hateful issue since it is really a Joomla convention that assumes that all views that have permissions [have a title filed](https://github.com/joomla/joomla-cms/blob/3.9.23/media/system/js/permissions-uncompressed.js#L47). I have been asking multiple times to change things in J3. But due to the urgency to get J4 out, it is complicated.

I am looking at an option to resolve the issue... but honestly the workaround is a major issue. We have to first check if the view has a title field, and if it doesn't we need to add one, and in the getForm method remove the field again, to avoid database  conflicts... serious pain.

**Comment by bM8qwa** [comment]
Thanks! Never could expect the permission behavior dependence on the view field set or the particular field name...

You certainly know, that the same wrong AJAX in permissions happens to JCB views themselves, let's say Joomla Components or Admin Views. 

Adding the "title" text field to the Look view in Demo component instantly fixes the permission things. Hopefully the field type of "title" could be "hidden" to use it as a patch, if I don't want the "title" in the view fields.

Closing this issue is up to you.

**Comment by Llewellynvdm** [comment]
Ok so I added a fix... please test the staging branch an let me know. Painful workaround... but no other option at this stage.

**Comment by bM8qwa** [comment]
Thank you.

Tested the branch [cc201b8](https://github.com/vdm-io/Joomla-Component-Builder/commit/cc201b8ec0b99ddda1f49d8b57c44e3b2088903e) with Demo component back end.

AJAX settings change works fine.

However, "no permissions tab should be added if no permissions are set in a view", right? But The "Permissions" tab stays with "Looks Edit Version" action in it, even if no permissions are set in the "Look" view, and even if "Enable Versions" is set to No in global settings of the Demo component.

**Comment by Llewellynvdm** [comment]
> Front end: On setting change, error raises "An error has occurred while fetching the JSON data: HTTP 500 status code. Internal Server Error"

JCB does not actually do anything to make this work... it is all Joomla, and therefore all the workaround issues. I will not at this time spend more on this, unless you can fix the front-end issue, it will wait for some who can.

> Besides, "no permissions tab should be added if no permissions are set in a view", right?

Yes that is right, and this I have tested with the hello world component, you need to check the [access.xml](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/access.xml) file to make sure no permissions are added to the view. Since you could have a field that still has permissions, and then it will still be added. The [hasPermissionsSet](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L1476) method checks for any permissions. You will see it first check history, then the view permissions, and then the field permissions.
