### ISSUE TITLE
After I updated to the latest version 

### ISSUE THREAD

**Issue by Safweb** [vdm-io/Joomla-Component-Builder#682]
After I updated to the latest version .
**When I try to compile, this result comes up:** 
Warning
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin/assets/css
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin/models
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin/models/forms
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin/sql
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin/sql/updates/mysql
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin/views
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/site/assets
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/site/assets/images
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/site/controllers
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/site/language
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/site/layouts
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/site/views
Failed deleting index.html
Failed deleting default.xml
JFolder: :delete: Could not delete folder. Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/site/views/looks/tmpl

System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 7.4.15
- Joomla Version: 3.9.25
- JCB Version: 2.12.8
- Browser:

**Comment by Llewellynvdm** [comment]
Can you give me more details as to what system your on and stuff... I am not yet able to replicate this, so I can say what is wrong.

**Comment by AlexZion** [comment]
> Can you give me more details as to what system your on and stuff... I am not yet able to replicate this, so I can say what is wrong.

Hi Llewellynvdm,

I have the same problem, after the last upgrade I can't compile any project without this kind of warning and even if the compiler finish to compile normally when I try to install the project doesn't works, because is missing some file, like the .xml.
That's why I think is some permission related problem, like if the compiler can't read or write anymore in some fundamental place, so the resultant package is missing files and folders.

I'm using it on Bitnami Stack, software versions as follow:

- OS: Bitnami stack using Linux debian 4.19.0-14-amd64
- Apache Version: 2.4.46
- PHP Version: 7.3.27
- MySql Version: 5.5.5-10.3.27-MariaDB
- Joomla Version: 3.9.25
- JCB Version: 2.12.8

I hope those details will help you to find out what's going on withe the last version.

Many Thanks,

Alex

**Comment by Llewellynvdm** [comment]
So the last update only fixed an issue in the compiler view (GUI) it did not touch any of the code that creates the files. This could mean that this is a change in Joomla. I will take a look at this API files of Joomla and see if I find any changes... 

What is strange to me is that I still do not get those errors... and I am also on exactly the same system as @AlexZion just my PHP is 7.3.13 but the rest is the same.

**Comment by Llewellynvdm** [comment]
I also have systems on PHP 7.4 and still no problem.

**Comment by Llewellynvdm** [comment]
This is where the files are found in Joomla that JCB use to create folders and move files...
https://github.com/joomla/joomla-cms/tree/staging/libraries/src/Filesystem

This seems to be the only file that changed in the last update:
https://github.com/joomla/joomla-cms/blame/staging/libraries/src/Filesystem/Path.php

The resolve method was added. So if anything changed it is on the Joomla side of things... not sure what this change a this point means but if you are able help me look back from the resolve method all the way to this JCB area:
https://github.com/vdm-io/Joomla-Component-Builder/blob/3c3951ae83e92b570e8a086b02677335a8f47cdb/admin/helpers/compiler/b_Structure.php#L2653

There is a possibility that I would need to add the name spacing to ensure the wrong class is not uses.

But I am trying to find this bug... issue. Should you who are getting the same error are able to do some debugging it will help. Since I don't get those errors on my side.

**Comment by Llewellynvdm** [comment]
I am wondering if this is a class clashing issue... add the following lines to the header of this [b_Structure.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/3c3951ae83e92b570e8a086b02677335a8f47cdb/admin/helpers/compiler/b_Structure.php#L14) file.
```php
use Joomla\CMS\Filesystem\File;
use Joomla\CMS\Filesystem\Folder;
```
Then replace all these strings:
from -> to 
- `JFile::` -> `File::`
- `JFolder::` -> `Folder::`

Then compile and lets see if the errors still come up...

**Comment by Llewellynvdm** [comment]
Seems like you will also need to do the same with the [a_Get.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/3c3951ae83e92b570e8a086b02677335a8f47cdb/admin/helpers/compiler/a_Get.php) and [f_Infusion.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/3c3951ae83e92b570e8a086b02677335a8f47cdb/admin/helpers/compiler/f_Infusion.php) files.

**Comment by Llewellynvdm** [comment]
Hmm there are also more in the [helper class](https://github.com/vdm-io/Joomla-Component-Builder/blob/3c3951ae83e92b570e8a086b02677335a8f47cdb/admin/helpers/componentbuilder.php), so you will also need to to it there... I am going all over JCB converting to namespacing for the folder and file classes. So wherever you may still find `JFile::` and `JFolder::` you need to add the header namespacing, and then update the text string by removing the `J`.

I will push this fix out in a few hours when I am sure it resolves the issue for you... as this could be it. Since I know the `JFile: :read: Unable to open file: ./libraries/phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/NamedRange.php` class also has a JFile class... and it could be that JCB for some weird reason is calling that class instead of the Joomla core API. But in my environment it does not. But it could be since you get that kind of error on your system.

**Comment by Llewellynvdm** [comment]
I have pushed the changes I asked you to make to the staging branch, please test.

**Comment by AlexZion** [comment]
> I have pushed the changes I asked you to make to the staging branch, please test.

Hi Llewellynvdm,

before I talk about what you change and the test result let me share with you a very strange episode I had this morning, meybe it will help you to understand what's going on. While I was reading your answer I open up my virtual machine (bitnami joomla) and before I start to change things I tried to compile a project and even if I got all the errors, when I tried to install it worked perfectly, just once. That's weird, it seems like something "random" is happening ?
 
Now let's talk about the test, I don't know what you mean by saying "make to the staging branch" but I saw the changes you did and I edit all the file involved reflecting the modify you did.

As result now when I compile I see just sometimes an error deleting a folder, while all the other warning disappears, but the resultant package is still NOT installable

**Comment by Safweb** [comment]
I have tried with your update and the only error I get now is this one:
Warning
JFolder: :delete: Could not delete folder. Path: /***/***/***/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3

When I then press compile component.
Do I get this error message: 
Warning
JInstaller: :Install: Can't find Joomla XML setup file.
×
Error
Unable to find install package
Could not install component!

**Comment by Llewellynvdm** [comment]
Okay it seems there is still a few I missed, and it also looks like this direction is fixing the issue... so I will search the whole project and convert all to the namespace convention. Then this issue should be resolved.

**Comment by Llewellynvdm** [comment]
Okay this should cover all the compiler area.. and even some of the rest of the system. Please test and let me know!

**Comment by Llewellynvdm** [comment]
Soon as I can get answer from you that the issue is resolved I will push out  release update.

**Comment by AlexZion** [comment]
> Soon as I can get answer from you that the issue is resolved I will push out release update.

I tried to apply all the changes you did, but I get a strange behavior, If I try few different time to compile the same project I get always different result in terms of warning and installation. Some time I get an installable package even if I get compiling warning, other time I can't install the result package even if I didn't get compiling warning.

At this point I guess I did something wrong during the process, so maybe you shouldn't consider my results

**Comment by Llewellynvdm** [comment]
Okay so over the last 6 years of JCB I have never had any of these issue (folder and file related), and still don't. So I am trying to fix something here that I can't see. Very hard to do... believe me.

Since I can't duplicate the error, and have never seen it, and everything works as expected in over 100 project on my 5 different JCB installs, on different servers, and different environments it is hard for me to understand what is wrong.

Yet I must admit that none of my environments run on-top of a Windows parent system, they are all fully Linux based, and this looks like it will never change for me. Now I know if you run virtualization system like bitnami it should not matter what parent system you have. But if the parent system is Windows then it seems "yes seems" like some of that still seeps into the PHP behavior, specifically on the file folder side of things.

So my advice to you at this point is.. when you import a JCB package like Sermon Distributor and compile that, does it work, or the demo package. Since these we know work well on many different systems. Since if they fail we can be sure its not JCB and that it is your environment setup.

I am trying to resolve the environment issues... always pointing to bitnami. But since you are also using it, and yet getting issues we may have another issue. Let me ask you have you touched the folder and file permissions at any time? This is what it should be https://serverfault.com/a/657871/431927.

**Comment by SimonvanDoorne** [comment]
Hi Llewellyn,

To add to this report this has been happening to my components as well. 
What we did was :

- Create a fresh domain without anything installed
- Install a fresh Joomla site and make sure it is updated
- Install newest version of JCB
- Create a simple component with 1 backend view, 1 site view, and 2 fields
- Compile

Server specs:
CentOS 7
Apache/2
FastCGI 
PHP 7.4.16
 5.5.5-10.4.18-MariaDB

When i compile i get around 150 errors 
![errors_1](https://user-images.githubusercontent.com/54291562/110539634-c8594a00-8125-11eb-91d1-61d8d244e492.PNG)
All of them are 'cannot open file' errors, except 2. Both of those are 'cannot remove folder' errors.
Then after this i still get the message that the build is complete but some files are missing thus creating errors on installing. 
To reiterate: EVERYTHING is fresh. There are no other components/plugins/modules installed other than JCB and the stock joomla items. File rights on the ftp were set to 775 (i believe).

The strangest thing about it all is that when i created another admin view, and compiled everything, but when i tried to compile again it came with the same errors as described as above. 

How can i help in trying to resolve this problem? Happy to help any way i can!

**Comment by Llewellynvdm** [comment]
Okay so this started happening with the upgrade to Joomla 3.9.25?

Then the newest version of JCB will still have the issue, as the fixes we have applied are not yet in a new release. To get those fixes download this package: https://github.com/vdm-io/Joomla-Component-Builder/archive/08d529aba970a882e096393b34bf3eb53ad1536f.zip

Once you have updated JCB with this downloaded version... run another test and let me know.

**Comment by EvDoorne** [comment]
The system we tested with was setup yesterday with 3.9.25 (no upgrades from previous J! versions). However, we tried on 2 different local development servers first, with exactly the same results. Both are running J! 3.9.23 (Both on JCB 2.2.18 as well).

**Comment by Llewellynvdm** [comment]
What browser are you using? please be sure to use Firefox, and only Firefox....

**Comment by EvDoorne** [comment]
Ofcourse .... that's the one.

**Comment by EvDoorne** [comment]
After installing the package with fixes from https://github.com/vdm-io/Joomla-Component-Builder/archive/08d529aba970a882e096393b34bf3eb53ad1536f.zip , both our systems are now working well. The compiler has no issues anymore and compiled components install without errors.

So: solved.
