### ISSUE TITLE
Component does not download

### ISSUE THREAD

**Issue by canfine** [vdm-io/Joomla-Component-Builder#69]
After compiling demo component Button "download" does not work.
Temp folder is empty.
 "Install" button is ok. 
 
Windows 10 AMD64
DB 5.5.50
 	utf8_general_ci
	utf8mb4_general_ci
PHP 	5.6.23
Apache
Интерфейс между веб-сервером и PHP 	apache2handler
Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by Llewellynvdm** [comment]
Once you install the component it removes it from the temp folder. Need to compile it again to find it in the tmp folder. Then it should also download, if not find it in the tmp folder.

**Comment by Llewellynvdm** [comment]
Just a side note, JCB works best on Linux... we have had known issues with Windows. But it should work for the most part.

Reality is both core developers on JCB are working on Linux only.

**Comment by mwweb** [comment]
I just went through working in Windows, using xampp, with trouble. I had the option of using my were server, configuring a virtual machine, or using a virtual 'box". I selected the virtual box. It was relatively quick and simple to set up. 

If instructions are needed/wanted for this, please let me know, and i would be happy to point people in three right direction to have a joomla development environment running in Ubuntu on their windows or Mac machines in a matter of minutes.

**Comment by Llewellynvdm** [comment]
Sure, make a tutorial, and add a link any where, even here. I don't mind :+1:

**Comment by mwweb** [comment]
Great thing is...the developers of JoomlaTools (who created the "Joomla in a box") already have tutorials.

https://www.joomlatools.com/developer/tools/vagrant/

There is a little "quirk" at least with Windows. I've read that there are similar issues with Mac. The "quirk" is related to how Vagrant updates the shared folders. There is, generally speaking, a delay between the files on the "box" updating the shared folders on the "host" computers drive, which results in a 503 Service Unavailable. A wait of 10-15 seconds, then click in the address bar and press enter and it's good. There are a few "workarounds" for this, but I'm too busy right now to dig into them.

Since setting up the Joomla Box, I haven't been having compile issues like I was with XAMPP.
