### ISSUE TITLE
Field Name (number) changed to text

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#7]
I encountered an issue that I'm not sure if it was by design or an issue.

When creating a field, if I set the address to something like myfield2, upon compile and install the database shows the field as myfieldtwo. It takes the 2 and converts it to two.

This also happens with default values. If I set default="10" it converts this to "ten" upon compile and install.

It looks like this only happens in fields.

**Comment by Llewellynvdm** [comment]
Yes you are right it is by design. Since fields are used in so many conventions where numbers don't work well and can cause errors. We chose to just convert all field **names** to text only.

As far as I know the default value is not changed so if you can give me a link to the code I can take a look. It could be that you are speaking of default values in another way than I am understanding.

So to me default values is in the fields area `default="10"` will stay 10.

Now if you need to iterate fields and therefore want the numbers there is a way to do this with the same function in the helper class called **safeString**.

So lets say you have four fields myfield1 to myfield4 that you want to target you can do the following:
```
$items; // this is the date from the Database
$bucket = array(); // to store values
$fields = range(1,4); // the iterate fields
foreach ($items as $item)
{
	foreach ($fields as $field)
	{
		$fieldName = ComponentHelper::safeString('myfield'.$field);
		$bucket[] = $item->$fieldName;
	}
}
```
You can in the helper file look at the safeString method to see what it does.

Hope this helps.

**Comment by Llewellynvdm** [comment]
Just a headsup note, if you make the default field in fieldtype translatable then it will change it to a string.
