### ISSUE TITLE
During compilation I get Errors

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#703]
I just installed Compnent builder on a fresh Joomla installation. Used the demo component to install.

I get the error:
JFolder: :delete: Could not delete folder. Path: /var/www/vhosts/acceptatie-server.nl/httpdocs/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/libraries/phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Pdf
Failed deleting Parser.php
Failed deleting Workbook.php
Failed deleting Worksheet.php
Failed deleting Xf.php
JFolder: :delete: Could not delete folder. Path: /var/www/vhosts/acceptatie-server.nl/httpdocs/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/libraries/phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xls
Failed deleting Xlsx.php
Failed deleting Chart.php
Failed deleting Comments.php
Failed deleting ContentTypes.php
Failed deleting DocProps.php
Failed deleting Rels.php
Failed deleting RelsRibbon.php
JFolder: :delete: Could not delete folder. Path: /var/www/vhosts/acceptatie-server.nl/httpdocs/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: /var/www/vhosts/acceptatie-server.nl/httpdocs/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin
Copy failed: /var/www/vhosts/acceptatie-server.nl/httpdocs/administrator/components/com_componentbuilder/compiler/joomla_3/index.html to /var/www/vhosts/acceptatie-server.nl/httpdocs/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_3__J3/admin/index.html

Als I get some notice messages. 

![image](https://user-images.githubusercontent.com/3889668/111874958-9357bd80-8997-11eb-9a39-06d55d00dee0.png)

What could the issue? Before I never had issues with JCB.

Best regards,

Arjen Schrijvers

**Comment by Llewellynvdm** [comment]
Joomla seems to have made changes to the File class, well that is as much as makes sense to me.

- Please check the folder paths in the global options under the tab->folder paths
- The check that Apache (user) has access to the folder JCB needs to write in and from

We had this issue here https://github.com/vdm-io/Joomla-Component-Builder/issues/682 and it was resolved... please check over the conversation.

Then I saw you send me a pro-member request... I would like to know did you get the last Pro-Member Newsletter that we now send out from sendinblue?

**Comment by Schrijvers123** [comment]
Thanks I will check later today.

"Then I saw you send me a pro-member request... I would like to know did you get the last Pro-Member Newsletter that we now send out from sendinblue?" Nope, I didn't received it. When was it send?

**Comment by Schrijvers123** [comment]
Hi Llewellynvdm,

Issues solved. 

The issue was that I was using Microsoft Edge Versie 89.0.774.57 (Officiële build) (64-bits)

After testig it in Firefox 86.0.1 (64-bits) it was working.

So I did some test with some browsers on Windows:

Firefox 86.0.1 (64 bits) **working**
Chrome version 89.0.4389.90 (Officiële build) (64-bits) **Not working**
Microsoft Edge Versie 89.0.774.57 (Officiële build) (64-bits) **Not working**
Opera 68 **Not working**
Brave Versie 1.21.77 Chromium: 89.0.4389.90 (Officiële build) (64-bits)  **Not working**

My conclusies the only browser that is working on windows is Friefox. All Chromium based brwosers will cause errors. 

Any idea why?

Best regards,

Arjen

**Comment by denovoit** [comment]
I've had similar issues on a localhost installation (Mamp Pro) on MacOS / Safari. The weird part is, I could try to compile 10 times and every time, the installation of the compiled component would fail, and then without doing anything, it would install. I will try on another browser, and also install a backup on my production server, and se if the issue remains there as well.

**Comment by Schrijvers123** [comment]
Let us know. Could be that some settings om Mamp Pro are not correct. Normal Safari has no issues. 
Please check the folder paths in the global options under the tab->folder paths and check that Apache (user) has access to the folder JCB needs to write in and from

**Comment by denovoit** [comment]
I've tried using Firefox for a while now, and so far no errors. So at least in my end, the errors during compile/installation seems browser related, so perhaps a JS issue?

**Comment by Llewellynvdm** [comment]
The fact that JCB works in Firefox and not in Chromium based browsers is yet unknown to me. This is an old issue actually and the outcome was that we all just USE Firefox in compilation of the of components.

Yet the fact that Chromium based browsers effect on server-side outcome is unacceptable, and concerning to say the least. This means as a localhost system Chromium is effecting the PHP classes. Since none of the files being build, or the data being generated is ever done with JS... ever. The [button](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/compiler/tmpl/default.php#L153) in the compiler area [post](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/compiler/tmpl/default.php#L55) to the [controller on the server](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/controllers/compiler.php#L75) and from there it is [all PHP](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/controllers/compiler.php#L96), until the page reloads and shows the build outcome. So if any of you can show me where a browser gets the right to effect the permissions on the server we may have discovered a major bug/loophole in the Chromium based browsers.

**Comment by Llewellynvdm** [comment]
I am closing this... but the conversation is welcome to continue...

**Comment by Llewellynvdm** [comment]
@Schrijvers123 please check your spam, since we did send out mails to the PRO members just last week.
