### ISSUE TITLE
Missing images in the free version Demo component

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#81]
After installing the free version and going to compile the demo version to see if I'm going to use it and then pay the $299 I noticed right away some missing images. See the screenshots below:

https://goo.gl/vMCsCf
https://goo.gl/B3Dijr

**Comment by mwweb** [comment]
I'll respond. Prior to my getting JCB, I had never developed a component. I need to, but nothing had the functionality I wanted: develop, then easily modify/update. JCB did it for me. I'm nearing release of my component (pushing for beta at the end of the month).

As far as the missing images in the demo component, that is because it is looking for the images in the folder on compile. For "Look" it was looking for images/WoodMannequin-icon.png, but that image isn't in your images folder on your Joomla! install.

To see how this works, go to admin views, then edit the "Look" view. At the bottom of the Settings Tab (the one that initially should open), click on icon. Select, or upload, and icon/image. Recompile/install and the image you selected should show there. 

On compile, JCB copies the icon image from the images folder to the components assets/images folder, but since the image didn't exist in the images folder, there was nothing to copy, showing a "broken" reference to the image, since the image is referenced in the admin view.

I hope this helps.

**Comment by kevincam3** [comment]
Thanks for the explanation. I understand why they don't show. I just thought you should include them so that they aren't missing for people when we install and test the demo. Just not a good look to install a component and see broken images all over the place.

**Comment by Llewellynvdm** [comment]
@kevincam3 the demo ships without images, but you can fix this.

Go to this [repository](https://github.com/vdm-io/JCB-Packages) and download this [package](https://github.com/vdm-io/JCB-Packages/raw/master/JCB_demo.zip), and follow this [tutorial](https://youtu.be/lkE0ZiSWufg) :+1:
