### ISSUE TITLE
Feature Request - Custom Code identifier (id) on edit view

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#879]
When editing a custom code entry (in the Custom Codes edit view), you can see the Component and the File Path, but there is no display of the Custom Code item number/id on the screen.

Occasionally there might be more than one custom code in a certain file, but you can't see which one you are in.
Esp. when you are editing custom code entries it would be helpful to see the ID number, like is possible on the custom code list view.

This is not a huge priority, it would just be a nice, time-saving feature.

**Comment by Llewellynvdm** [comment]
It seems like your using lots of custom code [smile]

You should [watch this tutorial](https://www.youtube.com/watch?v=QGMURJI_Mds&list=PLQRGFI8XZ_wuzAQELTUUIDdqKFmLP9lSl&index=12).... since I do not recommend this feature to be used that often.

What should instead happen is you should explain to us what you thing can be done better and let us improve JCB to catch this option. Yet what I have often seen, even with advance developers is that they don't know JCB has a solution for some thing... `my bad for not documenting it` and then they reinvent the wheel.

Remember that JCB itself has nearly no **RAW IDE** custom code. Yes we use custom code, but only **GUI** custom code, and for those we already have the id's in place.

One more thing, we have found that since the introduction of POWERS to JCB we hardly have any custom code in the new component we are building, its all moved to POWERS. Which is the more correct PHP way of development. Working with interfaces, traits, and classes is much better, cleaner, and easier to maintain. But yes you need to know more PHP...

But okay, I think we can keep your request in mind as we refactor JCB for Joomla 4.

**Comment by cpaschen** [comment]
Well, actually, the reason for needing the id is so that I can see which custom code I'm in so that I can move the custom code to gui (and some day powers).  I've used custom code when I've just needed to make something work and there wasn't an existing solution. But many of those issues have been added and there's a gui way to do it. I'm just trying to update my components.
But once I get into the custom code screen I can't remember which code I was working on :-(
Again this is a really LOW priority, and ONLY if it would be an easy fix.
