### ISSUE TITLE
Admin View - Order override problem

### ISSUE THREAD

**Issue by JohnnyMcWeed** [vdm-io/Joomla-Component-Builder#88]
Reproduce
- Making some admin views
- Adding them to a component 
- Change its order (last column)

Should override the the default order I think, but is not taken into account.

**Comment by JohnnyMcWeed** [comment]
Order on overview from top to bottom (as you can't see the name): zoo - elephant - datasheet

![adm](https://cloud.githubusercontent.com/assets/9844452/26538190/2887858a-4445-11e7-9999-dc104467af20.png)
![adm2](https://cloud.githubusercontent.com/assets/9844452/26538191/288908a6-4445-11e7-97cf-b1f4c017491f.png)
![adm3](https://cloud.githubusercontent.com/assets/9844452/26538192/28891274-4445-11e7-8577-f1fd0520073d.png)

**Comment by Llewellynvdm** [comment]
Okay you will need to update the admin-view __system name__ to reflect the correct name in the dropdown. You will also then be able to better manage the order :+1: 

Then you will see Joomla has a glitch when you open the modal some of the radio buttons are not selected, just close the modal and open it a second time. This is a Javascript issue that I have not had the time to report to the Joomla team... but this is a work around.

So you basically open the modal of the repeatable field twice to insure it loads the data as stored in database.

The order works this I am sure of since I have many components and it gets ordered correctly in all of them.

**Comment by JohnnyMcWeed** [comment]
Ok, the problem here was the same as for #89 - caused by starting with number 0 it couldn't put it in the right order.
