### ISSUE TITLE
On compiling demo component in clean new installation there is attempt to delete non-existing folder.

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#896]
On compiling demo component in clean new installation there is attempt to delete non-existing folder. Probably, the folder does not exist because its parent folder was removed before attempt to delete child folder. Please, see screenshot.

![Screenshot from 2022-04-17 05-36-16](https://user-images.githubusercontent.com/4179340/163697868-8056856b-71e7-41c4-92ba-2157dc9dd862.png)

**Comment by Llewellynvdm** [comment]
I work with JCB everyday, and I have hardly ever seen this issue, and I am working on many new systems and various environments. I don't know your setup completely, except that you may have use OctoJoom... once thing to make sure is that you use Firefox to run JCB compiling.

I will close this since it does not seem like a bug, but like a local setting that may not be correct in your JCB global configurations, and yet the result of the build I assume was correct.
