### ISSUE TITLE
Upon trashing the component its Language Translations are still present.

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#905]
Upon trashing the component its Language Translations are still present.
Please, see screenshot.

![Screenshot from 2022-04-17 14-58-17](https://user-images.githubusercontent.com/4179340/163713405-ae3897cd-0490-48e8-a528-d98911fc7655.png)

**Comment by Llewellynvdm** [comment]
Yes because language strings are shared across components and could be reused in most cases, we don't ever remove them. We do archive them if on compilation a string is found not to be linked to any component anymore... but for the most part we think of the language area as a shared area and so it is not tightly coupled to the components.

I don't think we will change this behavior, as translation is one of the major strengths of JCB.

So to see strings archived and confirm the expected behavior, compile an extension and you will see all language string that are not linked to any component, module and or plugin... gets archived. Or that what I think should happen, have not been in this area for ages actually... so let me know.
